### ISSUE TITLE
about sampler GLSL  shader specification  

### ISSUE THREAD

**Issue by absinthe99** [KhronosGroup/glslang#1009]
According to Khronos GLES 3.1 ES  shader language specification,   
---------------------------- I see this version of specification.
Language Version: 3.10
Document Revision: 4
29 January 2016
Editor: Robert J. Simpson, Qualcomm
----------------------------
I found a strange notation like as below.
last RESOLUTION paragraph clearly said that *dynamic indexing of sampler arrays is now prohibited*. 
but other paragraph said  *allowed* as if indexing is allowed.   
What does mean this *allowed*?

according to specification.
-----

13.29 Samplers 
Should samplers be allowed as l-values?  The specification already allows an equivalent behavior:
Current specification: uniform sampler2D sampler[8];
  
  int index = f(...);
  vec4 tex = texture(sampler[index], xy); // *allowed*

Using assignment of sampler types:
  
  uniform sampler2D s;
  s = g(...);
  vec4 tex = texture(s, xy); //  not allowed
  
RESOLUTION:  Dynamic indexing of sampler arrays is now prohibited by the specification.  Restrict 
indexing of sampler arrays to constant integral expressions

**Comment by absinthe99** [comment]
I want a comment.

**Comment by johnkslang** [comment]
That issue is:
 - not from the normative section of the specification
 - not about indexing, but about l-values (it just used indexing in a logical argument in making an equivalence to forming an l-value)

So, I would not use that issue as the overriding authority on sampler array indexing. Instead I would go with what the specification says.  Version 3.2 is more clear:

> 4.1.7 Opaque Types
>
> ...
> When aggregated into arrays within a shader, opaque types can only be indexed with a dynamically
uniform integral expression (see section 3.9.3) unless otherwise noted; otherwise, results are undefined.

However, this is the glslang project, not the specification project.

Do you have a specification issue, or a glslang issue?

For specification issues, see https://github.com/KhronosGroup/OpenGL-GLSL

**Comment by absinthe99** [comment]
Thank you very much for your comment.
And very sorry.  I have only specification issue, not about glslang-issue.

**Comment by absinthe99** [comment]
I guess just now , I have recognized about this specidication.
Thank you very much for explain.
I close this issue.
