### ISSUE TITLE
build warnings

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/glslang#1041]
As of 82e95a3aa5c41e3cfdf045e22cf131922e529b48 there are a couple warning during the linux build.
It would be great to resolve them for the next SDK build.
Thanks

glslang/SPIRV/spvIR.h:68:27: warning: ‘spv::MemorySemanticsAllMemory’ defined but not used [-Wunused-variable]
glslang/glslang/MachineIndependent/iomapper.cpp:419:110: warning: unused parameter ‘is_live’ [-Wunused-parameter]

**Comment by LoopDawg** [comment]
The second is straightforward.  The first is odd.  There's no handle (AFAICS) in g++ to distinguish between the local and global scoped warnings.  Here, I'd argue it isn't up to the header to know whether any random consumer is going to use this globally scoped value.  I'm not completely sold on the global scope warning, but in g++, you can have neither scope, or both.

In any case, #1042 uses the smallest hammer I could find, which still leaves ``-Wunused-variable`` enabled.

There seems to be some history and a bit of contention around this warning, with compiler version specific workarounds to handle things like version control system ID strings not otherwise referenced, and so forth.  Bit of a mess.
