### ISSUE TITLE
atomicCounterDecrement() and SPIR-V OpAtomicIDecrement result values

### ISSUE THREAD

**Issue by jozefkucia** [KhronosGroup/glslang#1067]
`glslang` translates `atomicCounterDecrement()` to `OpAtomicIDecrement`.  This seems to be incorrect because the result values don't match according to SPIR-V and GLSL specifications. The GLSL specification states that `atomicCounterDecrement()`  

> returns the value resulting from the decrement operation

while the SPIR-V spec states that 

> The instruction's result is the Original Value.

I've also tested `OpAtomicIDecrement` with Intel's Anvil driver and Nvidia Linux Vulkan driver. With both drivers `OpAtomicIDecrement` returns the value resulting from the decrement operation.

Is this a SPIR-V spec bug?

**Comment by johnkslang** [comment]
Agreed this inconsistency exists. Will investigate, thanks.

**Comment by pdaniell-nv** [comment]
We discussed this in the OpenGL WG meeting today. The GLSL spec and SPIR-V specs do mismatch. It's intentional that GLSL specifies the return is post-decrement. Since SPIR-V is defined to return pre-decrement then glslang needs to be updated to insert an OpSub(1) instruction to the generated SPIR-V so the GLSL behaves as specified. 

 Assigned to @johnkslang to modify glslang.

**Comment by johnkslang** [comment]
Fixed by https://github.com/KhronosGroup/glslang/commit/48d6e798bc76b8e58be844a8cef8bc6f843a909e.

**Comment by jozefkucia** [comment]
FWIW, multiple Vulkan drivers currently return post-decrement value for OpAtomicIDecrement. It would be good to add a CTS test for this.

**Comment by johnkslang** [comment]
Additionally, I now incremented the generator number (from 1 to 2, in the bottom half of the third word in the SPIR-V binary header).

This is to indicate a semantic change, and allows drivers to react differently to the different generated semantics.
