### ISSUE TITLE
HLSL: feature request, add subpass inputs

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#1069]
The VK_KHR_vulkan_glsl specification adds subpass inputs.  In order to leverage subpass inputs with HLSL shaders, we need some kind of analogue.  I could not find anything in the HLSL front-end for this.  Since this is a Vulkan-specific feature, the ask here is:

* Invent some syntax for exposing subpass inputs/loads in HLSL
* Implement it in the glslang front-end

**Comment by LoopDawg** [comment]
Proposal:

For reference, from [GL_KHR_vulkan_glsl](https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt):

    Types:
             subpassInput
             subpassInputMS
            isubpassInput
            isubpassInputMS
            usubpassInput
            usubpassInputMS

    Functions:
            subpassLoad(gsubpassInput   subpass);
            subpassLoad(gsubpassInputMS subpass, int sample);

    Layout qualifier:
            layout(input_attachment_index = i, ...)


The basic type for Texture and Buffer objects is already encoded in HLSL template syntax - e.g, Texture2D&lt;float4&gt; or Texture2D&lt;int4&gt;, so does not need the 'i' or 'u' prefix.  The template syntax seems natural here too.  Use existing layout(...) extension to specify attachment index.

    layout(input_attachment_index = 1) subpassInput<float4> subpass_f;
    layout(input_attachment_index = 2) subpassInput<int4>   subpass_i;
    layout(input_attachment_index = 3) subpassInput<uint4>  subpass_u;

    layout(input_attachment_index = 1) subpassInputMS<float4> subpass_ms_f;
    layout(input_attachment_index = 2) subpassInputMS<int4>   subpass_ms_i;
    layout(input_attachment_index = 3) subpassInputMS<uint4>  subpass_ms_u;

Like textures, ommitting the template type would default to float4.

Same spelling for the intrinsic, and also the multisample variant (like GLSL where it's overloaded on this spelling).

    float4 result = subpassLoad(subpass_f);
    int4   result = subpassLoad(subpass_i);
    uint4  result = subpassLoad(subpass_u);

    float4 result = subpassLoad(subpass_ms_f, samp);
    int4   result = subpassLoad(subpass_ms_i, samp);
    uint4  result = subpassLoad(subpass_ms_u, samp);

That would naturally extend to the HLSL feature of templatizing on a small user structure:

    struct my_type_t {
        float  c0;
        float2 c1;
        float  c2;
    };

    layout(input_attachment_index = 4) subpassInput<my_type_t> subpass_s;

    my_type_t result = subpassLoad(subpass_s);


Possible alternatives:

* Use the 'i' or 'u' prefix instead of templates.  This doesn't play as nicely with user structs though.
* Do something else instead of / in addition to layout(input_attachment_index).  Like an attribute.
* To match Texture and Buffer keyword style, SubpassInput type could be capitalized.
* To match Sample intrinsic name style, SubpassLoad could be capitalized.

**Comment by danginsburg** [comment]
Adding @dneto0 and @chaoticbob for comment.  Has the syntax for this been decided for the Microsoft HLSL project?  If so, we might as well adopt the same syntax here.  If not, maybe we can get agreement on what the syntax should be for both so we don't have two different ways of doing the same thing.

I don't have strong preferences here, but I do like the subpass_f.SubpassLoad() syntax for similarity to existing HLSL methods.

**Comment by LoopDawg** [comment]
> I do like the subpass_f.SubpassLoad() syntax for similarity to existing HLSL methods.

Yeah... also avoids polluting any global namespaces.

**Comment by LoopDawg** [comment]
Edited to make the method style the proposal's default.  Intrinsic is now listed as a possible alternate choice.

**Comment by johnkslang** [comment]
Note that I already supported a bunch of GLSL layout qualifiers in HLSL, so the parser already accepts `layout(input_attachment_index=X)` and set the attachment index on the variable's qualifier. E.g., this makes SPIR-V with an input attachment decoration:

```
layout(input_attachment_index=1) cbuffer attach
{
    float4 f4;
} buff;
```

```
                              Decorate 16(buff) Block
                              Decorate 18(buff) DescriptorSet 0
                              Decorate 18(buff) InputAttachmentIndex 1
```

**Comment by dneto0** [comment]
> Adding @dneto0 and @chaoticbob for comment. Has the syntax for this been decided for the Microsoft HLSL project? If so, we might as well adopt the same syntax here. If not, maybe we can get agreement on what the syntax should be for both so we don't have two different ways of doing the same thing.

Adding @antiagainst , who really knows what's going on in dxc.

I don't think they're up to subpasses yet.  The method syntax looks good to me.

A difference though is that layout qualifiers in that compiler use C++ attribute syntax instead of GLSL-style layout qualifiers.

See https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#vulkan-semantics

**Comment by LoopDawg** [comment]
PR #1075 (still WIP pending a number of things) has basic support for the proposal above.  I'll flesh it out more.  If there will be desired changes to the proposed syntax above, it'll be easy to tweak the PR to match.

AFAIK, nothing should prevent accepting both the existing layout(...) syntax, which as @johnkslang notes above has been in place for a while, and some C++ style attribute syntax as in @dneto0's link.  #1075 only has layout(...) at the moment, though.

**Comment by LoopDawg** [comment]
Thanks for reviewing, @dneto0 and @antiagainst.  I updated it to mention [[vk::..]].

**Comment by antiagainst** [comment]
@LoopDawg: I'd suggest `[[vk::input_attachment_index(N)]]`. It is using the same keyword as GLSL, so less surprise for developers using both language. Also, [it seems the convention for C++ attribute specifiers is to use snake_case](http://en.cppreference.com/w/cpp/language/attributes).

**Comment by johnkslang** [comment]
FYI, I did a broad add of attribute functionality (not subpass, just attribute).

It includes C++11 style, location, and binding, so I included the work for input_attachment_index as well, so the following now works (though, I don't know what type to apply it to really, that's the subpass subject, not the attribute subject):

```
[[vk::input_attachment_index(4)]]
Texture2D<float4> attach;
```

**Comment by LoopDawg** [comment]
> so I included the work for input_attachment_index as well,

Cool.  I tested that with the latest update to #1075, and it works fine with the new subpass types.  It's included in the new subpass input test case alongside the layout(...) syntax.

I also updated #1075 to support sub-vec4 template types on SubpassInput.  However, templatizing on user structs does not work.  Most of the infrastructure already exists from texturing methods, but there's a limitation in function selection preventing it in this case.  It could be fixed if needed, but it does not seem likely to be a feature encountered in many real shaders, so maybe it could be left as is for now.  (It will print an "unimplemented" error, so it doesn't fail silently).

Is there anything else that should be considered around the subpass input feature which should go into #1075?

**Comment by danginsburg** [comment]
> Is there anything else that should be considered around the subpass input feature which should go into #1075?

This looks good to me.  The one other thing I can think of that we'd need here is the ability to provide binding shifts for the input attachments to the I/O remapper.

**Comment by johnkslang** [comment]
Input-attachment indexes are not participating in any of the I/O mapping stuff.

**Comment by johnkslang** [comment]
Early send... The bindings should still be affected in the same way they would be for whatever type they are (sampler/texture/image).

**Comment by LoopDawg** [comment]
It's falling into the uniform binding shift category right now.  It isn't using the texture shift due to query categorization.  (I.e, ``type.sampler.isTexture()`` and ``.isImage()`` both return false for subpass objects).

This is trivial to change in the io mapper, if we want subpasses to use one or the other.

**Comment by danginsburg** [comment]
> It's falling into the uniform binding shift category right now. It isn't using the texture or image shift due to query categorization. (I.e, type.sampler.isTexture() and .isImage() both return false for subpass objects).

I think the texture category makes more sense.  It is also advantaged by the fact that there are limitations on the number of uniform buffers in the Vulkan API that we already brush up against (12 per stage) whereas we have tons of room to spare in texture bindings.

**Comment by LoopDawg** [comment]
> I think the texture category makes more sense. 

Done.  Also added a test case for SubpassInput vars with ``--auto-map-bindings`` and ``--shift-texture-binding``.
