### ISSUE TITLE
HLSL mixed shadow sample mode conflicts may be avoidable 

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/glslang#1082]
PR #1076 added checks for mixed sampler modes in HLSL shaders.  A particular shader might include a header file which includes conflicting modes, yet only call functions that use a single mode.  This is currently flagged as an error in glslang, even though the conflict is essentially with dead code. 

For example:
```HLSL
struct PS_In 
{ 
    float3 tex0 : TEXCOORD0 ; 
} ; 

Texture2D              shadowTex : register ( t1 ); 
SamplerState           shadowSampler : register ( s2 ) ; 
SamplerComparisonState shadowCompSampler : register ( s3 ) ; 

float ShadowDepth (in float3 tc)
{
    return shadowTex.SampleLevel(shadowSampler, tc.xy, 0).x;
}

float ShadowComp (in float3 tc)
{
    return shadowTex.SampleCmpLevelZero(shadowCompSampler, tc.xy, tc.z);
}

float4 PS_Shadow0 ( in PS_In i ) : SV_TARGET 
{ 
    float value = ShadowDepth(i.tex0);
    float test  = ShadowComp(i.tex0);
    return float4(value, test, 0, 0);
} 

float4 PS_Shadow1 ( in PS_In i ) : SV_TARGET 
{ 
    float value = ShadowDepth(i.tex0);
    return float4(value, 0, 0, 0);
} 

float4 PS_Shadow2 ( in PS_In i ) : SV_TARGET 
{ 
    float test  = ShadowComp(i.tex0);
    return float4(0, test, 0, 0);
} 
 ```

It seems like PS_Shadow0 could never be compiled to SPIR-V, but PS_Shadow1 or PS_Shadow2 should compile without error.

**Comment by LoopDawg** [comment]
I consulted with @johnkslang about this, who opined that the best available way to handle this is to generate the initial module by splitting the texture variable into two texture variables, one shadow and one not, and letting the optimizer eliminate the dead one.  (So, one must be dead).

I can pursue that and come up with a candidate PR.  I'm not equipped to test it under your workload, but I'll report back when there's something you could try.

**Comment by daveh-lunarg** [comment]
Cool.  I'm not entirely sure we don't have any of the PS_Shadow0 cases, but it'll at least be much easier to weed those out once the others are eliminated.  Thanks for digging in!

**Comment by LoopDawg** [comment]
#1089 has a candidate fix.  If a single texture is only used with shadow samplers, or only non-shadow samplers, it behaves as before.  If it is used with both in one shader, instead of generating an error, it will add two texture objects to the linkage, and use each in the appropriate places, and issue this warning:

    WARNING: AST will form illegal SPIR-V; need to transform to legalize

So that's an invalid module, and will depend on a post-compilation optimization transform to legalize by DCEing some of the uses and one of the symbol table entries.  Adding @greg-lunarg about that.  It also means one of the sides must be dead.  I don't know of any way to produce a valid SPIR-V module if that's not the case.

@daveh-lunarg: I'm not set up to run your workload, but if you try this plus the legalization transforms, and it works, I'll clean it up and remove the WIP.  I'm still working on some internal code details, but they shouldn't impact the externally visible behavior of #1089, so that'll be a no-op from your POV.

**Comment by greg-lunarg** [comment]
I am presuming from this that there is some restriction in Vulkan or SPIR-V that says that a single texture/image cannot be sampled with both depth-comparison and non-depth-comparison sample operations. True? Is this a SPIR-V or Vulkan restriction? Is this true for compute shaders as well?
