### ISSUE TITLE
HLSL: struct member initialization?

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1093]
Seems like this has been asked before, but I wasn't able to find an issue with it - and also couldn't find an item that matched it on #362. Was wondering if a shader like this could be supported via SPIR-V:
````C++
cbuffer ubo {
  float x = 0.0;
};

float4 main(float4 pos : POSITION) : SV_POSITION {
  return pos + float4(x, 0, 0, 0);
}
````

**Comment by johnkslang** [comment]
I believe this is because it is a Vulkan, or meta, issue. See related issue https://github.com/KhronosGroup/glslang/issues/701.

This "initialization" does not actually mean the shader initializes the struct member. Rather, it is a request that the driver pre-initialize the memory for the shader. If you look at fxc output, the initializer is actually in a comment, not the code.

If we do something to support this in glslang, something else will have to consume it to finish the job. So, we need a complete proposal of what to do:

- does it come with new Vulkan functionality?
- new driver support?
- some boiler plate application code the app can call to initialize buffers with?
- etc.

**Comment by chaoticbob** [comment]
Thanks for clearing this up. Will keep tracking it on #701.
