### ISSUE TITLE
Print glslangValidator errors to stderr

### ISSUE THREAD

**Issue by cleak** [KhronosGroup/glslang#1134]
Error messages are printed to stdout right now. It would be useful to print such messages to stderr instead, making it easier to integrate glslangValidator into typical tool chains. This would help the work for #1059.

**Comment by johnkslang** [comment]
We need to distinguish between different kinds of "error" here.

When being used as a validator (not a code generator), the expected normal output is the set of portability/specification problems the content contains. So, while a failure to open a file might be a true tool error that should go to stderr, getting semantic warnings and errors should go to stdout. Such things are not problems, they are the requested output.

Otherwise, I suppose all things that look like an error message are truly errors that could go to stderr.  So, following through on this model, there are, e.g., semantic error messages that are either normal expected output or problems in generating code, depending on what mode the tool is in.

**Comment by johnkslang** [comment]
If there are some fatal tool-level errors, that actually prevent the tool from working correctly (like can't open a file), I agree those could migrate to stderr. It could break some existing uses, but more generally shuffling things around would certainly a lot of existing uses. We may just need to live with the history being a validator, or add new options to control this.

**Comment by cleak** [comment]
The main use case I found for this is with additional output options such as -i. Having a mix of error output and other requested output is difficult for any tools downstream to deal with - also difficult to give feedback to the user of such a toolchain. Having an option like --stderr would make this manageable, though it feels a bit odd.

**Comment by johnkslang** [comment]
af52799c2d6b00661df7264a9b3faaf630cd85c4 now redirects a whole set of tool-level errors to stderr instead of stdout.  Given that we have two issues about this, and both a bit vague about which messages should go where, I'll close this one with this commit, and then we can keep the other open. Or submit new, highly specific issues about exactly which messages you think are misdirected.
