### ISSUE TITLE
HLSL: mul(float3, float4x4) warning vs. error

### ISSUE THREAD

**Issue by dustin-lunarg** [KhronosGroup/glslang#1160]
The following shader compiles with a warning with fxc, but fails to compile with an error with glslangValidator:

```hlsl
cbuffer Matrix
{
    float4x4  m4;
    float3    v3;
}

float4 main() : SV_Target
{
    return mul(v3, m4);
}
```

The fxc output is:
```
mismatch.ps(9,12-22): warning X3206: 'mul': implicit truncation of vector type
```

The glslang output is:
```
ERROR: mismatch.ps:9: 'mul' : no matching overloaded function found
mismatch.ps(9): error at column 23, HLSL parsing failed.
ERROR: 2 compilation errors.  No code generated.
```

Would it be possible for glslangValidator to produce the same behavior as fxc in this case?

**Comment by LoopDawg** [comment]
Experimenting a little, it seems a bit curious.  Generally you cannot expand a vector into a larger vector.  E.g, this is a compilation error:

    float4 f4;
    float3 f3;
    f4 = f3;

You _can_ truncate a larger matrix into a smaller matrix though, so one might be tempted to think that the behavior here is to to truncate the float4x4 into a float3x3. That doesn't appear to be quite true though, since the result of the mul() above is a float4, not a float3.

My working assumption is that only one matrix dimension is truncated, so ``float3 * float4x4`` ==> ``float3 * float3x4``, and further, that this is mul() specific behavior.  I'd welcome corrections from HLSL gurus, though.

(Generally, HLSL seems curiously unconcerned with matching dimensions for v\*m, m\*v, and m\*m: it happily lets you multiply a ``float3x3 * float2x4``, for example).

**Comment by LoopDawg** [comment]
#1161 fixes the v\*m and m\*v cases, based on the above truncation policy.  I haven't added the m\*m truncations yet.  It might be a few days since I'm busy with some other things.  If your workload doesn't need m\*m implicit truncation, #1161 should unblock you in the meantime, even in the current partial form.
