### ISSUE TITLE
Preprocessor: Per-token extension queries dramatically slow down preprocessor

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1187]
Context: I'm trying to switch to glslang preprocessor from mojoshader preprocessor that we use in our build pipeline; performance is important since full preprocessed source is the compilation cache key, so we preprocess all our shaders to check if they need rebuilding. On a specific shader pack, mojoshader takes ~90ms including various overheads, glslang preprocessor takes ~280ms.

I found that a very significant portion of this time is spent in `TPpContext::tStringInput::scan` (and possibly other callsites) calling `extensionTurnedOn` (which does `std:;string` construction and `std::map` lookup).

Replacing `extensionTurnedOn` body with `return false` drops preprocessing time from 280ms to 160ms which makes me think that all supported extensions should be cached in primitive variables somewhere.

**Comment by johnkslang** [comment]
Good find, thanks. I guess this has been slowly creeping in over time, as more keywords became conditional. Agreed with caching the common queries here.

**Comment by jfmarquis** [comment]
This started being a bottleneck to compile our 400 000+ shaders, so I did something as simple as possible before actually finding out there was an issue on the subject first.
All I did was change the map to an unordered_map and make it contain const char* instead of string, with corresponding custom hash/equal functions.

**Comment by jfmarquis** [comment]
If std::string_view was available it would look much better but wouldn't allow me to compare pointers, considering most (if not all) the elements of the map and the things we compare with come from constants in Versions.h. Comparing pointers gave the biggest gain after moving to unordered_map.

**Comment by jfmarquis** [comment]
See [here](https://github.com/jfmarquis/glslang/tree/getExtensionBehavior-perf) if its worth pulling.

**Comment by johnkslang** [comment]
I did something similar, and got a good speed up. But, I went all the way, fixing the code to use the `const *char const` from the header. Unfortunately, in debug mode on Windows, sometimes this constant changed value, so that experiment failed.

However, the real problem is how often the lookup is called. The actual culprit is this the following, which does 3 lookups *per token*!  This should instead be rare:

```
int TPpContext::tStringInput::scan(TPpToken* ppToken)
{
...
    bool enableInt64 = pp->parseContext.version >= 450 && pp->parseContext.extensionTurnedOn(E_GL_ARB_gpu_shader_int64);
#ifdef AMD_EXTENSIONS
    bool enableInt16 = pp->parseContext.version >= 450 && pp->parseContext.extensionTurnedOn(E_GL_AMD_gpu_shader_int16);
#endif
    bool acceptHalf = pp->parseContext.intermediate.getSource() == EShSourceHlsl;
#ifdef AMD_EXTENSIONS
    if (pp->parseContext.extensionTurnedOn(E_GL_AMD_gpu_shader_half_float))
        acceptHalf = true;
#endif
```

Fixing this will make it go from 3 checks per token down to a rare check, when needed. I see similar performance changes with the other fix.

**Comment by johnkslang** [comment]
So, #1209 is as shot at correcting the problem in the previous note.

I also uploaded the scan-perf branch, which tries to use the addresses of the strings from Versions.h to map, instead of TString, but it does not work.  Debug on VS 2015 sometimes sees pointers change values, which seems bizarre for const char* const.

**Comment by johnkslang** [comment]
So, the more normal way of dealing with features has now replaced these queries that were always being done. (Normal way: after you see a feature, you see if it is supported. That gives much nice error messages too, like extension not enable instead of syntax error.)

For the googletest suite, the entire thing, holistically, runs 13% faster, so I image scanning is considerably faster now.

I'm still interested in doing an integer-based extension-state management scheme soon, but assume most the performance is now attained.

**Comment by zeux** [comment]
With latest glslang I get ~90ms with mojoshader vs ~175ms with glslang for preprocessing; the overhead mentioned in this issue is completely gone. I'll close this.
