### ISSUE TITLE
[SPIR-V] Duplicate definitions of struct types when reading structs from buffer blocks.

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#123]
Consider a shader.

```
#version 310 es
layout(local_size_x = 1) in;

struct Foo
{
    vec4 a;
    vec4 b;
    vec4 c;
    vec4 d;
};

layout(binding = 0, std430) buffer SSBO
{
    Foo foos[];
} foobar;

layout(binding = 1, std430) buffer SSBOOut
{
    vec4 outdata[];
};

vec4 bar(Foo foo)
{
    return (((foo.a + foo.b) + foo.c) + foo.d);
}

void main()
{
    outdata[gl_GlobalInvocationID.x] = bar(foobar.foos[gl_GlobalInvocationID.x]);
}
```

I only expect the Foo struct to be declared once, but glslang now generates multiple version of the same type.

```
          8(Foo):             TypeStruct 7(fvec4) 7(fvec4) 7(fvec4) 7(fvec4)
         44(Foo):             TypeStruct 7(fvec4) 7(fvec4) 7(fvec4) 7(fvec4)
         51(Foo):             TypeStruct 7(fvec4) 7(fvec4) 7(fvec4) 7(fvec4)
```

While this isn't a problem on its own, when passing arguments and dealing with the memory, glslang will type-pun the various variants of Foo which I doubt SPIR-V allows here.

```
               9:             TypePointer Function 8(Foo)
12(bar(struct-Foo-vf4-vf4-vf4-vf41;):    7(fvec4) Function None 10
         11(foo):      9(ptr) FunctionParameter


              52:             TypePointer Function 51(Foo)
       53(param):     52(ptr) Variable Function
              56:     44(Foo) Load 55
                              Store 53(param) 56
              57:    7(fvec4) FunctionCall 12(bar(struct-Foo-vf4-vf4-vf4-vf41;) 53(param)

```

**Comment by Themaister** [comment]
This seems to be a regression, I didn't have this problem before.

**Comment by xorgy** [comment]
@Themaister If it is a regression, you could try tracking it to a specific commit with `git bisect`.

**Comment by johnkslang** [comment]
It was a recent, intentional, change.

SPIR-V allows type punning for structures and arrays.  This is to support multiple physical layouts of the same logical structure.  A struct bar's type needs different decorations on its type members for each of these cases:

```
struct bar {
    float f;
    vec4 g;
    mat4 m;
};

layout(std140) ... { bar b1; };  // bar.g decorated at offset 16
layout(std430) ... { bar ... };  // bar.g decorated at offset 4
in bar ...;     // bar.g location opaque, no offset
flat in bar b2; // bar.g decorated as flat, no offset
uniform ... { layout(row_major) bar b3; };  // bar.m needs a RowMajor decoration
```

Also, it is unlikely, for example, that the same function code could be used in:

```
void f(const in bar b) { b.m[2]; }  // different code needed for flat vs. std140 vs. ...
void main() { f(b1); f(b2); f (f3); } // b1, b2, b3 different 'bar's
```

You would either make different copies of f to access the member the right way through a pointer, or copy an I/O form of the struct to an opaque-stack form to pass by copy, or some such variant.

The tricky part is how much to invest in not having any redundancy.  Currently, glslang is keeping them unique for {std140, std430} X {row_major, column_major} X { ... }, but not for all combinations of interpolation, or for things like std140 vs std430 where the result just happens to be the same anyway.

Arrays are distinguished by stride.  Matrices, vectors, and scalars are not allowed to type pun, as the containing struct holds the layout information on the member, so it is just structs and arrays that participate.

**Comment by johnkslang** [comment]
Didn't mean to close, just post.

**Comment by Themaister** [comment]
Ok, thanks for the clarification. Makes sense now.
