### ISSUE TITLE
Question: can glslang be used as a lexer, only?

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [KhronosGroup/glslang#1335]
Would it be possible to use glslang as a backend for a scintilla lexer/api (syntax highlighting / live syntax checking)?  If so, where would I have to start deriving own classes?

**Comment by johnkslang** [comment]
Yes, there is a clean break between lexing and parsing.  The lexing and pre-processing are combined together. As 

Basically, parsing (from bison) keeps calling `TScanContext::tokenize()` in a loop (in glslang/MachineIndependent/Scan.cpp) to get a stream of tokens for parsing. This function gives the returned stream GLSL token labels for consumption by GLSL grammar rules.

In turn,  `TScanContext::tokenize()`  gets a C++-preprocessor token from `TPpContext::tokenize()`, which does all the right things with `#ifdef`, etc., and GLSL-specific modifications to the preprocessor.  Below that is character processing, which understands shaders come in an array of C strings.

`TScanContext::tokenize()` basically translates from C++-preprocessor processed tokens (PpTokens.h) to GLSL bison grammar tokens (glslang_tab.cpp.h), under rules for a specific version of GLSL/ESSL.

So, it depends which stream you want. I assume from the question you want the stream ready for parsing, because that goes with syntax checking. The class to use for that is `TScanContext` in ScanContext.h. You'd want to notice a skip in lines that indicates `#if 0` etc. skipped code, and color that something neutral with no syntax checking.

**Comment by St0fF-NPL-ToM** [comment]
Need to dig further: To receive tokens, wouldn't I also need the symbol tables initialized?

From reading how `TShader::parse(...)` proceeds, these are built on demand using `SetupBuiltinSymbolTable(...)`.  Unfortunately this function is library-private.  Am I right that I'd need to publish this function within ShaderLang.h for my cause (and a few more if I'm right)?

**Comment by johnkslang** [comment]
I guess this depends on whether you want to know the built-in symbols. It should work as a lexer without knowing the built-ins. But, certainly, whatever functionality you want, you could export to make available.

**Comment by lch32111** [comment]
Hi. I'd like to use glslang as a lexer. So I tried to make a simple example for getting one token from `TScanContext`. But I fail to create `TParseContext`.

Here is the code
```
std::ifstream ifs(filePath);
if (ifs.is_open() == false)
{
	std::cout << "Failed to open a file " << filePath << '\n';
	assert(0);
}
std::string inputGLSL((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());

// ParseContext Params for Construction
glslang::TSymbolTable symbolTable;
int version = 100;
EProfile profile = ECoreProfile;
glslang::EShSource source = glslang::EShSourceGlsl;
EShLanguage language = EShLangVertex; // EShLangFragment
TInfoSink infoSink;
glslang::SpvVersion spvVersion;
spvVersion.openGl = 100;
bool forwardCompatible = true;
EShMessages messages = EShMsgDefault;
bool parsingBuiltIns = true;
glslang::TIntermediate intermediate(language, version, profile);
intermediate.setSource(source);
intermediate.setEntryPointName("main");

// Create Parse Context
glslang::TParseContextBase* parseContext = new glslang::TParseContext
(
	symbolTable,
	intermediate,
	parsingBuiltIns,
	version,
	profile,
	spvVersion,
	language,
	infoSink,
	forwardCompatible,
	messages
);

glslang::TShader::ForbidIncluder includer;
glslang::TPpContext ppContext(*parseContext, "", includer);

// Link it to Scan Context
glslang::TScanContext scanContext(*parseContext);

parseContext->setScanContext(&scanContext);
parseContext->setPpContext(&ppContext);

symbolTable.push();

const char* builtInShaders[2];
size_t builtInLengths[2];
builtInShaders[0] = inputGLSL.c_str();
builtInLengths[0] = inputGLSL.size();
glslang::TInputScanner input(1, builtInShaders, builtInLengths);
		
YYSTYPE yType;
glslang::TParserToken parserToken(yType);
int token = scanContext.tokenize(&ppContext, parserToken);
```

And for putting `TParserToken` into the tokenize function parameter, which is private in Scan.cpp, I just copy and paste the class in my code :
```
namespace glslang
{
	class TParserToken {
	public:
		explicit TParserToken(YYSTYPE& b) : sType(b) { }

		YYSTYPE& sType;
	protected:
		TParserToken(TParserToken&);
		TParserToken& operator=(TParserToken&);
	};
}
```

But When I create TParseContext, I got this error from PoolAllocator
![image](https://user-images.githubusercontent.com/19434311/78653975-d80d5480-78fe-11ea-9c13-877598a03cd5.png)

Can you let me know what's the problem?

Thanks.
