### ISSUE TITLE
Redeclaring a struct with the same name inside a function fails glslang-validator

### ISSUE THREAD

**Issue by lucferron** [KhronosGroup/glslang#1358]
This simple shader declares a struct in the global scope, and then redeclares a struct with the same name in the main() function. The glslang-validator fails with this error message:

```
glslangValidator.exe -H shader.frag
ERROR: shader.frag:8: '' :  syntax error, unexpected TYPE_NAME, expecting IDENTIFIER or LEFT_BRACE
ERROR: 1 compilation errors.  No code generated.
```
Shader source: 
```
#version 450 core
layout(location = 0) out vec4 webgl_FragColor;
struct _uT {
    float _uf;
};
void main(){
    _uT _ua = _uT(0.0);
    struct _uT {
        float _uq;
    };
    _uT _ub = _uT(0.0);
    (webgl_FragColor = vec4(1.0, 0.0, 0.0, 1.0));
    (webgl_FragColor.w += _ua._uf);
    (webgl_FragColor.w += _ub._uq);
}
```
The GLSL spec mentions that this is a legal use case: 

_[...] If a nested scope redeclares a name used in an outer scope, it hides all existing uses of
that name. [...]_

**Comment by johnkslang** [comment]
Agreed. For the `_uT` in the nested `struct _uT`, the grammar is looking for an identifier to turn into a type, but not an existing type to hide with a type. This has been the grammar since inception, but there is some wiggle room in terms of what the lexical phase qualifies as a `TYPE_NAME` versus an `IDENTIFIER`.

Seems like it should get fixed, but it may also be new behavior.  Will check with Khronos.

**Comment by null77** [comment]
Any updates from Khronos yet John?

**Comment by johnkslang** [comment]
I found it is possible to address this during lexical analysis, the same way declaring variables works:

```
struct S { int a; };
void main() {
  float S;
}
```

The above is already handled by conditional lexical processing, and "struct S" issue can be handled the same way.

I will push something for this soon.

**Comment by null77** [comment]
Thanks!
