### ISSUE TITLE
Shared library use not first-class functionality, not tested

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/glslang#1484]
Compilation fails in commit e7df8e0b76af2fb9f58124be6b95688e5dbcdb7a; it used to previously work in a51525059f3f264c2337ae72997ca4e7ad7e17d0 (where essentially no libHLSL.so was generated).
Please specify the dependencies of HLSL properly.
```
/usr/bin/cmake . '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined' -DBUILD_SHARED_LIBS:BOOL=ON

-- The C compiler identification is GNU 8.1.1
-- The CXX compiler identification is GNU 8.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Configuring done
-- Generating done

$ make VERBOSE=1
[...]
/usr/bin/c++ -fPIC  -Wl,--no-undefined -shared -Wl,-soname,libHLSL.so -o libHLSL.so CMakeFiles/HLSL.dir/hlslAttributes.cpp.o CMakeFiles/HLSL.dir/hlslParseHelper.cpp.o CMakeFiles/HLSL.dir/hlslScanContext.cpp.o CMakeFiles/HLSL.dir/hlslOpMap.cpp.o CMakeFiles/HLSL.dir/hlslTokenStream.cpp.o CMakeFiles/HLSL.dir/hlslGrammar.cpp.o CMakeFiles/HLSL.dir/hlslParseables.cpp.o 
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/HLSL.dir/hlslParseHelper.cpp.o: in function `glslang::HlslParseContext::initializeExtensionBehavior()':
hlslParseHelper.cpp:(.text+0x59a): undefined reference to `glslang::TParseVersions::initializeExtensionBehavior()'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/HLSL.dir/hlslParseHelper.cpp.o: in function `glslang::HlslParseContext::parseShaderStrings(glslang::TPpContext&, glslang::TInputScanner&, bool)':
[...]
```

**Comment by v-fox** [comment]
Duh, tried to build and package fresh glslang for shaderc that is needed for Vulkan support in [mpv](https://github.com/mpv-player/mpv/) and it failed miserably with similar error:
```undefined reference to `glslang::TPoolAllocator::allocate(unsigned long)'```
Which is a sign of improperly written build rules. Probably has something to do with #1421 and the fact that "shared libraries are hard" for Windows "developers", so they break them even for platforms that don't suck. What a great display for the reference tool of a standard :/ The first time I was writting spec-file for auto-building/packaging it I had to make a script to move mishandled files into right directories after its "installation"… Someone should study it as a standard in failure of code maintenance.

**Comment by johnkslang** [comment]
As stated in #1421, maintenance of dynamic library builds is currently a non goal: It has no testing and most input had been to use glslang only with static linking. Negative judgments of a tool against goals it does not have does not help.

That being said, if there are users that want to contribute fixes for this space, or otherwise enable its support, I am happy to help fix glslang per those contributions.  Or, if it is truly a general need, figure out how to more officially add and test this need.

File locations, and many other legacy constructs adopted into glslang from its history, are likely relied on by users and so we need to cautious about changing things around (much as I'd like to). So, contributions that work without breaking things will be easier to get in.

**Comment by v-fox** [comment]
> As stated in #1421, maintenance of dynamic library builds is currently a non goal: It has no testing and most input had been to use glslang only with static linking. Negative judgments of a tool against goals it does not have does not help.
> 
> That being said, if there are users that want to contribute fixes for this space, or otherwise enable its support, I am happy to help fix glslang per those contributions. Or, if it is truly a general need, figure out how to more officially add and test this need.

How more general than "everywhere other than Windows where everything is held together by snots and crutches" could there be ? This is ridiculous how obsolete and broken coding practice is exalted to coding standard within a library that is an essential piece for emerging supposed global and universal graphics/high-parallelism standard-set (Vulkan/OpenCL/SPIR-V/etc.). Is there even a point in trying to fix something where breakage itself and broken-by-design approach are the norms ?

Although, the worst happen when MS-way of backwardness & non-maintenance and [Google-way](https://github.com/google/shaderc) of uninspired reinvention & over-complication [cross](https://developer.android.com/studio/releases/platform-tools)…

> File locations, and many other legacy constructs adopted into glslang from its history, are likely relied on by users and so we need to cautious about changing things around (much as I'd like to). So, contributions that work without breaking things will be easier to get in.

That's quite ironic, considering that build is long-time broken past https://github.com/KhronosGroup/glslang/commit/a51525059f3f264c2337ae72997ca4e7ad7e17d0, as original poster noted. Thanks to him I at least was able to build it and make mpv fully work. But newest shaderc would require newer glslang, so when mpv updates too - it's all over again…

Sorry for throwing shade unto your work that is important to pretty much everyone, at least indirectly. But those lax Windows-developer habits don't do anyone any good either. You're supposed to dominate over DX/HLSL and OpenGL/GLSL, not continue their mess. And now with "protected memory" hardware DRM/backdoor being built in Vulkan 1.1 users are being put between "rock and a hard place" yet again…

**Comment by johnkslang** [comment]
Let's get down to specifics, and stay on topic with this issue.

[The referenced commits (e7df8e0 and a515250) don't seem to have much to do with the reported behavior change, and some of the other criticisms seem triggered by guesses.]

The error `glslang::TParseVersions::initializeExtensionBehavior()` seems more to do with the addition of a virtual method override, which passed all the Linux, Mac, and Windows build bots.  On the other hand, commit e7df8e0 added use of the validator and seems completely unrelated.

With the issue being about something that is not tested by the normal configuration, it will help to:

1. identify when things really broke
2. identify what settings you are using that detect the break, despite the normal settings being happy

**Comment by jengelh** [comment]
Oh - I did not intend to mean e7df8e0 was the culprit; I merely tested these two commits, so the a51..e7d range is still subject to a bisection.

**Comment by johnkslang** [comment]
This is pending any contribution or constructive suggestion of how to advance to better support of shared linkage objects.

**Comment by v-fox** [comment]
> With the issue being about something that is not tested by the normal configuration, it will help to:
> 
>     1. identify when things really broke
> 
>     2. identify what settings you are using that detect the break, despite the normal settings being happy

The "settings we are using that detect the break, despite the normal settings being happy" is what all distributions consider proper practice, such as these [automated openSUSE builds](https://build.opensuse.org/package/show/X11:Wayland/glslang) (see build logs on the right). Notice how I'm the only person on OBS who even bothered trying building [vulkan](https://build.opensuse.org/package/show/home:X0F:HSF/vulkan), spirv-{[headers](https://build.opensuse.org/package/show/home:X0F:HSF/spirv-headers),[tools](https://build.opensuse.org/package/show/home:X0F:HSF/spirv-tools)}, [glslang](https://build.opensuse.org/package/show/home:X0F:HSF/glslang), [shaderc](https://build.opensuse.org/package/show/home:X0F:HSF/shaderc) past the breakage spiral. That is because you:
* don't version your API and put proper SO-versions in libs;
* don't define API dependencies, let alone build ones;
* put untested half-backed crap into master branches that doesn't belong there;
* have no concept of release cycle and feature-targeting from roadmap goals (you are NOT supposed to merge commits of entire features BEFORE testing them out in THEIR ENTIRETY in a development branch that is synced with master, especially if you haven't even defined their dependencies  !);
* probably, don't even have roadmap or any idea what exactly are you trying to achieve;
* have no concept of coding style, any idea of good & bad coding & maintenance practices.

> This is pending any contribution or constructive suggestion of how to advance to better support of shared linkage objects.

Because of that and your insistence on staying in your "safe-space" echo-chamber that as much of "constructive suggestions" that you're going to get. No one wants to deal with that and with you. Bisecting your code is even bigger fool's errand than trying to compile supposed "release" shapshots with your abnormal "normal configuration".

PS: same thing happened in distributions with support for horrible mess of android-tools, by the way. Although, with Mesa being dependant on vulkan, maintainers will persevere somehow this time.

**Comment by johnkslang** [comment]
I see several straw man fallacies, some religion, and can guess how you might jump to some of the non-religious conclusions, and yes there is a partially complete process of adapting a Windows' static-linking design to a Linux SO design (contributed by others), while not breaking existing use (which currently works on Max/Linux/Windows).

Rather than argue religiously in the abstract, it will be best to focus on specific issues and constructive action.

Is there a specific action to improve the semantic versioning being used?
Can you contribute the dependencies you want to see?
Is something currently in master that should not be?

(Note some large Khronos-provided features were developed and tested in a fork before appearing here, so appearances are different than reality.)

**Comment by jengelh** [comment]
>Is there a specific action to improve the semantic versioning being used?

That semantic version should be added to the filename; instead of producing (just) libHLSL.so, it should be called libHLSL.so.7. AIUI cmake has something like that in the form of `set_target_properties(HLSL PROPERTIES VERSION 7.9.2888 SOVERSION 7)`.

**Comment by akien-mga** [comment]
I can understand the frustration of package maintainers trying to build glslang as a shared library, as that's what I'm doing now and I spent a couple hours working on fixes in that direction already.

Yet I don't think language as seen in https://github.com/KhronosGroup/glslang/issues/1484#issuecomment-437538300 is constructive, and throwing a bunch of complaints on a generic issue isn't either.

So back to issue at end (the OP: https://github.com/KhronosGroup/glslang/issues/1484#issue-354011848):

This happens because the `glslang` and `HLSL` both have a weak dependency on each other (cyclic dependency). `HLSL` doesn't specify it, which causes this link error when preventing [underlinking issues](https://wiki.mageia.org/en/Underlinking_issues_in_packaging) using the link flags `-Wl,--as-needed -Wl,--no-undefined`.

This patch would solve the underlinking issue (i.e. make `HLSL`'s dependency on `glslang` explicit):
```diff
diff --git a/hlsl/CMakeLists.txt b/hlsl/CMakeLists.txt
index f918d7a1..5696afd8 100644
--- a/hlsl/CMakeLists.txt
+++ b/hlsl/CMakeLists.txt
@@ -27,6 +27,8 @@ if(WIN32 AND BUILD_SHARED_LIBS)
     set_target_properties(HLSL PROPERTIES PREFIX "")
 endif()
 
+target_link_libraries(HLSL glslang)
+
 if(WIN32)
     source_group("Source" FILES ${SOURCES} ${HEADERS})
 endif(WIN32)
```

But then another issue comes up:
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "glslang" of type SHARED_LIBRARY
    depends on "HLSL" (weak)
  "HLSL" of type SHARED_LIBRARY
    depends on "glslang" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

Cyclic dependencies are not allowed in shared libraries, so there's no easy fix. The proper fix would be to remove the cyclic dependency, probably by removing `glslang`'s dependency on `HLSL` somehow.

In the meantime, the workaround for distro packager is to forego their distro's library policy and let the underlinking go through (so remove `-Wl,--no-undefined` from the link flags).

**Comment by jengelh** [comment]
>Cyclic dependencies are not allowed in shared libraries, so there's no easy fix.

Generally speaking, there are two trivial (or let's say "default") ways of addressing such.
1. Merge the two libraries into one build target, or
2. Finding the intersection (usually the cycle in the graph) and factoring that out into a third library, then required by the other two.

While --no-undefined is a possible workaround, that would only work for ELF and not for PE platforms as I understand it.

**Comment by ben-clayton** [comment]
#2271 fixes building of shared libraries.

#2277 (draft) starts to tackle versioning, including `SONAME`.
