### ISSUE TITLE
Delete #ifdefs for NV and AMD extensions

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#1503]
Having piles of `#ifdef`s in the code for AMD and NV extensions is probably more trouble than it's worth.  It's lots of compile testing and mental "is this actually compiling" overhead for probably very little actual benefit.

**Comment by johnkslang** [comment]
Original intended benefits were:

1. vendor assuming quality of what was inside of #ifdef
1. footprint, for someone wanting the smallest embedded glslang
1. vendor-neutral glslang was buildable

Reason 1 is no longer applicable, due to interactions, and needed high quality independent of the vendor.

Reasons 2 and 3 may warrant community input, but also agreed the relative size of this is somewhat small (though, the symbol table does get quite a bit bigger).

Agreed they should not be part of interfaces to libraries, per #1502.

**Comment by johnkslang** [comment]
In experimenting just now, I was noticing how much data and if-testing is inside these #ifdef, so am sympathetic to consumers wanting a small footprint.

**Comment by jeffbolznv** [comment]
Did you compare the binary size with and without them enabled? Can you share the data?

**Comment by dgkoch** [comment]
ping @johnkslang to provide some data to back up his earlier comments on size. 

(This came up again in the review of #1787)

**Comment by johnkslang** [comment]
A while back, I saw on the order of 10% for static executable size.  I will be trying again soon.  These are growing faster than core.

**Comment by dgkoch** [comment]
I don't doubt that there is a lot of extension functionality, but what should be the definition of "core" for glslang? It supports multiple versions of GLSL, ESSL, and HLSL (and Vulkan semantics) on the front-end and produces multiple versions of SPV on the backend, so I don't know what you would propose be in the "minimal" version of glslang. Presumably different customers would have different needs and trying to meet all of these through ifdefs seems like it will result in a complex mess of unreadable and unmaintainable code.

**Comment by johnkslang** [comment]
So, I dug deeper in this and have an idea to pursue that will address both:

- this issue, reducing/removing #ifdef
- the quality/maintainability issue in Initialize.cpp, whose old design did not scale to the current usage

What I'd like to do is:
- reduce down to one macro name that identifies (still a bit loosely defined) the subset needed for web use; you're either in that small subset, or not
- table the declarations in Initialize.cpp; this helps with both size and maintainability

I spent a day investigating the last thing.  It'll be a bit of work to get it correct.  See following statistics.

Glslang generates over 8000 textual declarations and prototypes; combined surgically as they vary based on the 17 different versions of ESSL/GLSL, 14 stages, 4 profiles, Vulkan/OpenGL, and tagged with which of 120 extensions might enable them in an earlier versions.

The resulting text for these declarations, for "#version 460 core" only, takes over 400KB.  ESSL 3.1 is 1/10 this size, a bit over 40KB.

**Comment by johnkslang** [comment]
In side experiments, a `ESSL 3.0 -> SPIR-V` subset of glslang can compile and compress to less than 150KB, making it worth while for some uses.

This involved several techniques, including:

- moving to a higher-quality tabled version of built-in function declarations
- consolidating all extension #ifdef to use a single "make it small" macro
- ... a few others

The relevant point to this specific issue is to simultaneously reduce some technical debt and the binary footprint.

I believe the design I'm looking at will require less care in adding #ifdef for new extensions, as new code would often be adjacent to (or nested in) existing code that was already properly protected.  In addition, with only two modes (big and small) the bots can ensure both modes compile and pass tests.

Regarding the title of this issue, the existing `#ifdef` have some value in identifying code, but they will be transformed (renamed and generalized) rather than just deleted.

Comments welcome.  My intention is to slowly roll this out, one clear step at a time.

**Comment by johnkslang** [comment]
The vendor-specific `*_EXTENSIONS` switches are now gone.

**Comment by johnkslang** [comment]
In case this caused any problems, there is a stable release tagged just before it went in: https://github.com/KhronosGroup/glslang/releases/tag/7.12.3352.
