### ISSUE TITLE
Regression in the preprocessor

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glslang#1563]
Hi,

For quite some time glslang was able to correctly preprocess the following code:

```
#version 450 core

#define xyz() xyz

#define LIGHTING_COMMON_BRDF() \
	vec3 a = vec3(0); \
	vec3 b = a.xyz;

void main()
{
	LIGHTING_COMMON_BRDF();
}
```

The expansion produced the following:
```
#version 450 core
void main()
{
                      vec3 a = vec3(0);vec3 b = a . xyz;;
}
```

After April something broke the preprocessor and the new expansion is:
```
void main()
{
                      vec3 a = vec3(0);vec3 b = a . ;;
}
```

The old behavior aligns to what GCC's preprocessor produces (cpp). That leads me to believe that there is a regression somewhere. Please correct me if I'm wrong.

**Comment by johnkslang** [comment]
Yes, there was a change, but this was not a fully supported, completed, or tested feature. Seems to have reasonable need, and maybe needs to be promoted to a first-class feature. I will keep improving it based on demand.

**Comment by johnkslang** [comment]
I experimented a bit, and see this is not a -E issue, but rather a problem of calling a macro declared with `()` and then called without the `()`, which is sensitive to what the following characters are, how the macro gets expanded.

**Comment by godlikepanos** [comment]
Thank you for looking into this. Yes it's a _weird_ usecase at first but it may occur when creating weird macros in order to share code between C++ and GLSL.

I did some additional digging and it seems that the preprocessors of GCC, clang, MSVC and AMD's GLSL compiler have the behaviour of the old glslang. That doesn't mean that the newer glslang is wrong.

**Comment by johnkslang** [comment]
> in order to share code between C++ and GLSL

These both follow the same standard (C++) regarding this part of the preprocessor. The standard identifies *object-like* macros and *function-like* macros, and treats them separately, and does not say a function-like macro with no arguments is the same as an object-like macro.

(I actually don't know if you are expecting the macro to be invoked or not, because your example substitutes the same thing as the macro name. I couldn't reproduce calling a function-like macro without the `()` on MSVC 2013 or 2015. If your goal is to portability, you would certainly not want to declare a function-like macro and expect it to work with object-like calling syntax.)

What I did find is that glslang conditionally drops the token that the fails macro invocation (due to object vs. function-like semantics), rather than keeping the original token. (Maybe that's what you found too.) I will look at fixing that.

**Comment by godlikepanos** [comment]
Thanks for lightning fast fix!

I wasn't expecting the macro to be invoked. Because it was missing the () I was expecting PP to treat it just like any other token that it didn't recognize. I should have used a more generic example, sorry.

Once again thanks for the fix!
