### ISSUE TITLE
Use of noise1 causes glslang to throw an internal error

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#157]
Compiling the following program causes glslang to throw an internal error:

#version 440 core
void main() {
  float f = noise1(1.0);
}

I get this error:
glslangValidator: glslang/glslang/MachineIndependent/ParseHelper.cpp:1539: void glslang::TParseContext::nonOpBuiltInCheck(const glslang::TSourceLoc&, const glslang::TFunction&, glslang::TIntermAggregate&): Assertion `PureOperatorBuiltins == false' failed.

Low priority.  I don't really care about this case.  I was just fishing for a way to test deprecated language features without using a very old version of GLSL

**Comment by johnkslang** [comment]
Since I'm in the middle of several changes here anyway...

If you are looking for testing of use of deprecated features, this is generally missing, see issue #158.

This works correctly in non-debug mode, but noise*() wasn't mapped to an operator for PureOperatorsBuiltInMode (being unused), though it should have been.  This is fixed in ba5685a3322427d0f22f0757d02ea4a8d128948c.
