### ISSUE TITLE
Generating SPIRV using AtomicCounterMemory without adding capability AtomicStorage

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/glslang#1618]
https://github.com/KhronosGroup/SPIRV-Tools/pull/2175 added in stricter validation of memory semantics, which has uncovered the following failing test cases:

Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_subgroupBasic_comp
Glsl/CompileVulkanToSpirvTest.FromFile/spv_barrier_vert
ToSpirv/HlslCompileTest.FromFile/hlsl_intrinsics_barriers_comp

**Comment by alegal-arm** [comment]
This affects a lots CTS tests as well.
cc: @jeffbolznv

**Comment by jeffbolznv** [comment]
This is a little tricky. In internal merge request 2490 we had agreed that AtomicCounterMemory is ignored (see also discussion in 2493). But SPIR-V says the capability is required, yet Vulkan doesn't whitelist it. We made the decision for 2490 in part because there was a bunch of existing shaders that will use it and would become technically invalid. I'll open an internal issue to track this.

**Comment by jeffbolznv** [comment]
@zoddicus could you disable this check in SPIRV-Tools until we resolve the issue?

**Comment by jeffbolznv** [comment]
In today's Vulkan WG call, we agreed that spirv-tools should ignore this bit for Vulkan and not require the Capability be set. @zoddicus can you make that change to spirv-tools?

**Comment by johnkslang** [comment]
My understanding is SPIRV-Tools is indeed making (or already made) this change.

**Comment by jeffbolznv** [comment]
Well, https://github.com/KhronosGroup/SPIRV-Tools/pull/2193/ just commented out the code with a TODO comment. I assume they don't want to leave it like that.

**Comment by zoddicus** [comment]
I am going send a PR that removes the commented out code from spirv-tools, and leave a comment there that points to this bug, so in the future when I am trying to remember why I removed the check I will come back here.
