### ISSUE TITLE
Specialization constants used as array dimension for shader input array of array

### ISSUE THREAD

**Issue by samuelig** [KhronosGroup/glslang#1810]
I have a Vulkan Geometry shader like this:

```glsl
#version 450
layout (triangles) in;
layout (triangle_strip, max_vertices = 3) out;
layout(constant_id = 0) const int arraySize = 1;
layout(location = 0) in ivec4 inputData[3][arraySize];
in gl_PerVertex {
   vec4 gl_Position;
} gl_in[];
layout(location = 0) out vec4 outColor;
void main()
{
....
```
glslang returns an error saying: 

`ERROR: 0:5: &apos;[]&apos; : only outermost dimension of an array of arrays can be a specialization constant`

Checking the Vulkan spec, I found only this:

> OpTypeRuntimeArray must only be used for:
>    the last member of an OpTypeStruct that is in the StorageBuffer storage class decorated as Block, or that is in the PhysicalStorageBufferEXT storage class decorated as Block, or that is in the Uniform storage class decorated as BufferBlock.
>     If the RuntimeDescriptorArrayEXT capability is supported, an array of variables with storage class Uniform, StorageBuffer, or UniformConstant, or for the outermost dimension of an array of arrays of such variables.

But as `inputData` is a variable with storage class Input then it should work... or am I missing something?

**Comment by samuelig** [comment]
This also happens to other shader inputs for other stages (TCS, TES) and outputs (TCS output).

**Comment by johnkslang** [comment]
So `layout(location = 0) in ivec4 inputData[3][arraySize];` does not have anything to do with run-time sized arrays.  I see the intent is to specialize it, which theoretically could work, and would result in a run-time fixed-sized array, fixed by whatever it got specialized to.

The current intent though is for compilers to know things like stride at compile time, so Khronos does intend to not allow specialization of inner array dimensions.  If this is a real desire for real workloads, can you submit an issue to have Vulkan support it?

We currently have an internal Khronos bug to finish any missing language for stating that inner dimensions cannot be specialized.

**Comment by samuelig** [comment]
Thanks for your reply. I am going to create an internal Vulkan issue to discuss this.
