### ISSUE TITLE
Unsized array dimension corresponding to the view number causing error (mesh shader + multiview)

### ISSUE THREAD

**Issue by flisgd** [KhronosGroup/glslang#1818]
This line:

layout(location = 3) perviewNV out vec4 perVertexColor[][];

causes error:

'[]'
: only outermost dimension of an array of arrays can be implicitly sized 
ERROR: 1 compilation errors.  No code generated.

According to extension, this is legal:

From https://github.com/KhronosGroup/GLSL/blob/master/extensions/nv/GLSL_NV_mesh_shader.txt

> Mesh shader outputs qualified with "perviewNV" are considered to be per-view and arrayed with a second additional level of arrayness.  Each non-block output variable must to be declared as an array with at least two dimensions. For output block members, one level of arrayness applies to the block declaration and a second applies to the block member declaration.  For example,
> 
>       perviewNV out float perViewVertexColor[][];
>       out PerVertexBlock {
>         perviewNV vec2 perViewTextureCoord[];
>       } v[];
> 
> For non-block output variables, each element in the outer (leftmost) dimension of such an array corresponds to one vertex or primitive of the output mesh, as described immediately above.  Each element in the second (next-to-leftmost) dimension corresponds to a single view of the output primitive or vertex.  **The array dimension corresponding to the view number can optionally have a size declared.**  The array size will be set to (or if provided must be consistent with) the maximum number of views supported by the implementation given by the constant gl_MaxMeshViewCountNV.

**Comment by johnkslang** [comment]
I looked briefly; should let Nvidia (@jeffbolznv, @chaoc ?) decide what to do here.  My notes:

- it's a pretty direct path to seeing a variable declared with [] and checking legality of that:  declareVariable() -> arraySizesCheck() -> isInnerUnsized() to look to see if anything but the outer-most dimension is unsized
- there is nothing in that path accounting for "arrayed I/O" and possible removal of that dimension of the array before doing a check, or possibly modifying isInnerUnsized() to take a number of "outer" dimensions to ignore before requiring sizedness.

This would be a more general thing if we always said you could strip off an implicitly sized arrayed-io outer dimension before applying the other rules about implicitly-sized arrays, but we don't seem to:

> For implicitly-sized or run-time-sized arrays, only the outer-most dimension can be lacking a size.

**Comment by nvpbrown** [comment]
I didn't have any involvement in the glslang implementation of this feature, so I can't assess implementation choices.  From a spec point of view, I think my preference would be to allow any "arrayed" dimension to be unspecified, since these dimensions are always implicitly sized to some property of the execution environment independent of the shader code.  I guess "arrayed" dimensions here would include:

- vertex number for tessellation control inputs and per-vertex outputs
- vertex number for tessellation evaluation per-vertex inputs
- vertex number for geometry outputs
- vertex or primitive number for mesh outputs
- view number for per-view mesh outputs

The block number for arrays of uniform or shader storage blocks has some similarity to an "arrayed" dimension -- identifying one resource in an array of block or "vertex" resources.  But this isn't the same -- the number of UBO/SSBO instances does not come from some property of the execution environment.  The spec already requires explicit sizes for these:

> As the array size indicates the number of buffer objects needed, uniform and
> shader storage block array declarations must specify an array size.

I guess per-view mesh shader outputs are the one and only example at present where two "arrayed" dimensions are possible.

I'm not sure I fully grok the motivation behind this language:

> For implicitly-sized or run-time-sized arrays, only the outer-most dimension can be lacking a size. A
> type that includes an unknown array size cannot be formed into an array until it gets an explicit
> size, except for shader storage blocks where the only unsized array member is the last member of
> the block.

I assume the "implicitly sized language" is related to use cases like:
```
float batman[];
batman[0] = 3.0;
batman[1] = 4.7;
```
which would size the array based on usage (to 2 in this example), and where something like:
```
batman[non_constant_expression] = 5.11;
```
would be illegal.  I've never liked this aspect of GLSL and would have preferred that it had not existed.

I suppose that if you extend this to multiple dimensions like this:
```
float robin[][3];
robin[0][5] = 2.6;
robin[3][non_constant_expression] = 14.9;
```
the compiler would treat the outer dimension of the array as though it were declared to 4?  It's not clear to me why it's any harder to implicitly size the second dimension than it is to implicitly size the first, but I guess I don't have any problem with the current spec language requiring the second dimension to be implicitly sized.

One other thing I thought of here -- for arrayed inputs in GS, and similar, I think we support both "arrays of blocks" and "two-dimensional array" syntaxes.  I assume that in code like:
```
in Block { float joker[]; } blocks[];
in float riddler[][];
```
the first example is legal and has the compiler implicitly size <joker>, while the roughly equivalent second example is not legal due to the lack of explictly sizing the second dimension (which would be "joker" if converted to the first example)?

**Comment by sparmarNV** [comment]
While implementing the meshlet support, I remember adhering to the OpenGL spec rule which says “For implicitly-sized or run-time-sized arrays, only the outer-most dimension can be lacking a size.”.
However I agree to Pat's point that mesh multi-view is a special case and both view dimension and vertex/prim dimension could be unsized and be sized according to the values specified by the shader.

**Comment by johnkslang** [comment]
Yes, implicitly sized refers to the size coming from constant index usage (and maybe something else that is "non-local" that sizes the array).

> It's not clear to me why it's any harder to implicitly size the second dimension than it is to implicitly size the first

Right, I think it is not, other than trying to not further aggrandize this feature, because:

>  I've never liked this aspect of GLSL and would have preferred that it had not existed.

It existed originally just for some flexibly sized inputs/outputs, and the grey area has always been how much to generalize it.

For the issue at hand, I think it's perfectly fine to allow the [][].  The spec. can make it clear and the implementation can test for it based on type.  I believe these actions are both Nvidia's to take.

**Comment by sparmarNV** [comment]
>For the issue at hand, I think it's perfectly fine to allow the [][]. The spec. can make it clear and the implementation can test for it based on type. I believe these actions are both Nvidia's to take.

@nvpbrown can you take care of the spec changes? I will meanwhile work on the glslang changes to allow unsized view and vertex/prim dims for non-block per-view attributes.
