### ISSUE TITLE
glslangvalidator: Matrix function calls with constexpr args not considered const initializers

### ISSUE THREAD

**Issue by abelbriggs1** [KhronosGroup/glslang#1865]
```
#version 320 es

precision mediump float;

void main()
{
    const mat2 l = matrixCompMult(mat2(1.0), mat2(1.0));
    const float m = determinant(mat2(1.0));
    const mat2 n = transpose(mat2(1.0));
    const mat2 o = inverse(mat2(1.0));
}
```
Trying to validate this shader with any of these statements produces an error:
```
ERROR: 0:7: 'non-constant initializer' : not supported with this profile: es
ERROR: 0:7: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

According to the [GLES 3.2 spec, section 4.3.3 (Constant Expressions)](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf):

>For non-specialization constants only: A built-in function call whose arguments are all constant expressions, with  the  exception  of  the  texture  lookup  functions.  This  rule  excludes  functions with a void return or functions that have an out parameter. The built-in functions dFdx, dFdy,and fwidth  must  return  0  when  evaluated  inside  an  initializer  with  an  argument  that  is a constant expression.

It seems that even though `mat2(1.0)` is considered a constexpr (`const mat2 a = mat2(1.0)` will validate), calls to these functions with such constexpr arguments are seemingly not considered constexpr, even though they satisfy the above conditions for a built-in function to be considered constexpr (not returning void, not having an out param, not a texture lookup).

I'm interested in why this is the case - is it a bug in glslangvalidator?

Thanks.

**Comment by johnkslang** [comment]
This is intentional.  At least the desktop specification has been changed to not require these functions to be compile-time constants.  For maximum portability, it is best to not rely on these evaluating to compile-time constants, though they are allowed to.

I think it is really a specification issue that the OpenGL ES version of GLSL does not provide a white list like the desktop does, but that is an accident of history that is difficult to revise.
