### ISSUE TITLE
nonuniformEXT(<literal here>) segfaults

### ISSUE THREAD

**Issue by roenyroeny** [KhronosGroup/glslang#1900]
`#version 430
#extension GL_EXT_nonuniform_qualifier : require

layout(r32f) uniform imageBuffer meow[];
void main()
{
	meow[nonuniformEXT(0)];
}
`

This (compute) shader segfaults, changing it to this works:

`#version 430
#extension GL_EXT_nonuniform_qualifier : require

layout(r32f) uniform imageBuffer meow[];
void main()
{
	uint cat = 0;
	meow[nonuniformEXT(cat)];
}
`

**Comment by johnkslang** [comment]
I've looked and understand what is going on now:

- this is based on the `EOpConstructNonuniform` operator
- `constructorError()` does not create the correct result type (I think that should be fixed)
- `constructBuiltin()` does not use the type passed in (I think it should, it comes from the first bullet)
- instead, it reuses the type of the constructee, which somewhat undoes the point of making a non-uniform, because it inherits the constness from the child

Will get to fixing this soon.

**Comment by johnkslang** [comment]
This is getting fixed in #1910.

**Comment by roenyroeny** [comment]
Thanks John!
