### ISSUE TITLE
Chromium/ANGLE rollers broke because of semicolon warning

### ISSUE THREAD

**Issue by null77** [KhronosGroup/glslang#1931]
Examples:

https://chromium-review.googlesource.com/c/chromium/src/+/1860292
https://chromium-review.googlesource.com/c/angle/angle/+/1861874

Errors:

../../third_party/glslang/src/hlsl/hlslScanContext.cpp(86,2): error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
};
 ^

../../third_party/glslang/src/SPIRV/SpvTools.cpp(213,2): error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
}; // end namespace glslang
 ^

and a lot more files. Not sure if someone intentionally went and added extra semicolons at the end of every namespace. We need to either fix the semicolons or explicitly disable the warning in BUILD.gn. Mild preference to fix the semicolons as they aren't necessary.

**Comment by null77** [comment]
Ah, maybe the problem was this CL:

**Comment by johnkslang** [comment]
I question whether this whole activity is worthwhile, compared to other things to do; it seems a bit of a self-fulfilling problem/solution (it's a real problem only because we took a very minor thing and turned it into a real problem).

I thought the PR would just give warnings, not break things, but isn't the choice to treat warnings as errors outside this project, not within in?

I suggest the burden to keep such things working is on the shoulders of the people who choose to spend time on it.

**Comment by zoddicus** [comment]
I was trying to resolve an underlying Chromium roll issue, I will look into coming up with a better solution then this.
