### ISSUE TITLE
Moving headers to the glslang subdirectory breaks building shaderc and libplacebo

### ISSUE THREAD

**Issue by tgurr** [KhronosGroup/glslang#1959]
https://github.com/KhronosGroup/glslang/commit/7b0e236325fa9e8ebc7f446f83797a20a2263b70 found in the latest release breaks the build of at least shaderc-2019.0 and libplacebo-1.21.0.

**shaderc-2019.0**
```
[...]
[  7%] Building CXX object libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o
cd /var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/build/libshaderc_util && /usr/bin/x86_64-pc-linux-gnu-c++  -DNV_EXTENSIONS -I/var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/shaderc-2019.0/libshaderc_util/include  -march=native -O2 -pipe -O3 -DNDEBUG   -Wall -Werror -fvisibility=hidden -fPIC -std=c++11 -std=gnu++11 -o CMakeFiles/shaderc_util.dir/src/compiler.cc.o -c /var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/shaderc-2019.0/libshaderc_util/src/compiler.cc
make[2]: Leaving directory '/var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/build'
/var/tmp/paludis/build/sys-libs-shaderc-2019.0/work/shaderc-2019.0/libshaderc_util/src/compiler.cc:29:10: fatal error: SPIRV/GlslangToSpv.h: No such file or directory
   29 | #include "SPIRV/GlslangToSpv.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libshaderc_util/CMakeFiles/shaderc_util.dir/build.make:66: libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:288: libshaderc_util/CMakeFiles/shaderc_util.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
[...]
```

**libplacebo-1.21.0**
```
[...]
[26/50] x86_64-pc-linux-gnu-c++ -Isrc/25a6634@@placebo@sha -Isrc -I../libplacebo-1.21.0/src -I../libplacebo-1.21.0/src/./include -I../libplacebo-1.21.0/subprojects/xtalloc/include -I../libplacebo-1.21.0/subprojects/bstr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -Wall -Wundef -Wshadow -Wparentheses -Wpointer-arith -std=c++11 -fvisibility=hidden -march=native -O2 -march=native -O2 -fPIC -pthread -MD -MQ 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -MF 'src/25a6634@@placebo@sha/glsl_glslang.cc.o.d' -o 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -c ../libplacebo-1.21.0/src/glsl/glslang.cc
FAILED: src/25a6634@@placebo@sha/glsl_glslang.cc.o 
x86_64-pc-linux-gnu-c++ -Isrc/25a6634@@placebo@sha -Isrc -I../libplacebo-1.21.0/src -I../libplacebo-1.21.0/src/./include -I../libplacebo-1.21.0/subprojects/xtalloc/include -I../libplacebo-1.21.0/subprojects/bstr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -Wall -Wundef -Wshadow -Wparentheses -Wpointer-arith -std=c++11 -fvisibility=hidden -march=native -O2 -march=native -O2 -fPIC -pthread -MD -MQ 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -MF 'src/25a6634@@placebo@sha/glsl_glslang.cc.o.d' -o 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -c ../libplacebo-1.21.0/src/glsl/glslang.cc
../libplacebo-1.21.0/src/glsl/glslang.cc:28:10: fatal error: SPIRV/GlslangToSpv.h: No such file or directory
   28 | #include <SPIRV/GlslangToSpv.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
[...]
```

**Comment by johnkslang** [comment]
@dj2 championed this; can you help here?

We should probably be more conservative in moving things around.

**Comment by dj2** [comment]
I'm guessing shaderc-2019.0 is old @dneto0 would probably know better. This change does work with Tip-of-Tree shaderc.

I don't know what libplacebo is so I it's possible it needs to be updated to take the header move into account.

I'm not sure how we could be more conservative here, as the SPIRV/ install folder directly conflicts with the spirv-tools spirv/ install folder. So, one of them had to move ....

**Comment by tgurr** [comment]
> I'm guessing shaderc-2019.0 is old @dneto0 would probably know better. This change does work with Tip-of-Tree shaderc.

I fail to see how this is fixed in shaderc, for me it still fails for current git master https://github.com/google/shaderc/commit/f16e793858c4b438382f8483cb95f65b6b9aa3bf when trying to build against external dependencies / glslang-7.13.3496 with the same error.

```
/home/user/Downloads/shaderc/shaderc/libshaderc_util/src/compiler.cc:22:10: fatal error: SPIRV/GlslangToSpv.h: No such file or directory
   22 | #include "SPIRV/GlslangToSpv.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

> I don't know what libplacebo is so I it's possible it needs to be updated to take the header move into account.

> > Reusable library for GPU-accelerated video/image rendering primitives, as well as a standalone vulkan-based image/video renderer. (Basically, mpv's vo_gpu-in-a-library)

I've reported the issue downstream at https://code.videolan.org/videolan/libplacebo/issues/71.

Generally it would be nice if such breaking changes could be communicated to the developers working on software using glslang before, so there are at least upstream patches/commits around that distributions can backport to work around the breakage, if not proper coordinated upstream releases.

**Comment by dj2** [comment]
Ah using the system headers I see. We don't usually build that way so didn't notice that shaderc would fail to build.

@johnkslang would you be OK with moving the SPIRV source directory into the glsang/ folder to make the install and non-install variants consistent? Otherwise, we can make shaderc use a higher level include folder, but that's not as nice (it would, essentially, have its third_party/ folder in the include path instead of the specific projects).

On coordination, we don't know the downstream users of glslang so can't communicate with them directly. We usually do this by opening a PR and waiting to see if there are any complaints before committing. Shaderc other projects insulate themselves by pinning the known working version of downstream dependencies so you build with the required version.

**Comment by johnkslang** [comment]
@dj2, I'd like to put back any removed files, until we know it is safe to remove them.

Generally, I don't want to remove interfaces or files from where existing users already expect them, and agree this should not be done without adequate communication first.

**Comment by dj2** [comment]
This will conflict with spirv-headers, potentially in weird ways as depending on the install order on a case-insensitive filesystem, you'll get either the spirv-headers headers or the glslang headers. I'm not sure how to handle that conflict if we put the SPIRV/ folder back where it was.

The files aren't removed, just the install location was changed.  The problem is, in the repo they exist at `SPIRV` but installed they exist at `glslang/SPIRV`.

**Comment by johnkslang** [comment]
>  I'm not sure how to handle that conflict if we put the SPIRV/ folder back where it was.

What was the bad thing that was happening before?  What users were breaking?

I understand it looks wrong, and should have been done a different way (still haven't looked an the history here), but that's a separate subject from how to migrate to something different without breaking consumers.

See also #1919 for some recent history.

**Comment by dj2** [comment]
I don't have a broken user. But, it's going to end up with spirv folders that are a) confusing and b) strange. Depending on if you have glslang you have certain headers in SPIRV/ but you also have them inside the unified folder. The SPIRV/ folder is GLSLang specific so should exist in side the glslang include folder. 

I don't know of any way to move headers that won't break downstream customers that depend on working at tip-of-tree ..... but the fix should just be updating their include path from `SPIRV` to `glslang/SPIRV`.

The reason we don't see this in shaderc is because we don't use the install headers, we build with glslang source, so our `SPIRV/` path continued to work but will break if you try to combine shaderc with an installed version of glslang.

**Comment by dj2** [comment]
You can revert the offending CL if desired, it shouldn't break anything.

**Comment by haasn** [comment]
My 2 cents (as the author of one of the affected downstream libraries): This is an API break. You need to learn to start bumping the patch level in the same commit that implements the API break, so that users can continue building/bisecting against git master. (By guarding the `#include` behind an appropriate `#if`)

**Comment by dj2** [comment]
Yes, this change had unintended side effects. We have a plan for how to migrate to the new path which is in place now. We are installing to both locations so you can migrate as needed and we will remove the old path in a few months.

You can still git bisect with the changed path I'm not sure what the version has to do with doing a bisect? Is your suggestion for the `#if` that we have both paths in the code at the same time forever? That's not really a tenable solution as it will end up with a lot of cruft, or am I failing to understand?

Yes, if you pin dependencies you have to roll them forward for newer fixes. It also guards you against fluctuations in tip-of-tree and insulates your users from upstream changes.

Either way, we're going to be removing this path in the future. We're install both for the time being so you can migrate to the new path and we will remove the new one in May.

**Comment by haasn** [comment]
> You can still git bisect with the changed path I'm not sure what the version has to do with doing a bisect? Is your suggestion for the #if that we have both paths in the code at the same time forever?

My suggestion for the `#if` is that *downstream* users of your library have both paths in the code at the same time forever. Think:

```c
#if GLSLANG_VERSION > whatever
#include <glslang/GlslangToSpv.h>
#else
#include <SPIRV/GlslangToSpv.h>
#endif
```

Now I can build the same version of my library against newer and older glslang without requiring changes in my code.

(Side note: Instead of checking for the API version, we could also explicitly test for existence of `glslang/GlslangToSpv.h` / `SPIRV/GlslangToSpv.h` and guard based on that existence check, but I think having a bunch of cruft checks like that is needlessly bloated compared to just using a single number to inform users of API changes. Especially when you also need to test for e.g. changed function signatures or struct definitions, which [you've also happily broken in the past without any bump in the version number](https://github.com/KhronosGroup/glslang/issues/1538) - hence my frustration).

> You can still git bisect with the changed path I'm not sure what the version has to do with doing a bisect?

If the history contains a commit which changes the API, and I'm trying to bisect glslang while keeping the downstream library that uses it at the same version, I need to rebuild that *same* downstream library against different versions of the glslang API. This requires some sort of conditional include in the downstream library.
