### ISSUE TITLE
[SPIR-V] Incorrect encoding for string literals on big-endian machines

### ISSUE THREAD

**Issue by cwabbott0** [KhronosGroup/glslang#202]
The SPIR-V spec says, in the definition of "literal string," "the UTF-8 octets (8-bit bytes) are packed four per word, following the little-endian convention (i.e., the first octet is in the lowest-order 8 bits of the word)." But when emitting literal strings [here](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/spvIR.h#L104), we just reinterpret an integer as a character array, which won't work on big-endian systems, since we'll end up packing them according to the big-endian convention instead.

**Comment by johnkslang** [comment]
Agreed glslang is creating octets in address order instead of significant-byte order, and hence glslang only generates correct SPIR-V when executing on a little-endian system.

**Comment by tjaalton** [comment]
so this is why the tests fail on s390x/sparc/power/hppa?

**Comment by johnkslang** [comment]
If we have a real big-endian system to test glslang on, I can fix this.

**Comment by tjaalton** [comment]
should've failed on m68k too, but didn't:
https://buildd.debian.org/status/package.php?p=glslang

**Comment by mhillenbrand** [comment]
This issue has surfaced in QtShaderTools on s390x and ppc64, where the implementations in glslang and SPIRV-cross conflict: glslang encodes strings incorrectly while spirv-cross attempts to decode them correctly, resulting in reordered characters (https://bugreports.qt.io/browse/QTBUG-93101).

Both the SPIR-V generation and disassembly use incorrect encoding/decoding, so calling `gslangValidator -H` (generating binary SPIR-V and then disassembling) produces correct output, while the binary results are clearly wrong. Thus, it appears to me that none of the test failures are caused by this issue, since they are checking against the textual representation. Vice versa, fixing SPIR-V generation and not yet the disassembler introduces new test failures.

**Comment by mhillenbrand** [comment]
For reference, other issues about endianness: #2797 #2802
