### ISSUE TITLE
#line  file pathnames are being processed for escapes

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#2108]
The problem is caused by https://github.com/KhronosGroup/glslang/pull/2098

Here's a reproducer.  There are two files in directory c:\build\no:  a.frag and b.glsl
The gv-before.exe is glslangValidator at the commit before #2098 was merged.
The gv-jb.exe is glslangValidator at #2098 

```
C:\build>type no\a.frag
#version 450
#extension GL_GOOGLE_include_directive : enable

content a before

#include "b.glsl"

content a after

C:\build>type no\b.glsl
void main() {}

C:\build>gv-before.exe -Ic:\build\no c:\build\no\a.frag -E
#version 450
#extension GL_GOOGLE_include_directive : enable

content a before

#line 1 "c:/build/no/b.glsl"
 void main(){ }
#line 7 "c:\build\no\a.frag"

content a after


C:\build>gv-jb.exe -Ic:\build\no c:\build\no\a.frag -E
#version 450
#extension GL_GOOGLE_include_directive : enable

content a before

#line 1 "c:/build/no/b.glsl"
 void main(){ }
#line 7 "cuild
o.frag"

content a after

```

The processing of the path string in the last #line directive is corrupted.  The \b and \n have been interpreted as backspace and newline.

The original PR #2098 ensured the header name for #include is not corrupted by escape processing, but there are other cases that need to be handled too:  #line and probably #error.  I don't know if that's the full list.

This was caught by our tests in Shaderc https://github.com/google/shaderc/issues/996 and VKB: https://github.com/google/vkb/pull/82

cc: @jeffbolznv

**Comment by dneto0** [comment]
The risk comes with *Windows* path names that have backslashes all over the place.

cc: @greg-lunarg this should be a blocker for the debug-printf rollout.

**Comment by johnkslang** [comment]
Ah, okay. #line needs similar treatment as #include.

Side point: Windows paths do also operate with forward slashes.  I almost never use back slashes on Windows; not in code, not the command line, etc.

**Comment by johnkslang** [comment]
Reopening, as a better fix is likely needed.

Some notes:

- core GLSL doesn't even allow strings for `#line`, so that is up to other specifications
- the normative reference for C++ preprocessing says: 

> The process of dividing a source file’s characters into pre-processing tokens is context-dependent. [Example: see the handling of `<` within a `#include` preprocessing directive. ]

and also that `#line` -> *s-char-sequence* -> *s-char* -> *escape-sequence*.  I didn't immediately see it saying anything like "but don't actually substitute the escape sequences", so that's a bit odd. Similarly for `#error`.  `#include` is handled before this, so is indeed different regarding escape sequences.

- it would still be incorrect to slice this based solely on `GL_EXT_debug_printf` being enabled, as that would still impact subsequent `#include` and `#line`.

- because of the unusual history for how `#include` was added to glslang, the testing for it is still concentrated in shaderc, and I'd thought that was a conscious choice regarding that need for full test coverage

- I verified the escape sequences between the normative reference and what's in `GL_EXT_debug_printf` match, except that C++ allows any number if hex digits, and 1, 2, or 3 octal digits, which the glslang implementation does not follow.  C++ says:

> The escape \ooo consists of the backslash followed by one, two, or three octal digits that are taken to specify the value of the desired character. The escape \xhhh consists of the backslash followed by x followed by one or more hexadecimal digits that are taken to specify the value of the desired character. There is no limit to the number of digits in a hexadecimal sequence. A sequence of octal or hexadecimal digits is terminated by the first character that is not an octal digit or a hexadecimal digit, respectively. 

Question: Was it important to add escape sequences for debug printf?

Conclusions:

- doing mode setting around specific preprocessor statements might indeed be the proper way to do this, given the "context-dependent" statement above
- specifications need to say which strings get which behavior
- the new implementation of escape sequences does not follow the normative reference and the specification does not explain it as a deviation, so one of those two should be fixed (I don't see a good reason to not follow the normative reference)

**Comment by jeffbolznv** [comment]
I'll fix the deviation from the C/C++ specs for escape sequences. I'm not sure how that happened, I really thought I based the rules on some existing spec.

> Question: Was it important to add escape sequences for debug printf?

Yes, to represent things like `"`, `\n`, etc..

> specifications need to say which strings get which behavior

Agreed, it would be nice if GL_GOOGLE_include_directive and GL_GOOGLE_cpp_style_line_directive had published specifications...

**Comment by jeffbolznv** [comment]
> doing mode setting around specific preprocessor statements might indeed be the proper way to do this, given the "context-dependent" statement above

FWIW, I didn't change the CPPinclude logic in #2110. It still needs a special case to detect `<` vs `"` so I think it's simpler to leave it as-is.

**Comment by johnkslang** [comment]
Okay, I think it's okay as is.
