### ISSUE TITLE
error under the standalone folder

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/glslang#2213]
Hello,

Error on the standalone folder : 

![ErrorFromTheStandaloneFolder](https://user-images.githubusercontent.com/30596513/81495091-09869080-92ae-11ea-8215-20ab4f9fa4fa.jpg)

As you see It miss a makefile…

Thank you in advance to repair the problems,

Regards.

Azaretdodo.

**Comment by johnkslang** [comment]
Does this arise while following the instructions in the README?  If so, can you post at which point?

Thanks.

**Comment by Azaretdodo** [comment]
Sorry I haven't follow the readme

Now I will follow the readme

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Azaretdodo** [comment]
Hello,


I went to follow the readme,

I have launch the first command line with debug option,

the first command line doesn't happening error,

When I have launch 'make -j 6' I have happening this in end of running (in attachment)

I am on a system where I can't copy past from the system I am on fedora I Don't use ssh I have never success on fedora to set up the ssh access I have ever success on Ubuntu !

Thank you in advance for your help,

Regards.


Azaretdodo.


________________________________
De : John Kessenich <notifications@github.com>
Envoyé : lundi 11 mai 2020 18:45
À : KhronosGroup/glslang <glslang@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [KhronosGroup/glslang] error under the standalone folder (#2213)


Does this arise while following the instructions in the README? If so, can you post at which point?

Thanks.

**Comment by johnkslang** [comment]
I wasn't understanding this, and just realized perhaps because you are using email rather than this web page.

If there is still an issue, try posting here https://github.com/KhronosGroup/glslang/issues/2213, otherwise I'd like to close this out.

**Comment by johnkslang** [comment]
Okay, I can guess that means undefined symbols.  (If you quote the text instead of using an image, I could more easily use a translator.)

Those symbols are defined in `glslang/MachineIndependent/glslang_tab.cpp.h`, which is generated by a process like bison.  That's already done for you, and checked in.  That is, these symbols are defined in a file you get along with `scan.cpp`.

I can only imagine two possible causes:
1.  you have multiple copies of this header, in different places, one is old and one is new, and you need to get rid of the old one.
2. there is only one copy, that you somehow generated it yourself, using an out-of-date grammar input

**Comment by Azaretdodo** [comment]
Do you advice to compile all your h extension file but too cpp and hpp extension file?

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________
