### ISSUE TITLE
SV_Position.w vs gl_FragCoord.w

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/glslang#2244]
In Direct3D, an input variable with `SV_Position` semantic in a pixel shader keeps interpolated w value (where w is the output from the vertex shader) in its fourth component.
In OpenGL, `gl_FragCoord.w` stores 1/w, where w is the vertex shader output.
When compiling HLSL to SPIRV, the fourth component of `SV_Position` input stores 1/w similar to OpenGL, which makes it inconsistent with Direct3D and requires manual inversion in the shader.

**Comment by StarsX** [comment]
Yes, today I also realize this problem. dxcompiler has an option:
-fvk-use-dx-position-w  Reciprocate SV_Position.w after reading from stage input in PS to accommodate the difference between Vulkan and DirectX

I think it's better to let glslang consider handling the inconsistency.

**Comment by greg-lunarg** [comment]
@danginsburg Is it your experience that Vulkan's gl_FragCoord.w and DX's SV_Position w are reciprocals of each other in frag shaders? If so. how do you deal with this in your use of HLSL shaders? I am guessing you don't want glslang to start inverting SV_Position.w by default? Wondering if glslang need's a similar option to invert SV_Position.w?

**Comment by danginsburg** [comment]
@greg-lunarg Actually, this issue just bit us recently.  Yes, they are reciprocals of other.  For some reason when this bug was pointed out to me I didn't realize that it was a shader compiler issue since SV_Position.w in glslang/HLSL/Vulkan was matching gl_FragCoord.w.  I thought it was an API difference.  But thinking about it more, I think it probably should be changed in the compiler.

Doing so won't break our code if it became the default option.  We ended up using a different method for the particular use case where we hit this and apparently had been lucky and not encountered it before.

**Comment by TheMostDiligent** [comment]
We use HLSL as universal shading language for D3D11, D3D12 and Vulkan. Almost all the time the shaders work verbatim, however to workaround this issue, we have to use the following:

```hlsl
    float CameraSpaceZ = VSOut.PositionPS.w;
#   ifdef VULKAN
        // In Vulkan SV_Position.w == 1 / VSOutput.SV_Position.w
        CameraSpaceZ = 1.0 / CameraSpaceZ;
#   endif
```

I believe when compiling HLSL, it is correct to use DirectX conventions.

**Comment by greg-lunarg** [comment]
I was wondering if there was (or should be) a mode for Vulkan which generated a FragCoord.w consistent with DX. It seems like it would likely be a little more efficient than doing a divide in every shader that used FragCoord.w :P I have to think this is baked into hardware and could be enabled with little performance impact.

Such a solution might be better than changing the default now. I am worried that changing the default, either in the driver or in glslang, will break existing, running codes like that from @TheMostDiligent above.

If we decide to just fix this in glslang, I think I would do it as an a new option so as not to break existing code that has already patched around it, and to match dxc behavior.

Should we try to push for a (possibly more efficient) Vulkan mode first?

**Comment by danginsburg** [comment]
@greg-lunarg It seems perhaps worth raising as an issue in the Vulkan group, but even if something new were added older drivers would still need support.  So it seems either way I'd add the mode to glslang (I agree, it probably shouldn't be the default to avoid regressing existing customers).

**Comment by greg-lunarg** [comment]
Taking @danginsburg suggestion, I looked at the SPIR-V spec. It defines FragCoord as (x,y,z,1/w), so it seems we would need a new SPIR-V execution mode for FragCoord to be understood as (x,y,z,w) and allow glslang to avoid a reciprocal for HLSL. This is not impossible, but it is one more obstacle to overcome and capability to wait to appear in drivers.

I am therefore now leaning away from a Vulkan mode where w is delivered rather than 1/w, although I will be happy to implement it if a user finds it worthwhile and drives it to completion in the specs.

I must admit I am a little puzzled why dxc created an option to deliver w rather than just do it by default. Maybe they were trying to stay compatible with glslang. I am a little worried that new users will miss the new, extra option to get true HLSL semantics and waste time tracking it down. Still, I think compatibility with dxc is the better play at this point.

So my proposal is to do the reciprocal under a new compile option as dxc does.

**Comment by greg-lunarg** [comment]
I am moving ahead with the latest proposal above.

**Comment by greg-lunarg** [comment]
The glslangValidator command line option  will be --hlsl-dx-position-w.

**Comment by greg-lunarg** [comment]
The library interface is void TShader::setDxPositionW(bool dxPosW);

**Comment by TheMostDiligent** [comment]
Thank you!

**Comment by TheMostDiligent** [comment]
@greg-lunarg I finally got my hands on the fix and it did not really work in my case, unfortunately. 
The problem is that [this code](https://github.com/KhronosGroup/glslang/blob/master/glslang/HLSL/hlslParseHelper.cpp#L2172-L2182) never runs. After debugging a bit I think the reason is because the code expects that `SV_Position` will be a top-level variable. In my case, however, it is a member of a struct (which is a standard scenario in HLSL):

```hlsl
struct VSOutput
{
    float4 PositionPS 	        : SV_Position;
    float3 PosInLightViewSpace 	: LIGHT_SPACE_POS;
    float3 NormalWS 	        : NORMALWS;
    float2 TexCoord 	        : TEXCOORD;
};

float4 MeshPS(VSOutput VSOut) : SV_TARGET
{
...
```

As a result, `input->getType().getQualifier().builtIn == EbvFragCoord` check fails and members of the struct are not examined.

**Comment by greg-lunarg** [comment]
Yes. Sorry. I am seeing this as well. I think your expectations are correct. I will look into this right away.

**Comment by TheMostDiligent** [comment]
@greg-lunarg I just tested this and it works now! Thank you!

**Comment by alecazam** [comment]
We have the reverse of this issue.  Going from GLSL to SPIRV then to HLSL, but our GLSL shaders are written to assume gl_FragCoord.w is 1/w.   We're seeing rendering issues as a result.   This sounds like the fix was only solves HLSL to SPIRV.

**Comment by greg-lunarg** [comment]
> We have the reverse of this issue...

@alecazam Might this be a bug in your tool that is doing SPIRV->HLSL?
