### ISSUE TITLE
Decimal mark dependency

### ISSUE THREAD

**Issue by moresascha** [KhronosGroup/glslang#234]
Currently the compile time string to binary number parsing depends on the current active locale.

```
#version 450 core
layout(set = 1, binding = 0) uniform sampler2D tex;
layout(location = 0) in vec2 texcoord;
layout(location = 0) out vec4 outColor;

const float OFFSET_X = 0.5f;

void main()  {
    outColor = texture(tex, vec2(texcoord.x + OFFSET_X, texcoord.y));
}
```

Decimal mark set to "," (e.g. setlocale(LC_ALL, "German_Germany")) produces:

```
...
23:    6(float) Constant 0
...
```

Default Decimal mark "." produces the correct output:

```
...
23:    6(float) Constant 1056964608
...
```

**Comment by xorgy** [comment]
Very good catch, wow.

**Comment by johnkslang** [comment]
Both strtod() and atod() are in use, each once, and each (annoyingly) takes locale into account.

These are not trivial functions to replicate, and locale is typically a process-wide setting.  Bringing in streamstring stuff to imbue it with a stream-specific locale also feels heavyweight for this purpose, but perhaps not?  Any other ideas?

**Comment by Robert42** [comment]
I ran into the same issue. I am using the glslang static library directly, so calling `setlocale(LC_ALL, "C");` at the start of my application was a simple workaround which did the job for me.

**Comment by xorgy** [comment]
@johnkslang For what it's worth, we have a full number parser in the preprocessor. Though it is not the prettiest code; it is straightforward.

**Comment by ratchetfreak** [comment]
strtod() has a variant that takes the locale to use explicitly in both [windows (_strtod_l)](https://msdn.microsoft.com/en-us/library/kxsfc1ab.aspx) and [linux (strtod_l)](http://www.manpagez.com/man/3/strtod_l/): 

Looking around a bit I found a gist with an example to create a strtod that always uses the C locale without affecting the application's locale: https://gist.github.com/tknopp/9271244

**Comment by xorgy** [comment]
@johnkslang I was writing a standalone number parser, so I looked at the specification to make sure. In looking at the GLSL specification, I think that GLSL's definition of floating-point literals is more narrow than that of both the `PpScanner.c` parser and `strtod`. For example, _The OpenGL Shading Language 4.6 Revision 3_ makes no mention of [-]1.#INF[INITY] in §4.1.4.

Is this an inadequacy in the specification, or an excess in the implementation? I'm confident I can write (and exhaustively test) a compact standalone parser which accepts only what's specified in the specification, but otherwise behaves like a correct strtod, just wanna make sure I'm not missing something.

**Comment by xorgy** [comment]
GLSL spec also seems to not correctly encode the case where _sign_ appears before _fractional-constant_.

**Comment by xorgy** [comment]
The language regarding parsing signs in §4.1.3 and §4.1.4 is a bit weird. It says to treat the `-` as a unary operator, but that it makes it impossible to represent `INT_MIN` and similar constants (since positive 2147483648 can not fit in `int`). Since there are so few guarantees, and such low expectations, of the exact behavior of floats on GPUs, it may not be a problem for float constants like it is for ints.

**Comment by xorgy** [comment]
Maybe we should also accept the wisdom of §4.1.3 and §4.1.4, and parse the sign characters as unary operators, rather than as part of the constant.

**Comment by johnkslang** [comment]
Basically agreed, and agreed about the accidental inclusion of the HLSL syntax.

Otherwise, I think the glslang parser is validating against the spec, it just uses the library functions to create the actual number.

**Comment by johnkslang** [comment]
It turns out this is a quite complex problem.  To completely correctly both parse and print double values is ~1000 of lines of code, so I prefer to use library functions. Yet, library functions for these are not completely portable.  istringstream is different than strtod, and handles infinities differently, and all functions vary across platforms, and even the ways of controlling them are not standardized, because the C++ standard is not IEEE based. Further, istringstream is very slow.

(General side note: to get even close to correct rounding requires slow algorithms, whose performance is dependent on the actual values being translated. These are available in istringstream, and it is worth using them for some values.)

I believe, now, I have a combination of 
- an explicit (means totally portable) fast path that handles most values
- istringstream that handles the remaining values
- an explicit detection of infinities, both directions
- not printing to full precision, to get portable testing
- high performance by caching the istringstream and only using it when the fast path might not get the correct result

**Comment by johnkslang** [comment]
https://github.com/KhronosGroup/glslang/pull/1385 has a series of three commits that

1. increase testing in this area
2. changes macro processing to not need to reparse floating-point tokens
3. uses a combination of istringstream and a fast path for parsing of floating-point tokens

These should be locale dependent. If not, it should now be an easy fix.  See the pull request for more details.

**Comment by johnkslang** [comment]
Note this line in the currently passing test:

```
double pi = 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679;
```

I will try a few things.
