### ISSUE TITLE
extension directives must occur before any non-preprocessor tokens.

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2527]
Hi ,

Acoording to the glsl4.6 spec ,ch3.3 Preprocessor :
> Each extension can define its allowed granularity of scope. If nothing is said, the granularity is a shader
> (that is, a single compilation unit), **and the extension directives must occur before any non-preprocessor
> tokens.**

shader :
```
#version 300 es
#extension all : warn

precision mediump float;
in highp vec4 dEQP_Position;

void main()
{
#extension all : disable
       gl_Position = vec4(1.0);
}
```
glslang didn't report the error for this case. Thany you.

**Comment by greg-lunarg** [comment]
Looking at some of the tests written for glslang, it seems fairly clear that some extension directives are allowed to appear after non-preprocessor tokens. So the question here is: is this true for "all"?

I think one could possibly make some kind of argument that this should be disallowed, but I think it would have to be inferred; I don't think it is explicitly stated one way or the other. Also it would not be dependent on the spec directly, but rather on the sum total of all extensions that are supported. Do you know of an extension where this should not be allowed? If you know of one, please let me know. Otherwise I will assume the the previous implementers did things correctly. I do not want to disallow a capability unless there is a good reason.

I am going to close this for now, but if you think of a reason that it is causing bad behavior, please re-open and explain.

**Comment by ZhiqianXia** [comment]
@greg-lunarg I also see a similar [issue](https://github.com/KhronosGroup/glslang/issues/97) , According to johnkslang advice,
there is a warning at least. In fact, error is better for graphics chip manufacturers.
