### ISSUE TITLE
Is it necessary to do this if the constant fold produce wrong result ?

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2529]
Hi ,
   I recently encountered an precision issue caused by constant folding log2 and exp2 op. The relative code located at
glslang\MachineIndependent\Constant.cpp , and the line number is 601~612.  Here is the code:

```
case EOpExp2:
	{
		const double inv_log2_e = 0.69314718055994530941723212145818;
		newConstArray[i].setDConst(exp(unionArray[i].getDConst() * inv_log2_e));
		break;
	}
case EOpLog2:
	{
		const double log2_e = 1.4426950408889634073599246810019;
		newConstArray[i].setDConst(log2_e * log(unionArray[i].getDConst()));
		break;
	}
```
As you can see，there are simple math tricks to replace log2 and exp2 from the original idea.  
But didn't consider the presicion issue :  **log2_e * logx   !=  log2_x** at some case. 

So Is it necessary to do this if the constant fold produce wrong result ?  thank you. 
Here is a example:

> double input = 52.375000000000000;
> double ret = std::log2(input);                                                                     // **5.7108064336993518**
> double ret2 = 1.4426950408889634073599246810019 * std::log(input);  // **5.7108064336993509**

**Comment by greg-lunarg** [comment]
It is allowed. From the 4.6 spec, section 4.9:

Without any qualifiers, implementations are permitted to perform optimizations that effectively
modify the order or number of operations used to evaluate an expression, even if those
optimizations may produce slightly different results relative to unoptimized code.

It is sometimes happens no matter what because some graphics platforms only support e-based log and exp, and not 2-based.

There are ways to control this to a certain extent. There is the **precise** and **invariant** qualifiers in GLSL, for example. Not quite sure if they make a difference in this case, but they might.

Please re-open if you have follow-up questions.

**Comment by ZhiqianXia** [comment]
In the actual code , the precise qualifiers have been delcared. in other words,  the log2 math function always produce the precision error no matter you delcared it or not , as long as you do the constant fold.

**Comment by ZhiqianXia** [comment]
@greg-lunarg This problem seems to have been encountered by others. 
[log2](https://github.com/KhronosGroup/glslang/pull/2122)

**Comment by greg-lunarg** [comment]
Sorry, it appears my comment yesterday did not get committed.

This code is fairly old and may have gone in when only c++98 was allowed which did not support log2 or exp2. c++11 does support these, so I support changing this code to use them.

**Comment by ZhiqianXia** [comment]
@greg-lunarg thank you . I will commit the PR latter.
