### ISSUE TITLE
debugPrintfEXT does not work with rgen/rmiss/rchit khr shaders

### ISSUE THREAD

**Issue by Luke-Filewalker** [KhronosGroup/glslang#2548]
When using debugPrintfEXT("%d", 100) with a compute, vertex, fragment etc shader, the debugPrintfEXT value is passed to the callback and an output like the following is produced

`Validation Information: [ UNASSIGNED-DEBUG-PRINTF ] Object 0: handle = 0x1e5d398f8b8, type = VK_OBJECT_TYPE_DEVICE; | 
MessageID = 0x92394c89 | 100`

But when debugPrintfEXT("%d", 100) is used with a khr ray tracing shader, the output looks like this

`Validation Information: [ UNASSIGNED-DEBUG-PRINTF ] Object 0: handle = 0x1e5d398f8b8, type = VK_OBJECT_TYPE_DEVICE; | 
MessageID = 0x92394c89 | `

The value from the printf is not passed to the callback.

Vulkan sdk 1.2.162.1 
GPU Nvidia 2080 ti
Windows 10 20H2

**Comment by greg-lunarg** [comment]
I have looked at both the SPIR-V generated by glslang as well as that generated by spirv-opt --inst-debug-printf DebugPrintfEXT instrumentation pass and I am not seeing anything obviously wrong. Could you please create a similar issue against https://github.com/KhronosGroup/Vulkan-ValidationLayers and have them take a look? Please also reference this issue so they can see my results here.

I am going to close this now. If it turns out there is a problem with glslang, we can re-open.

**Comment by Luke-Filewalker** [comment]
It seems that this issue is already resolved, sorry should have also checked the Vulkan-ValidationLayers repo.
KhronosGroup/Vulkan-ValidationLayers#2469
