### ISSUE TITLE
SPIRV include files get installed under `include/glslang/SPIRV` instead of `include/SPIRV` when added as public interface

### ISSUE THREAD

**Issue by axsaucedo** [KhronosGroup/glslang#2571]
When adding the glslang and SPIRV dependencies to a target as PUBLIC target link, and then performing an installation, the headers of SPIRV get installed under `include/glslang/SPIRV` instead of `include/SPIRV` as expected in the targets. This leads into failures as the SPIRV headers can't be found under the expected paths.

**Comment by aliPMPAINT** [comment]
I'm trying to solve this issue with:
```
#if KOMPUTE_OPT_REPO_SUBMODULE_BUILD
#include <SPIRV/GlslangToSpv.h>
#else 
#include <glslang/SPIRV/GlslangToSpv.h>
#endif
```
but the tests fail

**Comment by axsaucedo** [comment]
Thank you @aliPMPAINT - this also seems like a workaround, the folder structure when running `make install` should be the same to the one when running for example `sudo apt install glslang-dev`, but it's not atm.

**Comment by greg-lunarg** [comment]
This is not a bug; it's a feature :)

Seriously, I am not aware of any specification or other requirement stating that a glslang install would install outside of include/glslang. And it seems to me to be good practice that it only would install within include/glslang so that it does not overwrite other identically named headers.

The glslang library API can be run with all headers under include glslang/include. It contains and maintains its own SPIRV headers under include/glslang/SPIRV. It **requires** those headers be in that place.

If there is some specification that states glslang install will install files under include/SPIRV, please document and re-open this issue.

**Comment by axsaucedo** [comment]
@greg-lunarg ok I see what you mean now, this has also clarified the reason why I was having this issue, looking back at the suggestion by @aliPMPAINT that actually does seem to be the way to go - thanks!
