### ISSUE TITLE
subroutine still not support ???

### ISSUE THREAD

**Issue by zhenxin8916** [KhronosGroup/glslang#2575]
Hi, current glslang still not support subroutine ??? why ?
//-------------------------------------------------------------
#version 450 core

subroutine void subroutineType (inout vec4 result);
subroutine vec4 subroutineType2(in    vec4 data);

subroutine(subroutineType) void function1(inout vec4 result)
{
    result += vec4(1, 2, 3, 4);
}
subroutine(subroutineType) void function2(inout vec4 result)
{
    result += vec4(2, 3, 4, 5);
}

subroutine(subroutineType2) vec4 function3(in vec4 data)
{
    return data * data;
}
subroutine(subroutineType2) vec4 function4(in vec4 data)
{
    return data + data;
}

subroutine uniform subroutineType  subroutine1;
subroutine uniform subroutineType  subroutine2;
subroutine uniform subroutineType2 subroutine3;
subroutine uniform subroutineType2 subroutine4;

out vec4 result;
void main()
{
    result = vec4(0);
    subroutine1(result);
    subroutine2(result);
    result = subroutine3(result) + subroutine4(result);
}
//---------------------------------------------------------------
glslang ast parse failed info:

ERROR: 0:3: 'subroutine' : feature not yet implemented
ERROR: 0:3: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

**Comment by greg-lunarg** [comment]
Like any open source effort, features are not implemented because no one has given them enough priority to make them happen. That apparently is the case here.

While it appears that some IHVs have implemented this feature, I have seen suggestions online that this capability has fallen out of favor and programmers are just using switch statements. This is reinforced by the fact that Vulkan and SPIR-V do not support this capability.

I am currently not funded to implement this, however I am open to accepting a PR if submitted.

Issue https://github.com/KhronosGroup/glslang/issues/141 already documents that this capability is missing, so I will close this issue.
