### ISSUE TITLE
Undefined behavior with shader including -2147483648

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/glslang#2652]
See this clusterfuzz bug for the error report: https://bugs.chromium.org/p/chromium/issues/detail?id=1202390

In short, if the shader contains -2147483648 (note that 2147483648 is 0x80000000), glslang parses it as 0x80000000 that is then negated. When constant folding, UBSAN complains about negating this value.

The lexer should have probably just parsed -2147483648 as one signed number.

**Comment by greg-lunarg** [comment]
Please refer to https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf, 4.1.3 Integers. You will see that glslang is correct in treating this as negated 0x80000000. Specifically:

> ... When the suffix u or U
> is present, the literal has type uint, otherwise the type is int. A leading unary minus sign (-) is
> interpreted as an arithmetic unary negation, not as part of the constant. Hence, literals themselves
> are always expressed with non-negative syntax, though they could result in a negative value.
> It is a compile-time error to provide a literal integer whose bit pattern cannot fit in 32 bits. The bit
> pattern of the literal is always used unmodified. So a signed literal whose bit pattern includes a set
> sign bit creates a negative value.

I can understand why UBSAN would complain about negating this value since negated 0x80000000 is not representable in a 32-bit int.

Please feel free to re-open if you feel my analysis is not correct. If you do, please supply the following:

- A valid GLSL shader
- A glslangValidator command line that replicates the issue
- A description of the incorrect behavior you observed

Thanks.

**Comment by greg-lunarg** [comment]
FYI, according to my sources, glslang's behavior here is the same as C++.

**Comment by ShabbyX** [comment]
Thanks for the spec quote. Could we work around it? Something like this could do:

```
// In glslang/MachineIndependent/Constant.cpp:532
-            case EbtInt:   newConstArray[i].setIConst(-unionArray[i].getIConst()); break;
+            case EbtInt:   newConstArray[i].setIConst(unionArray[i].getIConst() == 0x80000000 ? INT_MIN : -unionArray[i].getIConst()); break;
```

**Comment by greg-lunarg** [comment]
OK, I am understanding a little better the problem you are having: UBSAN is flagging the negate during glslang compilation.

I am fine with the above change. Do you want to write up the PR or should I?
