### ISSUE TITLE
Branching code instead of OpSelect generated when ternary operators are stored into partial vectors

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/glslang#2672]
I hope I'm not messing something up here, but looking with some of my colleagues into code generated by glslangvalidator I believe we found a case where glslangvalidator is creating unoptimized SPIR-V, which spirv-opt -O doesn't fix. Specifically the case is when the GLSL code uses a ternary operator and stores the result in a subset of a vector, for example:
```
t.x = test > 0.4 ? a.x : b.x;
```

In the original application, if we take the shader, compile it through glslangvalidator, then spirv-cross it and look at it again, 
```
    u_xlat16_2.x = (u_xlatb5.x) ? u_xlat16_3.x : u_xlat16_4.x;
```
becomes post-glslangvalidator-then-spirv-cross:
```
    mediump float _347;
    if (u_xlatb5.x)
    {
        _347 = u_xlat16_3.x;
    }
    else
    {
        _347 = u_xlat16_4.x;
    }
    u_xlat16_2.x = _347;
```

This obviously is pretty unefficient, it adds an extra variable and full branching. I repro'd this locally using glslangvalidator of mid-february from SDK 1.2.170, and the issue doesn't come from spirv-cross, the actual SPIRV generated has the branches.

I played with shader-playground to try to find the root cause in http://shader-playground.timjones.io/7c20ab03257ca297e27af1bdf71eadf3 . If you switch between the 3 operations:
```
    t = test > 0.4 ? a : b;
    t.x = test > 0.4 ? a.x : b.x;
    t.x = mix(a.x,b.x,test>0.4);
```
only the 2nd one generates the branching. Both the first one (ternary, but full-vector), and the last one (same thing as the 2nd one but using boolean-mix instead of ternary ops) generate faster, OpSelect-based code.

**Comment by greg-lunarg** [comment]
FWIW, a uniform branch sometimes can be faster than a select. It depends on the complexity of the control dependent code. The more complex, the better the branch performs. That's because, for most modern GPUs, a uniform branch will only evaluate **one** of the branches. A select must evaluate the code in both branches and then do a select between them.

This could explain the difference between the first and second cases above. The second does an additional extract of .x , making the dependent code more complex, making the branch more appealing.

Ultimately, it is the job of glslangValidator to only generate **correct** code. Most drivers are fairly good at generating the best performing code for shaders, often based on qualities of the GPU that glslangValidator cannot know or assume.

It is only an issue if glslangValidator generates code that cannot be optimized. I don't think we have that situation here.

So with all due thanks for your concern and time, I will close this. Please reopen if you think this code sequence is not optimizable by a downstream tool.

**Comment by tuxerr** [comment]
I guess that's fair, I'll let you know when we run more exhaustive performance tests. I still think that, for what it's worth,
```
    t.x = test > 0.4 ? a.x : b.x;
    t.x = mix(a.x,b.x,test>0.4);
```
should execute the same commands, they're effectively the same thing given that mix here has its 3rd argument as a boolean. 
The fact that mix generates less SPIR-V instructions (smaller code, and I believe more efficient, although we don't have hard data yet ;) ) is weird to me, and similarly the fact that the ternary isn't stable through SPIR-V cross (although I know compiling/decompiling isn't a bijection) makes me thing we're not doing things optimally.
