### ISSUE TITLE
#extension GL_ARB_fragment_coord_conventions meets compiler error

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2681]
Hi , there is a compiler error about **GL_ARB_fragment_coord_conventions**.

shader:
```
#version 140

#extension GL_ARB_fragment_coord_conventions: require
#extension GL_ARB_explicit_attrib_location : enable

layout (location = 0) in vec4 pos;
out vec4 i;

uniform float gtf_windowWidth;
uniform float gtf_windowHeight;
uniform float n;
uniform float f;

void main()
{
  gl_Position = pos;
  i = vec4((pos.x+1.0)*0.5*gtf_windowWidth, (pos.y+1.0)*0.5*gtf_windowHeight, (f-n)*0.5*pos.z + (f+n)*0.5, pos.w);
}
```

**Comment by greg-lunarg** [comment]
Are are compiling for SPIR-V or validation? If SPIR-V, for Vulkan or GLSL?

**Comment by greg-lunarg** [comment]
Assuming you are just validating...

Please note that this shader actually does not use the capabilities of this extension. That line can be removed from this shader without problem. So this issue is really not about enabling a shader in a practical way.

It appears that the functionality of GL_ARB_fragment_coord_conventions was merged into the GLSL core at some point. It appears that point may be #version 150. This is likely why the extension was never implemented for #version 140 or previous versions.

Since this capability is available in core, I am not going to consider this a bug or even an candidate for enhancement based on this shader. If there are real shaders out there that need this extension in 140 or earlier, I will reconsider.
