### ISSUE TITLE
[Question] How to remove unused varying variables ? 

### ISSUE THREAD

**Issue by Retr111** [KhronosGroup/glslang#2707]
At present, it seems that the Link + MapIO operation of TProgram will not remove redundant varying, such as variables output in the vertex shader but not used in the fragment shader.

Is there a way to remove these variables, otherwise we can only rely on the driver to optimize these variables.

vertex shader:

```
out highp vec3 WorldPosition;    // unused in fragment shader
out highp vec2 UV0;
```

fragment shader:
```
in highp vec3 WorldPosition;  // unused
in highp vec2 UV0;

void main()
{
    // depth only + alpha test
   if (texture(xxx, UV0).a < 0.5)
   {
        discard;
   }
}
```

**Comment by greg-lunarg** [comment]
I presume we are talking about generating SPIR-V. Correct? If so, for Vulkan or OGL or both?

**Comment by greg-lunarg** [comment]
I think this is legal when targeting SPIR-V and Vulkan.

Is there a way? There is always a way. The question is how much analysis do we want to do and what is the implementation cost.

I am not very familiar with the Link + MapIO mechanism and its relationship to AST generation. I presume all AST generation is done before any linking. This is probably not ideal for this kind of optimization. It would mean we would have to go back and do another pass on the ASTs, deleting unneeded variables and stores to them. We are looking at a non-trivial amount of work.

Since I believe I have answered your question, I will close for now. Feel free to re-open if you have additional questions.
