### ISSUE TITLE
Precision qualifier is mandatory for subpass inputs

### ISSUE THREAD

**Issue by chirsz-ever** [KhronosGroup/glslang#2827]
Example (`test_subpass.frag`):

```glsl
#version 310 es
precision highp float;

layout (input_attachment_index=0, binding=2) uniform subpassInput MySb;

layout (location = 0) out vec4 fragColor;

void main()
{
    fragColor = subpassLoad(MySb) * 0.5;
}
```

Compile command and outpust:

```sh
$ glslangValidator test_subpass.frag -V
test_subpass.frag
test_subpass.frag
ERROR: test_subpass.frag:5: 'sampler/image' : type requires declaration of default precision qualifier
ERROR: test_subpass.frag:5: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.


ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

After inserting `highp` before `subpassInput MySb`, compilation passed.

The [GL_KHR_vulkan_glsl](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt) seems not mention the  precision qualifier is mandatory, is this normal?

**Comment by greg-lunarg** [comment]
Yes. What you are experiencing is GLSL-ES rules which state that every type must a precision, and in fragment shaders, float and opaque types do not have a default precision and so they either need a precision statement in scope or a precision qualifier in the declaration.

subpassInput is an opaque type. While I am not able to find a statement explicitly calling out this type as not having a default precision qualifier, it is either because I didn't look hard enough or the documentation is faulty. No matter, I believe this is the intended behavior.

If you can find documentation that contradicts my beliefs above, please post them here and I will re-open.

**Comment by chirsz-ever** [comment]
[GLSL ES 3.2 says](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html):
> The fragment language has no default precision qualifier for floating-point types. Hence for float, floating-point vector and matrix variable declarations, either the declaration must include a precision qualifier or the default float precision must have been previously declared. Similarly, **there is no default precision qualifier in any of the languages for any type not listed above**.

And GL_KHR_vulkan_glsl says:
> All these versions map GLSL/ESSL semantics to the same SPIR-V 1.0 semantics (approximating **the most recent versions** of GLSL/ESSL).

So glslang behaves correctly, `subpassInput` indeed need a precision qualifier.

But the example code in GL_KHR_vulkan_glsl did not contains a precision qualifier, maybe it needs a consultation.

**Comment by greg-lunarg** [comment]
The example works for OpenGL, but not OpenGL ES.

In general, the text for GL_KHR_vulkan_glsl is just specified in terms of OpenGL. I am guessing the author presumed that the reader would understand how this would map to OpenGL ES implicitly.
