### ISSUE TITLE
Unit test non-determinism

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#2858]
When SPIR-V 1.6 support was add, a test non-determinism was introduced. If you run all of the tests in Spv.FromFile.cpp together they pass, but if you filter and just run the 1.6 tests then `spv.1.6.conditionalDiscard.frag` fails with a diff in the expected SPIR-V.

```
With diff:
@@ +18,5 @@
                               Decorate 13(tex) Binding 0
                               Decorate 17(coord) Location 0
+                              Decorate 34(gl_FragColor) Location 0
                2:             TypeVoid
                3:             TypeFunction 2
```

To reproduce, run:
```
# all tests
./gtests/glslangtests

# just 1.6
./gtests/glslangtests --gtest_filter=*spv_1_6_*
```

I haven't tracked it down, but I assume there is some global state that is not properly reset (presumably related to the client environment).

**Comment by greg-lunarg** [comment]
I will take it from here. Thanks.

**Comment by greg-lunarg** [comment]
The problem is that currently glslangValidator requires a semantic target, either OpenGL or Vulkan. OpenGL only accepts spirv1.0, and there is currently no Vulkan target that accepts spirv1.6. I tried using something I found in glslang called the Universal target, which got me through the validator, but is apparently not quite the generic SPIR-V target I had hoped for. Since SPIR-V really doesn't make sense without a target, rather than spend time making the (useless?) Universal target work, I am just going to wait for Vulkan1.3 and fix this problem then.

**Comment by ben-clayton** [comment]
Is there any way to remove the non-determinism here? Regardless of targets, it seems like a Bad Thing™ that we have state leakage between tests.

**Comment by greg-lunarg** [comment]
Ah! I had no idea. Very sorry. Yes, I will disable.

**Comment by ben-clayton** [comment]
No worries. We should have made that clearer from the start.
Many thanks!
