### ISSUE TITLE
Need to exit after first ERROR

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#29]
```GLSL
#endif
#endif
#endif
#endif
#endif
#endif
#endif

#if
#else
```
and a number of similar inputs exercise a segmentation fault bug in `glslang::TPpContext::tStringInput::scan`.

**Comment by xorgy** [comment]
Aside: Sorry I can't be of more help in actually fixing these, full-time employment imposes limits on what time I can devote to this.

**Comment by dneto0** [comment]
I find your bug reports really interesting and valuable.  Please continue!
Curious: Can you share how you are finding these issues?

**Comment by xorgy** [comment]
I think I forgot to credit the venerable [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/) or afl-fuzz fuzzer, which I have been using to help find these bugs.

The reason most of the finds have been in the preprocessor so far is because until the bugs are worked out in the preprocessor, it'll prioritize those paths for finding bugs.

**Comment by dneto0** [comment]
I was playing with this and got another crash from trying 150 #endif's in a row.
My best guess is the bug is in the PpAtomEndif case of TPpContext::readCPPline:

            elseSeen[elsetracker] = false;
            --elsetracker;

I bet that with enough #endif's and no other preprocessor directives,  elsetracker underflows and stomps on other memory.

The fact that you saw a problem with 7 #endifs is just by luck.  It could have crashed or produced incorrect results earlier.
I'm not promising to fix this (soon).

**Comment by xorgy** [comment]
Yeah, I'm aware of the deeper causes of these bugs, just don't have a whole lot of time myself to fix them.

As an aside, I'm looking at [csmith](https://embed.cs.utah.edu/csmith/) to see if I could modify it to generate valid GLSL code which triggers bugs in the semantic analysis, since an unstructured binary fuzzer like afl-fuzz will probably not find as many semantic bugs as syntax validation bugs in the parser.

**Comment by johnkslang** [comment]
Yes, thanks for the reports.  I fixed a set of them recently, and will take another round again in a few days.  

A big class (most?) of them comes from continuing after an error is found, which requires leaving state valid.  This is useful for testing and developing, but has no purpose on an end-user system.

One alternative, for end users, is to just stop after the first error, unless in a developer/testing mode.  This would matter for protecting against malicious software, where not all combinations of cascading errors need testing, just each first error.

Comments?

**Comment by baldurk** [comment]
Speaking just for my use case I'd find it very useful to prioritise stability over additional error reporting. I'm embedding glslang for SPIR-V compilation within another program that takes in arbitrary user-provided shaders, so I need to be confident that errors in the input won't cause a crash.

Obviously it's a "would be nice" kind of feature to report as many errors as safely possible, but that's purely for the user's information and I think most people are used to compilers bailing out at some point even if there are more errors to find.

**Comment by xorgy** [comment]
@johnkslang, @baldurk: I think a good balance to strike would be to set up an error accumulator which could be configured to stop on the first error, or not.

We can continue to work out the kinks of the full-scan validation, and at the same time offer a mode which is theoretically more robust.

Thoughts?

**Comment by xorgy** [comment]
@baldurk: For your use case, my first instinct would be to isolate the validator/compiler in a completely separate process, and spawn it for each task.

**Comment by johnkslang** [comment]
@xorgy Yes, a switch to say which behavior is desired is what I have in mind.  The caller of the library would have to request cascading errors; the default would be to stop after the first error.  I would certainly use it in cascading mode, and fix bugs that uncovers, because it's more efficient to test multiple errors in the same compilation unit.

**Comment by johnkslang** [comment]
Reopening, as the merge request was just one example of this subject.

**Comment by johnkslang** [comment]
I realized it's pretty easy to simulate end-of-file when an error is seen, causing the natural end of parsing without any exception handling, stack unwinding, extra tests everywhere to protect against previous error, etc.

Commit a86836ede213899dcb56f8220d5a8d40d342dfe8 does this.

By default, crashes should no longer happen, because cascading errors from error recovery must be explicitly requested with -C (or the EShMsgCascadingErrors message flag through the API).

This fixes several issues and generally makes glslang much more robust.
