### ISSUE TITLE
glslangvalidator problem with local_size in vulkan1.3

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glslang#2934]
if I specify `layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;` in a compute shader, and compile using the following command:
`glslangValidator -V --target-env vulkan1.3 -g0 test.comp -o test.comp.spv`

I get this validation error:
**_VUID-RuntimeSpirv-LocalSizeId-06434
if execution mode LocalSizeId is used, [maintenance4](https://www.khronos.org/registry/vulkan/specs/1.3-khr-extensions/html/chap38.html#features-maintenance4) must be enabled_**

And if I change the target-env to vulkan1.1, the error disappears.

this happens to me even when the code is just this:

```glsl
#version 460
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main() { }
```

**Comment by greg-lunarg** [comment]
I presume that you are getting this validation error from the Vulkan Validation layers, correct?

When you ask for --target-env vulkan1.3 , you will get SPIRV 1.6. In 1.6, the WorkgroupSize builtin was deprecated, redirecting users to LocalSizeId Exection Mode. When I updated glslang for 1.6, I changed glslang to *always* generate LocalSizeId Execution mode. I did not realize that LocalSizeId Execution Mode required additional hardware support.

I think the correct thing to do here is to generate LocalSize Execution Mode when possible (all local size components are literal constants) and LocalSizeId Execution Mode otherwise.

Sorry about that. I will fix that shortly.

@jaebaek dxc might have a similar problem. You might want to double check.

**Comment by jaebaek** [comment]
Thank you for letting me know! I will open a bug about it.

**Comment by greg-lunarg** [comment]
So I did find language in the Vulkan 1.3 spec that says that maintenance4 is now part of core.

So either you are running Vulkan 1.2 (which will not support shaders compiled for Vulkan 1.3) or VVL is in error. Either way, this is not a problem with glslang.

I could spend time making this behavior work, but unfortunately that work would be outside of the Vulkan spec which is beyond my charter. I suggest pursuing the other avenues I have pointed out.

**Comment by dorian-apanel-intel** [comment]
@greg-lunarg 

> So either you are running Vulkan 1.2 (which will not support shaders compiled for Vulkan 1.3) or VVL is in error. Either way, this is not a problem with glslang.

On VK 1.3 you still have to enable `VkPhysicalDeviceVulkan13Features.maintenance4` and pass it in `pNext `of `VkDeviceCreateInfo`. This should get rid of VVL warning.
