### ISSUE TITLE
cross-compile of 'packHalf2x16'

### ISSUE THREAD

**Issue by zhrit** [KhronosGroup/glslang#2946]
When cross compiling a GLSL shader, `packHalf2x16` in GLSL is translated into SPIRV as `44(int) ExtInst 1(GLSL.std.450) 58(PackHalf2x16) 175` by glslang, and then is translated into HLSL as `spvPackHalf2x16` by spriv-cross.
If cross compiling the new HLSL shader into GLSL，the `spvPackHalf2x16` will be treated as a function, but not a instruct. The result code is like `9(int) FunctionCall 12(spvPackHalf2x16(vf2;) 338(param)` in SPIRV and  ` _RESERVED_IDENTIFIER_FIXUP_spvPackHalf2x16` in GLSL.
Is it possible to treat `spvPackHalf2x16` in HLSL as a instruct, and map to the `packHalf2x16` in GLSL?

**Comment by greg-lunarg** [comment]
Possible? Yes. Good idea? Well, there is a better way to do this.

The way to do this is with SimplificationPass in spirv-tools. This pass is designed to do just this kind of thing. With just a few lines of code in spirv-opt, this can happen. Doing this in glslang would take hundreds of lines. This alone justifies doing this in spirv-tools.

You will then get this as part of glslang, although you will need to add -Os to glslang when compiling HLSL to guarantee this will happen.

Plus you will have the added advantage that this would then be available when using the dxc frontend for free. Again, you should ask for optimization on dxc, here I think it would be -O3.

So I would direct you to open an issue/request on spirv-tools and reference this issue. Because the argument for doing this elsewhere in the spirv toolchain is so strong, I am going to close this issue here.
