### ISSUE TITLE
can't build wasm

### ISSUE THREAD

**Issue by romamik** [KhronosGroup/glslang#3088]
I've tried building the wasm version following instructions from the readme, but CMake failed with this error:
```
CMake Error: Cannot determine link language for target "glslang.js_1_glslang_pre_js".
```
I'm on Mac and also tried ubuntu in docker. Both arm64 if that matters.

**Comment by wdanilo** [comment]
I've got the same issue.

**Comment by jeremy-lunarg** [comment]
Regression from #2339. The LANGUAGES statement was restricting which languages `cmake` would detect. I've submitted a [PR](https://github.com/KhronosGroup/glslang/pull/3098).

On a related note, this regressed over two years ago and was not detected by CI because there is no coverage for this configuration.
