### ISSUE TITLE
Binary logical operators &&, ||, ^^ do not work on vector types

### ISSUE THREAD

**Issue by rdb** [KhronosGroup/glslang#3118]
This code fails to compile with a diagnostic:
```glsl
#version 460

uniform bvec4 a;
uniform bvec4 b;

void main() {
    a && b;
}
```
```
ERROR: 0:7: '&&' :  wrong operand types: no operation '&&' exists that takes a left-hand operand of type ' uniform 4-component vector of bool' and a right operand of type ' uniform 4-component vector of bool' (or there is no acceptable conversion)
```

The GLSL 4.6 spec has this to say:
> The logical binary operators and (**&&**), or (**||**), and exclusive or (**^^**) operate only on two Boolean expressions and result in a Boolean expression.

The wording in the spec strongly implies that "Boolean" refers to vectors as well:
> **Definition**
> A *boolean type* is any boolean scalar or vector type (**bool**, **bvec2**, **bvec3**, **bvec4**)

In all other places where only bool scalars are returned, the spec uses the language "scalar Boolean" specifically, eg:
> Relational and equality operators (<, <=, >, >=, ==, !=) are defined to operate on scalars and produce
scalar Boolean results.

This makes the spec unambiguous in my opinion, that these operators are expected to be accepted for Boolean vectors and not just scalars.

**Comment by rdb** [comment]
It looks like this behaviour was deliberately introduced by @johnkslang in 69762564dee079fedc5e725899b0fa0a4f8430ac.  It also looks like some drivers are getting this wrong.

John, is this actually an issue in the wording of the spec?  It uses the term "Boolean expression", which isn't used anywhere else in the spec in that combination, but the most obvious interpretation is just "an expression of any Boolean type".  The term "scalar Boolean" is used in other places where it matters.

And it makes sense for these operations to be defined on *any* Boolean type, which is also what HLSL does (and what SPIR-V allows, for what it's worth), and doing otherwise would leave open an awkward gap in the set of boolean operators (as we do have `notEqual` and friends).

**Comment by greg-lunarg** [comment]
See this text in GLSL spec section 5.9 immediately after the section on &&, etc:

```
The logical unary operator not (!). It operates only on a Boolean expression and results in a
Boolean expression. To operate on a vector, use the built-in function not.
```

This text seems to imply that "Boolean expression" is not vector. While I understand your argument in terms of the whole spec, if we assume consistency within 5.9, it seems to suggest "Boolean expression" does not include vector when talking about  &&, etc.

The GLSL &&, etc operators are also different from the SPIR-V operators in that they are "short-circuiting" in the classic C language understanding. The SPIR-V operators are not "short-circuiting", so that works against the idea that there should be consistency between GLSL and SPIR-V for these operators.

The "short-circuiting" also starts to get strange when one tries to apply it to vectors. Maybe there is some programming model out there that attempts to do this, but I don't think GLSL is one of them.

I am quite certain the intent here is that && etc are meant to operate only on Boolean scalars. Any use or implementation of these on vectors would be quite unusual in the shader programming world.

As such, I will close this and will re-open if presented with evidence to the contrary.

**Comment by rdb** [comment]
@greg-lunarg Thank you for your clarification.  As-is the wording is quite ambiguous as in other places "Boolean" can refer to a vector and often (eg. for equality operators) there is specific wording limiting their operation to scalars.

I hadn't considered short-circuiting behaviour.  It appears that in HLSL, where the operation *does* apply to vectors, short-circuiting isn't supported, unlike in GLSL.  I checked Metal and it also defines && for vectors, but doesn't mention short-circuiting.

I think the argument that the current behaviour reflects the intention of the spec is sound.  I have filed KhronosGroup/GLSL#198 to clarify the spec wording.

**Comment by dneto0** [comment]
First, thanks for the thoughtful bug report.

> I hadn't considered short-circuiting behaviour. It appears that in HLSL, where the operation _does_ apply to vectors, short-circuiting isn't supported, unlike in GLSL. I checked Metal and it also defines && for vectors, but doesn't mention short-circuiting.

I believe "legacy" HLSL supports && and || for vectors, does not circuit, and computes answers component-wise.
But HLSL 2021 changed that.  
Now && and || are short-circuiting, and only operates on scalar bool.  Using them with vectors produces an error.  For the old behaviour, use new builtin functions `and`, `or` instead.
See https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021#logical-operation-short-circuiting-for-scalars

**Comment by greg-lunarg** [comment]
For those that want access to the SPIR-V, non-short-circuit vector capability through GLSL, one way might be to create a GLSL extension which adds and(), or() and xor() functions with this behavior.
