### ISSUE TITLE
Each number sign (#) can be preceded in its line only by spaces or horizontal tabs

### ISSUE THREAD

**Issue by HeXiaoZhi** [KhronosGroup/glslang#3155]
glcts.exe --deqp-case=KHR-GL45.shaders.preprocessor.basic.stringification_vertex
glcts.exe --deqp-case=KHR-GL45.shaders.preprocessor.basic.stringification_fragment
Following case need report error.
#define VEC4_STRING_PARAM(a, b, c, d) vec4(#a, #b, c, d)

According spec:
Each number sign (#) can be preceded in its line only by spaces or horizontal tabs. It may also be
followed by spaces and horizontal tabs, preceding the directive.

**Comment by arcady-lunarg** [comment]
This is something of a strange case, because glslang tends to report macro errors when the macro is expanded, rather than when it is defined. So attempting to actually use the macro VEC4_STRING_PARAM does result in the correct error message. Still, I can see the argument for having the error message come on macro definition in cases like this.

**Comment by HeXiaoZhi** [comment]
Has this issue been fixed

**Comment by arcady-lunarg** [comment]
Not yet, but we would be happy to accept patches for it. In this case, it would be a somewhat significant change to how the preprocessor reports errors in general.

**Comment by arcady-lunarg** [comment]
This was fixed by #3398
