### ISSUE TITLE
Thread safety issue in spirvbin_t (race condition in Parameterize function)

### ISSUE THREAD

**Issue by C0lumbo** [KhronosGroup/glslang#342]
The documentation (README-spirv-remap.txt) says: "It is safe to instantiate one spirvbin_t per thread and process a different SPIR-V in each."

However, spv::Parameterize(); is called at the start of spirvbin_t::remap. spv::Parameterize() uses the local static 'initialized' to avoid doing its initialization work multiple times, which is not a thread-safe approach. 

Calling spirvbin_t::remap on two threads at once leads to thread 1 proceeding past the 'initialized' check and doing the proper work of the Parameterize function. Meanwhile thread 2 sees that 'initialized' is now true and quickly exits the Parameterize function and proceeds to do the remapping work before thread 1 has completed initialization eventually leading to a "vector subscript out of range" assert.

Projects can work around this problem by calling spv::Parameterize before beginning any threaded spirvbin_t::remap work.

A fix could just be a modification of the documentation to inform users to call spv::Parameterize. Or the 'initialized' var could be protected by a mutex.

**Comment by mknejp** [comment]
> However, spv::Parameterize(); is called at the start of spirvbin_t::remap. spv::Parameterize() uses the local static 'initialized' to avoid doing its initialization work multiple times, which is not a thread-safe approach.
Since C++11 it is required that initialization of local static variables is thread-safe.

**Comment by C0lumbo** [comment]
Very interesting. I don't think it makes a difference in this case though. The issue would be the same if 'initialized' was a global var. There's nothing to stop a second thread doing remap work while a first thread is still doing the Parameterize work.

**Comment by ratchetfreak** [comment]
The test-then-set is still a race, in 2 ways

1. 2 (or more) threads can pass the if check before any of them set the static to true, leading to several threads filling the maps and thrashing on each other.

2. a thread coming in later while the first thread is still busy will attempt to use partially initialized maps.

To fix this you would need to lock over the entire initialization code:

``` C++
void Parameterize()
{
    static bool initialized = false;
    if (initialized) 
        return;
    auto g = lock_guard(&mutex);
    if (initialized) 
        return; //double check

    // do init

    initialized = true;
}
```

or just use std::call_once

void Parameterize()
{
    static std::once_flag flag;
    std::call_once(flag, [](){

        // do init

    }
}
```

**Comment by mknejp** [comment]
Hmm actually you're right. The easiest would be to just use a lambda for the side effects.
```cpp
void Parameterize()
{
  static const bool init = []
  {
    // do init
    return true;
  }();
  (void)init;
}
```

**Comment by johnkslang** [comment]
@steve-lunarg any preference here?

**Comment by steve-lunarg** [comment]
I like @ratchetfreak's option B, using std::call_once.  Want me to make the change?

**Comment by johnkslang** [comment]
I'm worried that doesn't work on some older systems.  Is there a more basic (older) way to do it?

Otherwise, yes, thanks.

**Comment by steve-lunarg** [comment]
There are probably N older (pre-c++11) ways to do it, but unfortunately I don't know of any single one that's available everywhere without introducing other weird dependencies we wouldn't want.  Maybe someone else knows of something suitable?  If so we can use that.  I recall having to use environment-specific code for threading and mutex features before c++11.

On one side of the coin, the spirv-remap tool is already using C++11 level features.  On the other, some compilers lag in supporting certain subsets, so the introduction of a dependency on <mutex> (which provides std::call_once and friends) plausibly could break some environments.  I think MSVC added <thread> and <mutex> features in Visual Studio 2012 or thereabouts.  I'd imagine g++ has had it since c++0x days.  What else?  Do we know the entire set of compilers in play?  (I'd imagine it to be a somewhat narrower set than for glslang in general).

One other potential issue: in g++, using threading features requires compiling with -pthread.

**Comment by johnkslang** [comment]
The remapper's recent use of C++11 all fit within MSVC 2010, but std::call_once() would not.  Lambda's work, so if the lambda solution works, that seems okay.

**Comment by mknejp** [comment]
I just realized "magic statics" feature (required for the lambda-only solution) is only supported since Visual Studio 2015.

**Comment by steve-lunarg** [comment]
Another option would be along the lines of this from @C0lumbo's initial report:

> Projects can work around this problem by calling spv::Parameterize before beginning any threaded spirvbin_t::remap work.

The initialization could be encapsulated and made an explicit part of the remapper library's interface, and the handling of it then up to any calling code, which would have to call a one-time init function before remapping.

It punts the problem to the caller, but has the benefit of not introducing anything that doesn't work in VS2010.

**Comment by baldurk** [comment]
FWIW the spirv remapper and SPVRemapper.cpp/.h already don't build at all on MSVC 2010, it's disabled due to [these code](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/SPVRemapper.h#L45-L49) [snippets](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/SPVRemapper.h#L76-L94):

```cpp
// MSVC defines __cplusplus as an older value, even when it supports almost all of 11.
// We handle that here by making our own symbol.
#if __cplusplus >= 201103L || _MSC_VER >= 1700
#   define use_cpp11 1
#endif

// ...

#if !defined (use_cpp11)
#include <stdio.h>

namespace spv {
class spirvbin_t : public spirvbin_base_t
{
public:
    spirvbin_t(int /*verbose = 0*/) { }

    void remap(std::vector<unsigned int>& /*spv*/, unsigned int /*opts = 0*/)
    {
        printf("Tool not compiled for C++11, which is required for SPIR-V remapping.\n");
        exit(5);
    }
};

} // namespace SPV
```

Where `_MSC_VER==1700` is VS2012.

I'm not sure how far the remapper is off from building on 2010 - if I force it to compile there are a load of errors. Some are simple syntactic sugar like range fors, but others are errors with lambda return values - I'm not familiar enough to know if it's an equally trivial fix, but AFAIK VS2010's support for lambdas is not complete.

I can't speak for any of the other guilty parties dragging the project down to VS2010 support (:wink:) but at least for my part I'm only interested in the core glslang library, I don't compile or use the remapper.

**Comment by steve-lunarg** [comment]
Interesting.  That really ought to have been something I was aware of, since I wrote the quoted lines of code :grinning: 

If it's come this far and nobody has needed both VS2010 and SPIR-V remapping at once, maybe it'd be acceptable to bite the bullet and use std::call_once?  It could be done in the remapper calling code in spirvbin_t::remap() to leave doc.cpp and other users of that unchanged.  There could be a compile time switch to avoid thread entanglements for environments that either can't support call_once, or just don't care about threads.

**Comment by steve-lunarg** [comment]
I'm going to make a proposed PR for people to review, although it might be a couple of days before I get to that.

I'm inclined to use an #ifdef protected std::call_once.  The default could be either way, but to prevent introducing new dependencies on current users, maybe thread safety should require the explicit request.

**Comment by steve-lunarg** [comment]
I've made some [WIP code](https://github.com/steve-lunarg/glslang/pull/1) to address this issue.  It's not a PR to the main glslang repo, but can become that once people have a chance to try it.  It's currently based on the WIP remapper testing branch.

Per requests, rather than using std::once(), this code fleshes out the *nix versions of the Init/Get/ReleaseGlobalLock wrappers in ossource.cpp using pthreads.  Init is called once from the command line spirv-remap.cpp.  There's a per-invocation Get/Release() around spv::Parameterize in SPVRemapper.cpp.  Arguably this could be part of spv::Parameterize itself, but this does introduce new link-time requirements, and I wasn't sure what other uses might be perturbed.  If there aren't any, it can be moved inside.

The CMakeLists creating spirv-remap accommodates adds a link dependency on the glslang OSDependent library that's providing the thread wrappers.  By default, the *nix ld linker makes a single forward link-time pass, which is insufficient here.  It can be asked to make multiple passes with -( and -), but I couldn't figure out how to do that through the CMake abstraction, so instead the libraries are listed twice to pick up circular dependencies.

I don't have the multi-threaded environments using the library interface that folks above are using.  Since this issue has existed since the beginning, I think we can leave this as WIP for a while to give people a chance to exercise it in those environments.
