### ISSUE TITLE
Glslang version output?

### ISSUE THREAD

**Issue by rubyFeedback** [KhronosGroup/glslang#3548]
So glslang version outputs:

11:14.1.0

Isn't the **11:** part wrong there? Usually we have a version output of the actual version. Not
sure why you guys prepend the "11:" - most other projects don't do that. Anyway, just
reporting this here because one of my scripts claimed that this was an error, but
of course this is debatable - I adjusted my script to drop any leading parts if a ':'
shows up, so for me this is settled. Best regards.

**Comment by arcady-lunarg** [comment]
The 11 is the SPIR-V generator version, the 14.1.0 is the version of glslang itself. In particular, the SPIR-V generator version refers to incompatibilities in the way SPIR-V is generated while the glslang version is more about the API/ABI of `libglslang.so` itself. It's been like this since fbe9a23baf2cb020fe3f80d68d972e2a97d9b954 in 2020.
