### ISSUE TITLE
glslangValidator Crashes when compiling this file to SPIR-V

### ISSUE THREAD

**Issue by subsurfacegames** [KhronosGroup/glslang#374]
This file causes it to crash every time. I did eventually get it to work with the crashes being seemingly random, but it will no longer crash if you comment out the if at the bottom. I know it's spelled wrong, but even if it's correct it still causes a crash. I think there might be some type of hidden character in there causing the crash or something like that. Because I re-typed it out and it all compiles just fine. 

Thought you guys might appreciate a file that causes a crash consistently. Hopefully you can find the issue. 
[frag.txt](https://github.com/KhronosGroup/glslang/files/353920/frag.txt)

**Comment by yavn** [comment]
Hi, thanks for your report!

Looks like there's a buffer overflow assertion in a function that builds the error message (`TParseContext::outputMessage` in ParseHelper.cpp). The crash is triggered by this line:

```
64:    if(UBO.Toggles1 != 0)
```

There's a syntax error and glslang tries to print the argument that is incorrect and crashes because UBO declaration is very long.

**Comment by johnkslang** [comment]
It's crashing in safe_vsprintf(), with a properly bound buffer size, firing on an assert "Buffer too small".

I guess it's safe but not crash-free.

**Comment by johnkslang** [comment]
BTW, the shader as provided has a "!=" on a misspelled member name, and as @yavn says, the type of the block for the member dereference is too long for the error handler.
