### ISSUE TITLE
Assertion on function call with combined sampler

### ISSUE THREAD

**Issue by ChrisGautier** [KhronosGroup/glslang#415]
The following shader causes glslangValidator -V to assert:

```
#version 310 es
precision highp float;

layout(set=0, binding=0) uniform mediump sampler s;
layout(set=0, binding=0) uniform mediump texture2D t2;
layout(location=0) in vec2 vTexCoord;
layout(location=0) out vec4 FragColor;

vec4 sample_texture(mediump sampler2D samp, vec2 uv) 
{
    return texture(samp, uv);
}

void main()
{
    FragColor = sample_texture(sampler2D(t2,s), vTexCoord);
}
```

```
% ./glslangValidator -V regression.frag
SPIRV/SpvBuilder.cpp:2216:spv::Id spv::Builder::accessChainGetLValue():
Assertion `accessChain.isRValue == false' failed.
```

This is a regression introduced by:
```
commit 76d0ac1a6f6f84f54d9e04e378da7823d69b3cc1
Author:     Jason Ekstrand <jason.ekstrand@intel.com>
AuthorDate: Wed May 25 11:50:21 2016 -0700
Commit:     Jason Ekstrand <jason.ekstrand@intel.com>
CommitDate: Wed May 25 13:49:47 2016 -0700

    SPV: Don't shadow sampler parameters when performing function calls
    
    Fixes #179
```

**Comment by johnkslang** [comment]
I think this is not supposed to work.  The SPIR-V specification says:

> All OpSampledImage instructions must be in the same block in which their Result <id> are consumed.  Result <id> from OpSampledImage instructions must not appear as operands to OpPhi instructions or OpSelect instructions, or any instructions other than the image lookup and query instructions specified to take an operand whose type is OpTypeSampledImage.

And GL_KHR_vulkan_glsl specification says, variously (admittedly weaker):

> The result of a sampler constructor cannot be assigned to a variable...
> 
> * there is no control flow construct (e.g., "?:") that consumes any sampler type
>
> Issue 9.  The spec currently does not restrict where sampler constructors can go...
>
> RESOLUTION (bug 14683): Only constructed at the point of use, where passed as an argument to a function parameter. [Implied as a built-in function, not a user function, for point of use.]

I think the functionality implied could be supported, as a new feature, if the following were done:

 - [ ] change SPIR-V to allow OpSampledImage is an argument in a function call
 - [ ] change GL_KHR_vulkan_glsl similarly
 - [ ] change glslang to take r-values for all sampler objects, instead of l-values

The latter is key in getting this to work, as a mix of handling r-values and l-values won't work.  It seems quite legitimate (other than being disallowed for samplers).  It would also be a new use of SPIR-V for back ends, so should be done cautiously.

If this is desired functionality, versus just a test failure, I recommend one of us open an issue for an enhancement request to the specification changes in https://github.com/KhronosGroup/SPIRV-Headers/issues.

**Comment by johnkslang** [comment]
Commit 1176530 prevents the assertion through better semantic checking, but does not add the functionality.  Leaving this issue open for discussion of new functionality.

**Comment by ChrisGautier** [comment]
Thanks for fixing the assertion. 

I personally do not request that such functionality is added. Having a clear error message is good enough in my opinion.

Independently of GL_KHR_vulkan_glsl, I think it would make sense to remove the restrictions on the uses of *OpSampledImage* in SPIR-V (speaking unilaterally, my backend would accept it). However, this should probably be done only if there is a clear demand for it from other people.
