### ISSUE TITLE
Need to track depth-less-than and depth-greater-than through stack.

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#489]
These "modes" are actually tagged to a depth variable declaration, and may need to see if that's used in the entry-point's call tree before knowing the mode the fragment shader is running in.

**Comment by dankbaker** [comment]
I don't believe it's necessary to track the whole call trace. I think a fairly simple change would work just fine.

1) Add EbvDepthLessThen and GreatherThen Enums

2) When looping through the output vars, IF we are the entrypoint function call the setmode() function as appropriate.

However, it does bring up another possible problem: SV values should be ignored on anything other then entry level functions. Right now I think they get processed if they are top level or not. This isn't exactly academic, since you can sometimes 'wrap' one shader entry point with an alternative one.

**Comment by johnkslang** [comment]
I was accidentally (?) concerned that a another function, not initially known to be in the call tree, could trigger the mode.  However, you'd claim the entry point is known, and all outputs are part of the entry-point signature and return value, so you know everything right there as far as setting the mode?

**Comment by johnkslang** [comment]
>  you can sometimes 'wrap' one shader entry point with an alternative one

But, is the case for any single compilation that the entry point is known, and there is no ambiguity?

It is illegal in SPIR-V for a function to be both an entry point and a target of a call.

**Comment by dankbaker** [comment]
> But, is the case for any single compilation that the entry point is known, and there is no ambiguity?

Yes & No. It's not possible to recursively call a function, however, there could definitely be another function in the module that calls that entrypoint, e.g. a new entrypoint you might target:

```

void func(out float Depth : SV_DEPTH)
{
   Depth = 0;
}

Buffer<float4> Position;

float4 main(uint Index : SV_VERTEXID) : SV_POSITION
{ 
    return Position.Load(Index);
}

float4 main2(uint Index : SV_VERTEXID) : SV_POSITION
{ 
    return main(0);
}
```

And this is pretty useful because it allows you to sort of overload and specialize a root shader. I think the right way to handle this for GLSLlang is to either ignore SV_ values if they aren't on the entrypoint function, or strip them if they arne't on the entrypoint function.

**Comment by johnkslang** [comment]
>Yes & No.

I'm hoping that means yes.  That we always know the entry point because we were told in side band information (e.g., command line) what it is.  (We don't see two decorated functions and then not know.) We know because it's the one declared.  Yes?

That is, in the example, only one of `main` and `main2` was declared as the entry point, so the other one is not. Yes?  Then, given that there is no recursion, if `main` is the entry point, then `main2` must be dead code.

>  I think the right way to handle this for GLSLlang is to either ignore SV_ values if they aren't on the entry point function, or strip them if they aren't on the entry point function.

Sounds like they should be dropped.  If `main2` is the entry point, then the decorations on `main` don't mean anything, and should not go into the AST.  Yes?

**Comment by dankbaker** [comment]
> I'm hoping that means yes. That we always know the entry point because we were told in side band information (e.g., command line) what it is. (We don't see two decorated functions and then not know.) We know because it's the one declared. Yes?

It's hard to have an apples to apples comparison. I noticed that SPIRV would include unused stuff in the module, which is pretty much impossible in HLSL so pragmatically it's not possible in HLSL because by definition unused functions are not included in the output module.

However, in the example given if glslang didn't compiled main but didn't remove the main2 and left it in the module and I'm assuming that would cause some confusion. main2 could still be left in the module if desired, but it would have to be compiled as not an entrypoint.

> Sounds like they should be dropped. If main2 is the entry point, then the decorations on main don't mean anything, and should not go into the AST. Yes?

Yes, only the entrypoint function would get SV decorations. Anything else they would just be ignored completely.

**Comment by johnkslang** [comment]
@dankbaker We either have an ambiguous entry point or we don't.  I'm not willing to believe that it is further ambiguous whether or not knowing the entry point is itself ambiguous.

> It's hard to have an apples to apples comparison.

I'm not comparing, I'm trying to find out whether we can count on knowing the name of the entry point when parsing the compilation unit.

> I noticed that glslang SPIRV would include unused stuff in the module, which is pretty much impossible in HLSL so pragmatically it's not possible in HLSL because by definition unused functions are not included in the output module.

Whether or not unused functions are present is not the same thing as whether or not we know which one is the entry point.  Why don't we know which one is the entry point?

>However, in the example given if glslang didn't compiled main but didn't remove the main2 and left it in the module and I'm assuming that would cause some confusion.

Why? Were we not told at compilation time what the entry point was? This question must have an answer.  Are you saying it's wrong to pass in the entry point name, and instead the tool chain should guess, and in your example it might guess wrong?

> main2 could still be left in the module if desired, but it would have to be compiled as not an entrypoint.

Right.  That's how it works.  If we are told `main` is the entry point, then `main` is the entry point, and not `main2` right?  Why is this unclear or ambiguous?  Because it was wrong to pass in the name of the entry point?  Is the whole design wrong?

**Comment by johnkslang** [comment]
Ah, I think the problem is that because there is something that *could* be a entry point, and *looks* like an entry point, you are considering it an entry point.

What I'm claiming (hoping) is all that matters is one compile at a time, HLSL compilation unit -> SPIR-V compilation unit, and for any single compile there is only one entry point, and we know up front what the name of the entry point is.  Is that true, and if not, which specific part of it is not true?  Thanks.

**Comment by dankbaker** [comment]
>Ah, I think the problem is that because there is something that could be a entry point, and looks like an entry point, you are considering it an entry point.

Yeah. It looks to me the way SPIRV is structured is you could have multiple entrypoints in the same _compiled_ module where in HLSL you can have multiple entrypoints in the same _source_ file but never in the same compiled module.  It looks like to me that in theory you could create a shader file in GLSLang that has multiple possible entrypoints and chose the entrypoint you want when the pipeline is created (at least that's what the API seems to indicate). In HLSL, a compiled module only contains one entrypoint so this situation is impossible.

It's actually a bit strange coming from HLSL because the expectation is you create a new module for each shader, via multiple invocations of the same source file with different entrypoints and profiles. I was going to suggest adding an option into the HLSL->SPRIV path that renamed the entrypoint function to "main" or some other string so that you don't have to propagate the entrypoint char* information through the engine pipe. I already modified our engine to prop that information, but there's really no reason to do since we know every module will contain only 1 entrypoint.

**Comment by johnkslang** [comment]
I'm just asking about the definition of HLSL compilation unit coming in, because you are coming from HLSL. My question is, how do we properly parse the HLSL coming in, and not about anything about it downstream: Do we know the entry point or not?  (Without any worry at all about SPIR-V, just on input, can we always count on knowing what the entry point is?)

>  since we know every module will contain only 1 entrypoint.

That's good progress toward my question.  Now, I only want assurance that which one it is will always be known. :)

SPIR-V is different, yes, but I only need to know the HLSL rule to know how to translate it correctly to SPIR-V.

It's a different discussion, but SPIR-V works by entry-point name, not by "main", and the stacks already operate by name.  If an HLSL entry point is named `flizbit`, then that will survive through the whole stack.  Also, SPIR-V gives you the choice to put multiple compilations of the high-level language into the same SPIR-V module or different SPIR-V modules.  But that's all background information, not to mention already working.  The question I'm trying to hear the answer to has nothing to do with SPIR-V, but is whether at HLSL parsing time can we the name of the one entry point.  Yes?  No?  Thanks.

**Comment by dankbaker** [comment]
> t's a different discussion, but SPIR-V works by entry-point name, not by "main", and the stacks already operate by name. If an HLSL entry point is named flizbit, then that will survive through the whole stack. Also, SPIR-V gives you the choice to put multiple compilations of the high-level language into the same SPIR-V module or different SPIR-V modules. But that's all background information, not to mention already working. The question I'm trying to hear the answer to has nothing to do with SPIR-V, but is whether at HLSL parsing time can we know the name of the one entry point. Yes? No? Thanks.

Sorry, it's confusing to me because it's actually a choice and it's wasn't clear which path you wanted to go.  Short answer is that you CAN know the entrypoint. That's the HLSL model. However, in that model, I wouldn't expect to see dead code functions laying around the SPIRV (e.g. unused entrypoints). Since I was seeing dead code, I wasn't sure that was the path that was desired.

However, seams to me we could also chose to allow multiple entrypoints on the same HLSL module instead, and then create the shader module once using the entrypoint specification on the pipeline creation. I think that would cause a few logistical issues, but seems like it is doable to me.

It sounds like the simpler option of knowing the entrypoint is the way to go. But certainly our engine can easily support the second one if it's the expected way for SPIRV to be used.

**Comment by johnkslang** [comment]
> you CAN know the entrypoint

Great, thanks.

>  allow multiple entrypoints on the same HLSL module instead

Without first doing some transforms, that would create the problem of an entry point calling an entry point, and likely more subtle semantic issues, etc.  I'm pretty sure the right way to do that is compile twice, once with each entry point being the right one, and then use a down stream SPIR-V merger that takes two SPIR-V modules and turns them into a single SPIR-V module.

Dead code, in general, shows up, as we are not currently using a DCE transform in the HLSL -> SPIR-V path, and that's orthogonal to whether or not the dead code could have been a candidate entry point in an alternate world (separate compile with different options).

So, now, putting the pieces together for this issue, if you could please directly correct where ever this line of reasoning goes astray:

- we know the one true entry point at parse time
- the only true inputs/outputs are declared as part of the entry point, not globals elsewhere, and not as part of some other function (even if that function looks like it could be an entry point a week from now, which I hope we don't have to discuss anymore)
- we ignore built-in semantics for non-entry-point in/out
- we add greater/lesser built-in variables
- when we special-case process the one-true-entry-point, we'll
  * set the depth mode based on the built-in variables we see
  * change those built-ins back to just being depth, having set the correct mode

Yes?  Or, line of reasoning goes wrong at step XXX?  Thanks.

**Comment by dankbaker** [comment]
Yes, that reasoning would work.

Alternatively, if you are already ignoring semantics on non entry point functions you could just set the mode and built in type when they are parsed safely. 

> I'm pretty sure the right way to do that is compile twice, once with each entry point being the right one, and then use a down stream SPIR-V merger that takes two SPIR-V modules and turns them into a single SPIR-V module

I don't think one way is more right then the other, it's just what is easiest to support and implement. Multi-entry point module compilation would certainly be useful in some cases, but it's an optional feature IMHO. Even if supported, I'd still expect a means of expliciting marking functions as entrypoints.

**Comment by johnkslang** [comment]
> Yes, that reasoning would work.

Okay, thanks.

> Alternatively, if you are already ignoring semantics on non entry point functions you could just set the mode and built in type when they are parsed safely.

The current place this is handled is after individual parameters are parsed.  (The "in entry point" bit isn't set until the whole signature is put together; the grammar recognizes that much before handing it over to semantics.)
