### ISSUE TITLE
Auto-assignment and reflection of buffer/texture numbers

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#499]
From @danginsburg, issue #463:

> I think there is going to be a bunch of reflection information we'll need to get back.
> 
> cbuffers/textures declared without register will need to be auto assigned by the parser and then queried afterwards. Most of our HLSL does not actually use registers at the moment, but instead queries D3D. We are going to need something resembling a subset of ID3D11ShaderReflection: (https://msdn.microsoft.com/en-us/library/windows/desktop/ff476590(v=vs.85).aspx) . I would need to go through our code to say exactly what subset of that we need.

This is a bit counter to Vulkan, which was avoiding all reflection, and instead having everything explicitly declared.  But, logging here for discussion/input.

**Comment by ratchetfreak** [comment]
at the very least have a way of specifying this from hlsl (possibly through a glslang-specific "extension")

**Comment by danginsburg** [comment]
The way our HLSL shaders are written, there are usually a massive overdeclaration of HLSL cbuffers and to some extent, textures.  This is because there are various files included that ultimately get dead code eliminated.  Even if we embedded special syntax in each of these declarations (which itself would be inconvenient, but maybe do-able), we still need a way to get reflection information back to know which were active.  glslang provides this information through its reflection interface and so does D3DX.  It's an essential piece that makes the whole thing work in our shader pipeline.  We will need something like that somewhere in the pipeline for HLSL -> SPIR-V.

**Comment by dankbaker** [comment]
We don't use reflection information from the GLSL path currently, but rather compile it first with D3D and get it that way.

The SPIRV looks like it has at least most of the relevant packing information in the output, however, I think it's just a matter of extracting it - or perhaps there is a little bit of meta information that is missing that needs to be provided.

**Comment by johnkslang** [comment]
Reflection is working for HLSL as well as GLSL now, and auto-assignment features for resources have been added some time ago.
