### ISSUE TITLE
What does register(c...) mean, and when on in/out, packoffset(c..) mean?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#500]
Currently, `packoffset(c...)` sets up offsets for buffers shared with the app.  

Input/output location numbers are being auto generated based on order of declaration in the entry point.

It seems one of the `register(c...` or `packoffset(c..` should also map input/output location numbers and components, when what is decorated is in input or output. To what extent does that exist?  Where all does `register(c...` have meaning, and what does it mean?

**Comment by dankbaker** [comment]
register keyword will not have any impact on output/input. This is based entirely on the cardinal order of the arguments, with a consistent packing policy, caveat being that SV semantics are ignored in the packing process since they don't get passed between shader stages. As long as the packing order is consistent for 2 shader stages (e.g. an input/output match up), it's fine.

**Comment by johnkslang** [comment]
Okay, this is basically how things are happening, closing.
