### ISSUE TITLE
`barrier` call is translated to SPIR-V incorrectly for GLSL 4.50

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/glslang#502]
GLSL 4.50 r6 states:

>  In order to achieve ordering with respect to reads and writes to shared variables, memory barriers must be employed using the `barrier()` function (see section 8.16 “Shader Invocation Control Functions”).

However, employing `barrier` in glslang results in an `OpControlBarrier` that applies [`spv::MemorySemanticsMaskNone` for its memory barrier](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp).

This behavior is apparently correct for ESSL 3.20 r4:

> In order to achieve ordering with respect to reads and writes to shared variables, a combination of control flow and memory barriers must be employed using the `barrier()` and `memoryBarrier()` functions (see section 8.15 “Shader Invocation Control Functions”).

But this is incorrect for GLSL 4.50.

This is apparently a new break, as [a commit resolved this at one point](https://github.com/KhronosGroup/glslang/commit/823fc656445946b805f46024a4499ee354b5824c). This commit [was undone, but incorrectly](https://github.com/KhronosGroup/glslang/commit/c51287d744fb6e7e9ccc09f6f8451e6c64b1dad6). The comment states that only TCS shader `barrier` calls should issue a memory barrier. But that is not the resolution from issue #205, which makes no statement about the behavior of `barrier` calls within _compute shaders_.

If the Khronos group has _changed_ the behavior of GLSL 4.50 in this regard, then something should probably be published on that. But otherwise, glslang ought to follow both the GLSL and ESSL wording, based on the profile being compiled for.

**Comment by johnkslang** [comment]
Yes, glslang should correctly implement the GLSL and ESSL wording.  However, the wording was contradictory (you could draw different conclusions from different places).  Hence this clarification from Khronos: https://github.com/KhronosGroup/glslang/issues/205#issuecomment-226066797.

Until the next ESSL and GLSL spec. updates are visible, this serves as notice that Khronos made the decision to fix the specifications to be consistent in this direction, rather than having contradictory statements.  (Maybe a public bugzilla did as well?)

Given all that is there a current issue?  Is glslang contradicting the newly clarified behavior (which is the same for ESSL, GLSL, and SPIR-V).

**Comment by NicolBolas** [comment]
But what is the "newly clarified behavior"? The comment says:

> Khronos has decided that everything should converge towards control barriers in the tessellation control stage also synchronizing memory outputs. SPIR-V 1.1 might revisit this, but for the current versions of ESSL, GLSL, and SPIR-V, an extra memory barrier is not needed, as it is built into the meaning of barrier().

So for a TCS `barrier` call, `out` declared variables do not need synchronization. But what does that mean about `shared` variables in a *compute* shader?

**Comment by johnkslang** [comment]
I don't believe there is any contradictory language about the compute stage's behavior for `barrier()`, and that glslang currently correctly implements `barrier()`.

It is the responsibility of the consumer of the SPIR-V to correctly implement all the semantics of `barrier()` for the stage in which it is issued.  For TSC, that includes the memory synchronization of outputs, but not for compute shaders.

**Comment by NicolBolas** [comment]
> I don't believe there is any contradictory language about the compute stage's behavior for barrier(), and that glslang currently correctly implements barrier().

I posted two quotes, one from GLSL and one from ESSL, which describe contradictory behavior for the compute stage's `barrier` call. GLSL 4.50 r6 makes it clear that `barrier` is supposed to be sufficient to "achieve ordering with respect to reads and writes to shared variables".

Whereas ESSL explicitly says that you must use an appropriate `memoryBarrier` calls if you want visibility of `shared` objects, in tandem with `barrier`.

They cannot both be true. Hence the contradiction.

And the clarified wording from #205 *only mentions TCS invocations*. It does nothing to clear up the contradiction surrounding `shared` variables in compute shaders.

**Comment by NicolBolas** [comment]
It should be noted that GLSL 4.60 also leaves the wording intact.

**Comment by johnkslang** [comment]
Both ESSL (rev. 5 of 3.20) and GLSL (rev. 6 of 4.60) now say the same thing:

> In order to achieve ordering with respect to reads and writes to **shared**
variables, control flow barriers must be employed using the **barrier**() function

Glslang translates this to:

- for tessellation control without the new Vulkan memory model, an `OpControlBarrier` with `Workgroup` execution scope and `Invocation` memory scope, and no memory semantics (and the SPIR-V spec. says this "...also implicitly synchronizes the **Output**..." for this case)
- otherwise, `OpControlBarrier` with `Workgroup` execution scope and `Workgroup` memory scope, and memory semantics of
  * `OutputMemoryKHR` and `MemorySemanticsAcquireRelease` for tessellation control
  * `MemorySemanticsWorkgroupMemory` and `MemorySemanticsAcquireRelease` for other stages
