### ISSUE TITLE
Linkage objects listed in indeterminate order

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#594]
On Linux the hlsl.rw.register.frag test fails (sometimes?) because the "Color" object is listed in a different order compared to other objects.  

Example failing public bot:
https://travis-ci.org/KhronosGroup/glslang/jobs/175757615

Here's an excerpt from the diff:
```
 0:?   Linker Objects
+0:?     'Color' (layout(location=0 ) out 4-component vector of float)
 0:?     'g_tTex1df1' (layout(binding=2 r32f ) uniform image1D)
 0:?     'g_tBuf1du1' (layout(binding=3 r32ui ) uniform uimageBuffer)
-0:?     'Color' (layout(location=0 ) out 4-component vector of float)
```

**Comment by johnkslang** [comment]
I see the same diff on Windows. The base case is incorrect, because of parallel development.  d3f1122a4430563cd47f60060956e88dc559ba22 changed the order, but this test didn't exist until a later commit that was recently merged.

An example of clean merges plus full testing still incorrectly allowing changes.

I'll push the corrected test result.

**Comment by johnkslang** [comment]
This appears fixed, even though the OS X build isn't starting.  All other tests are passing with the same results between Windows and Linux.

BTW, the logic putting things on the list is deterministic; there isn't a way for the order to vary.

**Comment by dneto0** [comment]
Ah.  Makes sense.  I had tracked down the original logic and couldn't see why the diff was different, so I filed the bug.  Thanks for the thorough explanation.
