### ISSUE TITLE
Adding a custom Decoration with a different syntax

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#622]
Hi.
Regarding the Decorate operation, is it possible to define a different OperandClass depending on the decorationId?
For now, all Decorate operations syntaxes are defined as:
OperandId OperandDecoration **OperandVariableLiterals**

As written in Doc.cpp
`   InstructionDesc[OpDecorate].operands.push(OperandId, "'Target'");
    InstructionDesc[OpDecorate].operands.push(OperandDecoration, "");
    InstructionDesc[OpDecorate].operands.push(OperandVariableLiterals, "See <<Decoration,'Decoration'>>.");`

However I'd like to create a custom decorationId having  a different syntax:
OperandId OperandDecoration **OperandOptionalLiteralString**

For now I can hardcode it in the code, and check for this new decorationId when dissasembling the decoration bytecode, but I'd like to ask if there is any better way to do this?

**Comment by johnkslang** [comment]
First, if we are discussing SPIR-V syntax, we need to use the specification. Doc.cpp is arbitrary and could go away at some point; it was a placeholder until a real disassembler showed up, which we have now in SPIR-V tools. The point is, something like OperandVariableLiterals is an arbitrary side-implementation detail, not the definition of SPIR-V, and so not a proper foundation to discuss SPIR-V changes on.

Second, there is still a SPIR-V principle that the type of operands is known from the opcode, so you might be wanting a new opcode. In fact, you can extend SPIR-V that way if you want, but of course discussing here is good to get better input and alignment on what to do.

About solving the problem, my first questions would be is this debug only? Or, for reflection? E.g., is there something you can do with OpName and syntax inside that string? There are efforts to greatly increase debug support; hearing more about what you are trying to accomplish will help.

**Comment by Joojooo** [comment]
Thanks for your answer. No problem about Doc.cpp being arbitrary, I understand that the project is under active development and so not everything is definitive or complete. On my side I'm discovering glsland and SPIRV, so any advices I get from you is always very valuable.
What we're trying to accomplish is to convert our hlsl-based shaders into an extended version of SPIR-V. Extended because our converted shaders won't be complete and we will need another pass to merge all bytecode shaders together later on. So I like to add some additional data and properties into our bytecode. 
I was indeed considering using OpName to add some of those properties (it would work as well), but it looks like OpName is for Debug only (we're not necessary in debug).
According to the specs, OpDecorate can have different kind of literal depending on the Decoration, and so looked like a good candidate to resolve my problem. I just need to add a new DecorationId and change the operand accordingly. Or as you said I can also add a new opcode for this purpose. I think both solutions would be identical.

**Comment by johnkslang** [comment]
Okay, also consider the existing power of glslang to link partial ASTs together.  Repeating from the other issue:

Another key point here is that glslang has an AST linker in it. Glslang is already architected to take in multiple partial-stage compilation units for a single stage (single entry point). These partial stages are first independently compiled into partial ASTs, and then the linker part of glslang merges the multiple ASTs together (the whole "TIntermediate" actually) into a single one. The single one represents a complete call graph for an entry point, which can then be translated to valid SPIR-V, dropping anything not needed by the complete call graph rooted by the entry point.

The point of this goes hand in hand with not needing to have partial SPIR-V files merged to make a single stage; it would be handled by the front end, not by SPIR-V tools. (The SPIR-V merging we do want is independent complete, not partial, SPIR-V modules merged into a single SPIR-V module with multiple entry points.)

So, it sounds like some of the trouble here comes from wanting to solve the "merge partial results" problem at the SPIR-V level instead of the AST level.

**Comment by Joojooo** [comment]
Thanks again for your answers and for clarifying this features of glslang. I haven't looked into glslang linking possibilities yet, but I will definitely investigate and consider this when designing our partial AST.
