### ISSUE TITLE
Specialization constant expressions and ternary operator

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/glslang#649]
Let's have layout (constant_id = 0) const int POINT_LIGHT_COUNT = 0. Since zero sized arrays are rejected by glslangvalidator, I worked around this by using POINT_LIGHT_COUNT > 0 ? POINT_LIGHT_COUNT : 1 as array size for a varying. Unfortunately this is not allowed by GL_KHR_vulkan_glsl.txt, ternary operator simply is not listed as allowed operator for specialization constant expressions. This feels strange, because I can still use int(POINT_LIGHT_COUNT > 0) * POINT_LIGHT_COUNT + int(POINT_LIGHT_COUNT <= 0) * 1 as array size. So perhaps ternary operator should also be allowed?

**Comment by johnkslang** [comment]
This sounds like a couple of issues.

1. Array sizes:  Can you make the default size of your array be `1` instead of `0`? Indeed, nothing in the stack tolerates 0-sized arrays. The `= 0` is just the default specialization constant, until the desired value is supplied, so is there any harm in it being `1` instead of `0`?

2. Ternary operator: Specification with specialization constants. If this is an issue, it is better discussed with specification issue, like https://github.com/KhronosGroup/SPIRV-Headers/issues for SPIR-V (but SPIR-V allows `OpSelect` as a specialization-constant operation) and https://github.com/KhronosGroup/Vulkan-Docs/issues for Vulkan, where I think it may be appropriate to request an enhancement for this, if needed.

**Comment by johnkslang** [comment]
This has been resolved in https://github.com/KhronosGroup/Vulkan-Docs/issues/424.

It is implemented in the emit-OpSelect branch, which will soon merge into master.

**Comment by johnkslang** [comment]
This work is complete now. Specialization constants work with GLSL :? which then generate OpSelect in SPIR-V.
