### ISSUE TITLE
Why do push_constant blocks require an instance name?

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glslang#665]
GL_KHR_vulkan_glsl states

"A block declared with layout(push_constant) must have an /instance-name/ supplied, or a compile-time error results."

However, there is no reason given as to why an instance name is required. Regular uniform buffers do not require an instance name.

Because push constant blocks do require an instance name, it is more work to convert an OpenGL shader to a Vulkan shader. You can't just place your OpenGL uniforms in a Vulkan push contant block. You now also have to go through your shader code and pre-append the push constant instance name to each usage of the original OpenGL uniform.

If there is a solid reason for requiring an instance name, then it should be documented in GL_KHR_vulkan_glsl. If there is no good reason, then it's just an annoyance.

**Comment by johnkslang** [comment]
It may be a good enhancement request for GL_KHR_vulkan_glsl, which needs to be made at https://github.com/KhronosGroup/Vulkan-Docs. I aim to keep glslang conformant to that spec.

For the most part, the specifications focus on how to express something, not rationale for why to express it. I can say one reason the anonymity of some blocks was added was backward compatibility to before the blocks existed, and it was considered safer to not introduce anonymous access features when not otherwise needed. But, if there are requests to do this, and it works in the language, it may be worth filing an issue for it.

**Comment by johnkslang** [comment]
Commit 33f85b6e5908c23d6836f776cb42b0a237b90289 adds this functionality (see https://github.com/KhronosGroup/Vulkan-Docs/issues/428).
