### ISSUE TITLE
Add ability to conditionally disable HLSL code compilation

### ISSUE THREAD

**Issue by slime73** [KhronosGroup/glslang#666]
The code in glslang which provides HLSL support adds a decent amount to the compiled binary size of glslang – it would be handy to be able to prevent HLSL support from being compiled in, for cases where binary size is a factor and HLSL input support is unneeded.

**Comment by sergeyreznik** [comment]
@johnkslang Suddenly my code stopped working :)
**ENABLE_HLSL** is not quite proper define for this feature request. By default it should work, and must be conditionally disabled with define like **GLSLANG_DISABLE_HLSL_SUPPORT**

**Comment by sergeyreznik** [comment]
@johnkslang I'm using glslang not as a separate library, but compiling it from sources inside my project (I'm aware this is not quite proper way, but I don't have build system now to use it as a separate project). And ENABLE_HLSL is not defined anywhere for me. 
Also there is a crash inside **InitializeSymbolTables** (ShaderLang.cpp, line 297) when ENABLE_HLSL is not defined. Caused by `unique_ptr<TBuiltInParseables> builtInParseables` to be nullptr and then unconditional call to
`builtInParseables->initialize(version, profile, spvVersion);`

**Comment by johnkslang** [comment]
Is it possible to externally define `ENABLE_HLSL`, or add to your code?

Apologies for driving it that direction instead of disable, but there are other things that must be enabled, and it seemed to better to request what was needed rather than the other way. Can reverse that decision if it's really not the right way to do it.

**Comment by slime73** [comment]
> ENABLE_HLSL is not quite proper define for this feature request.

There was discussion on the PR about this (not sure if you saw or not): https://github.com/KhronosGroup/glslang/pull/668

> Also there is a crash inside InitializeSymbolTables (ShaderLang.cpp, line 297) when ENABLE_HLSL is not defined.

This crash will also happen if the `source` parameter is set to EShSourceNone, although I don't believe a codepath does that currently. So I think the crash will only happen if you compile glslang without HLSL support and then try to use it with HLSL.

**Comment by johnkslang** [comment]
Commit 65d538c832670e1a0a0da469ceb345c3e9622ada is more robust against the `source` parameter.

However, trying with HLSL disabled, something still tries to bring in the non-built hlsl.lib.  Looking at that.

**Comment by johnkslang** [comment]
Commit dc1a8196cf4e717af8b1e64cf82ca3d13e4dd2d8 makes the normal build work with `ENABLE_HLSL` set to off.

**Comment by slime73** [comment]
Ah, sorry about that. I should have tested the tests!

**Comment by sergeyreznik** [comment]
@johnkslang @slime73 
I think conditionally enabling functionality is not a best idea. By default library should provide all features and option to disable unused ones. Consider situation when new functionality will be added, but no one will know about it unless preprocessor macro is not defined. I don't think this is a good idea to have a lot of functonality disabled by default.
Regarding naming - it would be better to start defines with GLSLANG_, because "ENABLE_HLSL" could be defined is somebody's project and have completely other meaning, while GLSLANG_ENABLE_HLSL would keep from potential errors.

**Comment by johnkslang** [comment]
@sergeyreznik Generally agreed, but this has been stable this way now, and I don't want to keep changing it out from under folks.  (Unless there are lots of folks asking to change it anyway.)

Future macros should start GLSLANG_ .
