### ISSUE TITLE
GLSL: MatrixStride for smaller than 3x3 matrices

### ISSUE THREAD

**Issue by huhtanen** [KhronosGroup/glslang#680]
SPIR-V 1.1 specification says following:
"The MatrixStride on a RowMajor (ColMajor) matrix must be padded to hold a row (column) of 4 components, when the matrix only has 3 columns (rows). In all other uses of MatrixStride, no padding is allowed."

It seems that glslangValidator still pads all rows (columns) to 4 components regardless of the size of the matrix. E.g., following:

```
uniform test
{
    mat2x2 colmajor_2x2;
};
```

results in:

```
MemberName 9(test) 0 "colmajor_2x2"
MemberDecorate 9(test) 0 ColMajor
MemberDecorate 9(test) 0 Offset 0
MemberDecorate 9(test) 0 MatrixStride 16
```

I would have expected the MatrixStride decoration to be 8, not 16. Two 32-bit floats should fit to 8 bytes since spec is prohibiting padding in this case, if I read the spec correctly.

EDIT: This is the result with the latest LunarG Vulkan SDK 1.0.37 on Windows when using glslangValidator with the -H option.

**Comment by johnkslang** [comment]
If this is declared as `buffer` instead of `uniform` it would get a stride of 8 instead of 16.

History: Basically, `buffer` and `uniform` correspond to the OpenGL `std430` and `std140` rules, respectively.  `std140` says array elements must be rounded up to a multiple of 16, while `std430` skips that step. That is what glslang implements.

Agreed this is inconsistent with how SPIR-V reads regarding no padding, for the `uniform` case:


> The MatrixStride on a RowMajor (ColMajor) matrix must be padded to hold a row (column) of 4 components, when the matrix only has 3 columns (rows). In all other uses of MatrixStride, no padding is allowed.

However, the Vulkan-specific language allows padding:

>... MatrixStride decoration must be an integer multiple of the base alignment ...

I'll take this up with Khronos.

**Comment by johnkslang** [comment]
Answer: The Vulkan statement is correct, and the SPIR-V "no padding" statement is not. Glslang should continue to generate offsets per `std140` and `std430`, as that's what content for GLSL expects, and at the same time it is legal according to Vulkan to store a 2x2 matrix in a single vector slot.
