### ISSUE TITLE
Can't use the default $Global block built from loose uniforms until function entry

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#743]
Glslang builds up a list of loose uniforms, and then on entry to the first function builds the default $Global block out of it. This was a quick functionality hole plugging that has two problems:

1. members declared between functions were not put in the block on entry to the first function
2. members are not available for access until entry to the first function

A different design is needed to apparently real-time edit the global block as it is built up.

**Comment by alenl** [comment]
+1

**Comment by alenl** [comment]
This is very important to us in order to be able to benchmark HLSL vs GLSL. We're seeing unusual performance numbers regarding fill rate/pixels shader throughput on GL/Vulkan vs DX9/11, and we want to check one shading language against another in same API. Lack of this feature is currently preventing us from using HLSL in Vulkan.

**Comment by johnkslang** [comment]
Thanks for the input. I'm planning to get to this one in the next few days. It's not quite trivial.

**Comment by johnkslang** [comment]
This is addressed by 000c818efb6bf208b27eb22d6f3f20a18007c85d.
