### ISSUE TITLE
SPV: Unexpected NV declarations in geometry shader

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/glslang#790]
Generating the SPIR-V for the following geometry shader:

```cpp
#version 450

#extension GL_ARB_viewport_array : enable

layout (triangles, invocations = 2) in;
layout (triangle_strip, max_vertices = 3) out;

layout (binding = 0) uniform UBO {
	mat4 projection[2];
	mat4 modelview[2];
	vec4 lightPos;
} ubo;

layout (location = 0) in vec3 inNormal[];
layout (location = 1) in vec3 inColor[];

layout (location = 0) out vec3 outNormal;
layout (location = 1) out vec3 outColor;
layout (location = 2) out vec3 outViewVec;
layout (location = 3) out vec3 outLightVec;

void main(void)
{	
	for(int i = 0; i < gl_in.length(); i++)
	{
		//...
	}
	EndPrimitive();
}
```

Will always add the following NV members and decorations:

```cpp 
MemberName 46(gl_PerVertex) 4  "gl_SecondaryPositionNV"
MemberName 46(gl_PerVertex) 5  "gl_PositionPerViewNV"

MemberDecorate 46(gl_PerVertex) 4 BuiltIn SecondaryPositionNV
MemberDecorate 46(gl_PerVertex) 5 BuiltIn PositionPerViewNV
```

Even though I have none of the NV specific geometry shader extensions enabled. 

This will result in validation layer errors like these:
```ERROR: [SC] Code 5 : SPIR-V module not valid: Invalid built-in operand: 5257```

This seems to be connected to #776 

glslangvalidator is build from current master.

**Comment by johnkslang** [comment]
Several scattered notes here:

- Looks like #776 removed the capability, but not the members.
- If the validator knew about all extensions, it wouldn't complain about not knowing that built-in operand, so validation would pass. (@dneto sanity check?)
- If you don't want Nvidia extensions, you could build without enabling NV_EXTENSIONS.
- Does this work if you skip validation? I see the implementation difficulty for Nvidia here, and wondering how harmful it is to declare members, but leave out the capability, much as we do for clip and cull distance,  which also are not supported here.

**Comment by johnkslang** [comment]
Sorry, I corrected @dneto to @dneto0 is the previous commented.

**Comment by SaschaWillems** [comment]
> Does this work if you skip validation?

Yes, just checked on a completely different platform (Intel IGP on Ubuntu) and the example works fine there, so this seems to be a pure validation layer related issue. I guess it would be a good idea to change the validation layer error then and at least include the extension that the op refers to and a note that this may not be relevant (and maybe change this to a warning instead). Will discuss that over at the validation layers repo.

**Comment by dneto0** [comment]
Summary:
 - that report is from a validator other than the one in SPIRV-Tools
 - the generated code is truly invalid in two ways.  (I think it *is* harmful to include those extra members)
 - the SPIRV-Tools validator message is a bit more helpful, but could be improved

---

@SaschaWillems: Can you confirm the validation error is coming from a Vulkan layer?  The message you see is different from SPIRV-Tools validator.

The top-of-tree SPIRV-Tools validator rejects the module with this message:

error: 54: Operand 4 of MemberDecorate requires one of these capabilities: ShaderStereoViewNV 

Indeed, disassembly shows:
```
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpMemberDecorate %gl_PerVertex 4 BuiltIn SecondaryPositionNV
               OpMemberDecorate %gl_PerVertex 5 BuiltIn PositionPerViewNV
```
The module only declares Geometry capability.  Also, it does not declare any extensions.
So the module fails validation in two ways (missing capability, and missing extension).  That seems like a glslang code generation bug.

Regarding the helpfulness of the message from the SPIRV-Tools validator:
- at least it named the missing capability
- it's really unfriendly to just say operand 4 instead of actually naming the operand enum value.  That should be improved
- the "54" is the 1-based number of the instruction.  It says the 54th instruction is bad.   You should be able to find that in a disassembly.  (I've always been torn about how to report position in the SPIR-V binary.  An alternative is to report the word offset into the module.)

**Comment by dneto0** [comment]
I filed an enhancement request to the SPIRV-Tools validator so this message will print the name of the offending enum https://github.com/KhronosGroup/SPIRV-Tools/projects/1#card-2202881

**Comment by Plagman** [comment]
How do we make sure this never, ever happens again for the glslang that ends up in an SDK? Could glslang have tests that run when new changes are merged, that would compile a couple of shaders and sanity check the output?

**Comment by johnkslang** [comment]
I view the contract of putting a longer-living snapshot of a tool into an SDK as being that the SDK maker tested it well enough to justify requesting people use that specific copy over time.

For GitHub, here, we learned our lesson that just because vendor-specific code is under a vendor-specific #ifdef, does not mean it is subject to lower quality threshold (unless people want to go back to having NV_EXTENSIONS etc. off by default).  So, let's try with closer scrutiny of vendor-specific code and see how that goes.

Do some vendors still need the removal of the extra members, even with the capabilities gone?

**Comment by johnkslang** [comment]
Another thing to do: I've already mentioned now treating vendor-specific code in vendor-specific #ifdef just like any other kind (not with lower standards). In addition, we should have PRs that include such code available for a few days for vendors to try.  (That changes the Khronos process of this stuff instantly showing up like it did last time.)

**Comment by dneto0** [comment]
> Do some vendors still need the removal of the extra members, even with the capabilities gone?

I think it would be a bad move to permit the extra members to remain.  I know that for ClipDistance and CullDistance we negotiated a rule that "if you don't *access* that member then you don't need the capability".  But I don't want to go that route for vendor extensions.  In short, I'm asserting that the validators are correctly rejecting these modules.

> How do we make sure this never, ever happens again for the glslang build ...

I have to mention it:  We could add the an *option* to run the glslang test suite with SPIRV-Tools validation turned on.  That can gate acceptance into an SDK, by choice of the SDK maintainer.  But that also couples development of glslang with SPIRV-Tools (and transitively to SPIRV-Headers).
It puts heavier pressure on early development of those dependencies.  That might be a good thing.

I don't advocate passing SPIRV-Tools validation is a *default* gating criterion for glslang development.

There is precedent.  I make sure to regularly run all shaders from the Vulkan CTS through the SPIRV-Tools validator.  But that flow is *optional*: Others don't have to run it. It also helps to ensure that the SPIRV-Tools validator has one-sided error: all valid modules will pass validation.

**Comment by johnkslang** [comment]
@dneto0 I'm unclear this works with vendor-specific extensions unless either

- the validator accepts input for extensions it doesn't understand without giving errors (just warnings), or
- vendor-specific extensions have to be in the validator before they are in glslang

Is there a third way, or which way are you advocating?

**Comment by dneto0** [comment]
More like option 2 than option 1.

A possibility is:
- Acceptance of a change into glslang is the same as today.  It does not require that glslang SPIR-V outputs pass SPIRV-Tools validation.
- Add a *non-default* option to enable failure of glslang tests when SPIR-V validation fails.

Who runs tests in the second mode?
- You could, periodically, for your interest
- I would, periodically.  Similar to how I cross check the validator against Vulkan CTS.
- A downstream consumer making an SDK.

To keep development lightweight, even *compilation* of SPIRV-Tools and SPIRV-Headers could be conditional.

**Comment by johnkslang** [comment]
FYI, I'm looking at making a code change for this that only includes these members in the interface if the extension was enabled.

**Comment by johnkslang** [comment]
Here's what I come up with as all that has to get fixed. Please let me know if there is more, or this is incorrect:

- gl_SecondaryPositionNV should only be present if GL_NV_stereo_view_rendering is enabled
- gl_PositionPerViewNV should only be present if GL_NVX_multiview_per_view_attributes is enabled

**Comment by johnkslang** [comment]
BTW, this problem could only be triggered if the version was #450 and the built-in interface blocks were not redeclared.

**Comment by SaschaWillems** [comment]
Thx for this quick fix 👍 

I can confirm that this works now as expected, and the NV built-ins are no longer compiled into SPIR-V when not requested. 

Btw. I've had one user reporting a driver crash due to this behavior (see [this comment](https://github.com/SaschaWillems/Vulkan/issues/307#issuecomment-288516254)], oddly enough with an NVIDIA card.
