### ISSUE TITLE
HLSL: Type resource declarations SPIR-V issues

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#872]
Not sure if this belongs here, but I'll go ahead and put it here and someone can tell me no :)

The typed resource form of declaration is producing decorators in the SPIR-V that's causing VkCreateGraphicsPipeline to fail on NVIDIA card:
````c++
struct UniformsT {
  float3 color;
};
ConstantBuffer<UniformsT> uniforms : register(b0);
````

Generated SPIR-V:
````asm
                              Name 36  "uniforms"
                              // ...
                              Decorate 36(uniforms) DescriptorSet 0
                              Decorate 36(uniforms) Binding 0
                              // ...
    36(uniforms):     35(ptr) Variable Uniform
````
Whatever the NVIDIA driver is doing seems to not like that form of the declaration. However, this version of the declaration is OK:
````c++
cbuffer uniforms : register(b0) {
  float3 color;
};
````
...and the SPIR-V:
````asm
                              Name 36  ""
                              // ...
                              Decorate 36 DescriptorSet 0
                              Decorate 36 Binding 0
                              // ...
              36:     35(ptr) Variable Uniform
````
A similar (if not the same thing) is happening for ```StructuredBuffer<T>``` and ```RWStructuredBuffer<T>``` as well.

Full source of shader I'm using:
````c++
struct VSOutput {
  float4 Position : SV_POSITION;
  float3 Color : COLOR;
};

struct UniformsT {
  float3 color;
};

//ConstantBuffer<UniformsT> uniforms : register(b0);

cbuffer uniforms : register(b0) {
  float3 color;
};

VSOutput VSMain(float4 Position : POSITION) {
  VSOutput result;
  result.Position = Position;
  //result.Color = uniforms.color;
  result.Color = color;
  return result;
}

float4 PSMain(VSOutput input) : SV_TARGET {
  return float4(input.Color, 1);
}
````

As a note, this form of declaration is not accepted by the D3D12 shader compiler, but is accepted by glslang:
````C++
cbuffer uniforms : register(b0) {
  float3 color;
} uniforms ;
````

**UPDATED**: includes usage of color

**Comment by steve-lunarg** [comment]
Hi @chaoticbob,

If there's something broken with ConstantBuffer<T> I can look into that.  However, I don't understand what the trouble is quite yet.  I tried running the shader above through spirv-val, and it validated successfully (which doesn't imply there's no bug, because it could be a problem the validator does not detect).  I also modified it to add the commented out ConstantBuffer declaration (L10) and use (L19) back, and also that validated OK.

One difference is that the ConstantBuffer<T> syntax creates named blocks using the declared variable name, and uses the *blockname.member* syntax, while cbuffer creates anonymous blocks where the members are available in the global namespace.  However I think the first method should be valid in SPIR-V in general.  The difference is visible in the linkage output with the "-q" option:

`0:?     'uniforms' (layout( binding=0 row_major std140) uniform block{layout( row_major std140) uniform 3-component vector of float color})`

As opposed to the cbuffer case:

`0:?     'anon@0' (layout( binding=0 row_major std140) uniform block{layout( row_major std140) uniform 3-component vector of float color})`

**Comment by chaoticbob** [comment]
Hey @steve-lunarg,

I'm using the drivers from a week ago. I had shared this with NVIDIA, in waiting mode now. I unfortun forately do not have an AMD or Intel card to try this on for the next couple of weeks. I'm still poking at the problem to see if I can find any other clues out. Seems like just the mere presence of the decoration cause vkCreateGraphicsPipeline to crash. I don't know enough about SPIR-V to make any reasonable guesses on it. 

The full source for the sample programs are here: [](https://github.com/chaoticbob/tinyrenderers). It's Windows only right now and requires GLFW.

**Comment by chaoticbob** [comment]
Latest NVIDIA drivers seems to have resolved this issue.
