### ISSUE TITLE
HLSL: IO remapper creates aliases for unused UAVs counter buffers

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#914]
```
AppendStructuredBuffer<uint> Buf1 : register(u0);
AppendStructuredBuffer<uint> Buf2 : register(u1);
AppendStructuredBuffer<uint> Buf3 : register(u0);

float4 main() : SV_Target
{
	Buf1.Append(10u);
	Buf2.Append(20u);
	return float4(1.0, 3.0, 5.0, 1.0);
}
```

with command
```
/git/glslang/StandAlone/glslangValidator -D -H -V -o /tmp/test.spv /tmp/test.frag -e main --auto-map-bindings --shift-ssbo-bindings 83
```

gives odd aliasing with the counter buffers
```
                              MemberDecorate 13(Buf1) 0 Offset 0
                              Decorate 13(Buf1) BufferBlock
                              Decorate 15(Buf1) DescriptorSet 0
                              Decorate 15(Buf1) Binding 83
                              MemberDecorate 18(Buf1@count) 0 Offset 0
                              Decorate 18(Buf1@count) BufferBlock
                              Decorate 20(Buf1@count) DescriptorSet 0
                              Decorate 20(Buf1@count) Binding 84
                              Decorate 30(Buf2) DescriptorSet 0
                              Decorate 30(Buf2) Binding 84
                              Decorate 31(Buf2@count) DescriptorSet 0
                              Decorate 31(Buf2@count) Binding 84
                              Decorate 43(@entryPointOutput) Location 0
                              Decorate 45(Buf3) DescriptorSet 0
                              Decorate 45(Buf3) Binding 83
```

If I remove Buf3 it seems to work.

I over-rode validateBinding to allow aliasing
```
diff --git a/glslang/MachineIndependent/iomapper.cpp b/glslang/MachineIndependent/iomapper.cpp
index 26772ddc..034ff393 100644
--- a/glslang/MachineIndependent/iomapper.cpp
+++ b/glslang/MachineIndependent/iomapper.cpp
@@ -468,6 +468,7 @@ struct TDefaultIoResolver : public TDefaultIoResolverBase
 {
     bool validateBinding(EShLanguage /*stage*/, const char* /*name*/, const glslang::TType& type, bool /*is_live*/) override
     {
+               return true;
         if (type.getQualifier().hasBinding()) {
             const int set = getLayoutSet(type);
 
@@ -588,6 +589,7 @@ struct TDefaultHlslIoResolver : public TDefaultIoResolverBase
 {
     bool validateBinding(EShLanguage /*stage*/, const char* /*name*/, const glslang::TType& type, bool /*is_live*/) override
     {
+               return true;
         if (type.getQualifier().hasBinding()) {
             const int set = getLayoutSet(type);
 
```

**Comment by gwihlidal** [comment]
This is a critical issue for us, and would appreciate a fix.

**Comment by johnkslang** [comment]
What's the actual issue?  I mean, I see observational comments about binding aliasing, but am a bit unclear what I should deduce is the goal; the rule you need followed for something to work.  Or, is this a driver problem, or specification, or ...?  Thanks.

**Comment by LoopDawg** [comment]
Also, I notice that the aliasing is explicitly requested in the source:

AppendStructuredBuffer<uint> Buf1 : register(**u0**);
AppendStructuredBuffer<uint> Buf2 : register(u1);
AppendStructuredBuffer<uint> Buf3 : register(**u0**);

The example fails to compile in FXC as well, though maybe for a different reason than that.  Is the intent for Buf3 to be ignored in iomapping?

**Comment by punkUser** [comment]
Buf3 is not used at all by the entry point, so yes it should be ignored entirely.

**Comment by johnkslang** [comment]
Shouldn't the driver be ignoring that then?  SPIR-V modules can have buffers that aren't used by a particular entry point.

**Comment by chaoticbob** [comment]
Just out of curiosity, are the unused buffers confusing reflection?

**Comment by punkUser** [comment]
Graham can clarify but I don't think our issue here is with driver, it's that two buffers that *are* used are ending up with binding = 84 (i.e. Buf1@count and Buf2).

**Comment by johnkslang** [comment]
The original post shows Buf1 and Buf2 being 83 and 84.

**Comment by punkUser** [comment]
Yes but Buf1@count and Buf2@count are also real buffers that we need to bind, and it has a duplicate binding, right?

**Comment by johnkslang** [comment]
Ah, I agree the bindings of Buf1@count and Buf2@count appear aliased. Is that the real issue?

**Comment by punkUser** [comment]
Yes in this case we need 4 unique binding points to bind all of our resources. 2 for the base buffers and 2 for the associated counter buffers.

**Comment by gwihlidal** [comment]
Hi,

Yes, the io map resolver appears to fail when there are aliases of a resource in the same namespace. The first issue is:

1) validateBinding in the hlsl io map resolver doesn't support unused aliases, but this is allowed in HLSL\FXC. We use our own io map resolver, so we currently just return true there (but we want to enable more strict checking, so it would be good to only validate used resources)

2) The real bug here, is that when you do have an unused alias, and it has an internal counter buffer, the bindings get all broken (the reserveSlot and getFreeSlot behavior of the io map resolver doesn't seem to be working correctly).

Going back to this example:

AppendStructuredBuffer Buf1 : register(u0);
AppendStructuredBuffer Buf2 : register(u1);
AppendStructuredBuffer Buf3 : register(u0);

Assuming our base shift ssbo offset is 83, I'd expect:

Buf1 to get binding 83 (83 + 0) - u0
Buf2 to get binding 84 (83 + 1) - u1
Buf3 to be ignored (it's unused)

The io map resolver first runs over all resources with explicit bindings, so reserveSlot is called on 0 and 1 (no further resources should ever be allowed to get 83 or 84 as a binding)

Then, the implicit bindings for resources that don't specify explicit registers are evaluated (again, in resolveBinding)

Buf1 has an internal counter buffer, so it should get a binding assigned using getFreeSlot() -> should return 2 -> which is shifted to 83 + 2 -> 85

Buf2 has an internal counter buffer, so it should get a binding assigned using getFreeSlot() -> should return 3 -> which is shifted to 83 + 3 -> 86

Buf3 has an internal counter buffer, but that is unused, so it should also be ignored.

Hopefully this makes more sense?

Thanks,
Graham

**Comment by johnkslang** [comment]
Yes. It mostly makes sense, and having the counts get the same binding is an understandable problem. (I don't always follow "should be ignored", as there are so many actors that could be the ones you are implying could behave differently.)

**Comment by gwihlidal** [comment]
To be clear, I'm not expecting the counter buffers to get the same binding as the parent (in fact, I don't want that). I expect the counter buffers to be treated as if they are normal ssbos that don't define an explicit register binding (we use reflection to find their bind points, anyways).

**Comment by johnkslang** [comment]
I looked into this.  The existing remap algorithms assume an ordered list of binding numbers, with no repetition (fragile use of std::lower_bound). Hence, the validate() methods protected against that.  So, basically, you can get the bad result because you disabled validate().  It's a garbage in, garbage out situation (according to the existing algorithm), where removal of buf3 from the shader makes it all work again.

Will look at making the algorithms less fragile.

Note that fxc says the `u0` binding is illegal, so you seem to be showing shaders that are not legal HLSL, but that is independent from this bug.
