### ISSUE TITLE
FreeGlobalPools is never called in glslang::FinalizeProcess()'s path.

### ISSUE THREAD

**Issue by Kwizatz** [KhronosGroup/glslang#928]
This creates a leak on persistent processes.

**Comment by johnkslang** [comment]
There is a set of related issues and PRs that I will try to address as a whole soon.  Labeling the all as "Memory".

**Comment by Kwizatz** [comment]
Thanks, I may provide a pull request but the solution is not too clear to me.

 ShInitialize calls InitProcess, it would make sence for ShFinalize to call DetachProcess, but DetachProcess itself calls ShFinalize, either way none of the two functions call FreeGlobalPools, it is called instead from DetachThread, which I don't think is the correct place, but I dont know, again DetachThread is never called directly or indirectly from glslang::FinalizeProcess.

**Comment by johnkslang** [comment]
Looking at this now.

Historically, the code was a Win32 DLL, and something else called `DetachThread()` and `DetachProcess()` at the correct time. Because this is no longer a DLL, that stopped happening, and should happen programmatically.

So, yes, the top external interface calls should lead one way or another to once again do all this work.

**Comment by johnkslang** [comment]
#916, which possibly covers three topics, includes this as one of them.

**Comment by johnkslang** [comment]
This has been fixed (made irrelevant) by recent commits that removed the need to free any pools except the one holding the shared symbol table at tear down time.
