### ISSUE TITLE
Implement correct handling of indices for SV_TARGET[n] semantic

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#942]
Apologies, but another HLSL issue...

Looks like the semantic index for SV_TARGET[n] is generating the correct location number. Simple example:
````C++
struct PSOutput {
  float4 oColor0 : SV_TARGET0;
  float4 oColor1 : SV_TARGET2;
};
PSOutput main() {
  PSOutput ret;
  ret.oColor0 = float4(1, 0, 0, 1);
  ret.oColor1 = float4(1, 0, 0, 1);
  return ret;
}
````
....produces loaction=0 for SV_TARGET0 and location=1 for SV_TARGET2, when it should location=0 and location=2, respectively:
```
                              Name 8  "PSOutput"
                              MemberName 8(PSOutput) 0  "oColor0"
                              MemberName 8(PSOutput) 1  "oColor1"
                              Name 10  "@main("
                              Name 13  "ret"
                              Name 26  "flattenTemp"
                              Name 29  "oColor0"
                              Name 32  "oColor1"
                              Decorate 29(oColor0) Location 0
                              Decorate 32(oColor1) Location 1
```
For comparison the FXC output:
````C++
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
ps_5_1
dcl_globalFlags refactoringAllowed
dcl_output o0.xyzw
dcl_output o2.xyzw
````

**Comment by johnkslang** [comment]
Okay, old design decision, as our input back then was to assign locations by declaration order, not based on semantics. Perhaps that should just be limited to the interfaces between stages, and not the output of the fragment stage?

This comes down to how the API sets up the rendering targets. There is an interface that has to match multiple entities.

If interface alignment is done by declaration order today, it would all work as is today. Or, if its based on reflection, it would also work today.  So, it raises the question of how the API side in Vulkan is getting done.

Any input on the confidence in changing design for API matching from declaration order to semantic spelling?  I think it would be the first time any weight is put on the semantic itself.

**Comment by punkUser** [comment]
In HLSL the input/output interfaces of shaders is always explicitly semantic-based, there's no auto-assignment. (SV_Target is just an alias for SV_Target0). This is likely going to be an issue for us for vertex inputs as well as interfaces between shader stages too... I think it's mostly just luck that has allowed us to get so far with things being assigned in declaration order :)

It'll definitely get a bit messy with the latter two as those are string-based semantic names in HLSL rather than indices. Render targets is easier though: in all cases we want SV_TargetN to get assigned to location N, as it has to match our binding code, which is all explicit for render targets (and vertex inputs...).

**Comment by chaoticbob** [comment]
Agreed with @punkUser .

Semantics should be used between shader stages. Removes a layer of confusion that declared order may introduces and fits in line with a HLSL shader writer's workflow. And probably shader generator tools. 

A couple of issues that have raised similar (or related) concerns:
https://github.com/KhronosGroup/glslang/issues/871
https://github.com/KhronosGroup/glslang/issues/643

**Comment by chaoticbob** [comment]
Sorry, I didn't mean to over simplify the overall problem. But it seems like due to the constraints of multiple strings and indices, it may require a solution similar to how IO (re)mapper works.

**Comment by johnkslang** [comment]
@chaoticbob Let's be clear what you are talking about....

> ...the semantic index for SV_TARGET[n]...

That is the output from the pipeline, which I could understand mapping `n -> location`, rather than declaration order, if that doesn't break are things already working (main question to answer), while 

> Semantics should be used between shader stages...

is a different subject (link cross-stage by semantic name, yet requested to be assigned locations in declaration order by several initial ISVs).  Do you want this issue to be about fragment outputs, or do you want it to be about inter-stage I/O? Note there would be massive questions about linking by name for what are independently compiled, and never linked, stages.

Can we keep this issues about fragment output and SV_Target[n] semantics, and use the existing issues for inter-stage link by name?

**Comment by johnkslang** [comment]
I updated #871 that fxc is also assigning registers in declaration order, in the same way glslang assigns locations in declaration order. Unclear yet there is any issue there. Follow up in issue #871 for inter-stage linkage.

**Comment by chaoticbob** [comment]
> >...the semantic index for SV_TARGET[n]...
> That is the output from the pipeline, which I could understand mapping n -> location, rather than declaration order, if that doesn't break are things already working (main question to answer), while

Got it.

> > Semantics should be used between shader stages...

> is a different subject (link cross-stage by semantic name, yet requested to be assigned locations in declaration order by several initial ISVs). Do you want this issue to be about fragment outputs, or do you want it to be about inter-stage I/O? Note there would be massive questions about linking by name for what are independently compiled, and never linked, stages.

Apologies, lets keep it about fragment outputs. Will move discussion to appropriate issue.

> Can we keep this issues about fragment output and SV_Target[n] semantics, and use the existing issues for inter-stage link by name?

Of course, I just walked through a door that was opened. Will also move discussion to appropriate issue.

**Comment by chaoticbob** [comment]
Hi John, was wondering if there's an updates on the semantics with regard to SV_TARGET[n]?
