### ISSUE TITLE
ninja-build is not listed as a build dependency?

### ISSUE THREAD

**Issue by sillydan1** [KhronosGroup/glslang#956]
Why isn't ninja listed as a build dependency? If one was following the described build process and doesn't have the ninja-build package installed (GNU/LINUX) the build process will complain about ninja is missing. 

-
Linux devuan 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u1 (2017-06-18) x86_64 GNU/Linux

**Comment by LoopDawg** [comment]
I wonder if that might be down to some specific local configuration.  I'm on Ubuntu 16.04, don't have ninja installed (I've just barely even heard of it), and all is well.  As Devuan is also a Debian fork, it seems it wouldn't be there either.

```
$ dpkg-query --list '*ninja*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
un  backupninja                      <none>                <none>                (no description available)
un  ninja-build                      <none>                <none>                (no description available)

```

Is there any chance you might have pointed something to it explicitly?  Some versions of cmake can optionally use it, if you throw the right sorts of switches.

**Comment by johnkslang** [comment]
Is the question just about the manual instructions (in the readme), which use ninja?  And, if so, to match, it just needs mention in the manual instructions?  Or, is this really about what's happening internally in cmake?

**Comment by cgmb** [comment]
Ninja is optional. If you drop `-G Ninja` from the cmake command and replace `ninja install` with `make install`, the project builds just fine. The only reason its mentioned is because ninja is faster.

I always build with ninja, but I would be tempted to drop it from the build instructions. People familiar with CMake on Linux know it's an option anyway, and there's no point in confusing people who are new to this stuff.

Though, that would still leave a few unmentioned dependencies: make (on Linux) and a C++ compiler. It might be nice to mention what version of C++ is being targeted. That seems to be C++11.
