### ISSUE TITLE
HLSL: parameter for "all" are not correctly translated into Spir-V opall

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/glslang#968]
Hi,

HLSL allows float, int and bool vectors (and matrices) as input parameter for "all", it internally converts them to bool. The translation of EOpAll of glslang to OpAll of Spir-V it does not check whether the parameter is a boolean vector or something else.
This applies probably to other similar operations to ("any" probably?), but "all" was the operation that broke our shaders when not passing booleans to it.

**Comment by TiemoJung** [comment]
Our current hack is to remove FUI (leaving only B) from the entries of "all" and "any" from hlslIntrinsics and let the implicit convert handle the mismatch.

**Comment by johnkslang** [comment]
@LoopDawg do you have an opinion about whether conversion for any/all should happen outside versus inside the built-in function?

**Comment by LoopDawg** [comment]
Assuming this doesn't happen with very many builtins, I'm a bit partial to inside.  I could be persuaded differently though, e.g, by an argument of pragmatism.  Here's my reasoning for inside:

The intrinsics table (in hlslParseables) was made to capture the HLSL language intrinsics, and it creates prototypes accordingly.  In some cases like "sin", HLSL only defines a float proto, and if you pass an int, it issues a conversion opcode (outside the sin op), or for some opcodes, it issues an error.  That's also how glslang behaves: there's a layer matching the intrinsic, and a conversion added if needed.

I feel like the "inside" approach leaves the intrinsic table cleanly capturing the HLSL intrinsics (rather than a mismash which includes the peculiarities of what we have to do to translate to them).  In the cases it's needed, glslang then decomposes into whatever's required to implement the intrinsic as defined, e.g. in HlslParseContext::decomposeIntrinsic().  There's precedent for such type conversions in more complex cases.  It's just that some intrinsics can map directly across to a SPIR-V opcode, and any/all are being treated that way even though they aren't.

Inside avoids blurred layers, IMHO.

**Comment by LoopDawg** [comment]
Oh, another argument for inside would be: if a decomposition handles it, it has the opportunity to do some type-specific cleverness.

**Comment by johnkslang** [comment]
Agreed with leaving the prototypes alone and doing a decomposition.

**Comment by LoopDawg** [comment]
OK, there's a #974 for that.

Related but slightly different topic: maybe there's a lurking issue around intrinsics accepting matrix types.  Most of the SPIR-V opcodes don't, and most of the HLSL intrinsics do, and (AFAIK) there's nothing being done about it.  In that case, maybe it wouldn't be so convenient for every single opcode to have a decomposition just for that purpose, and it should be handled in a single place somehow, excepting cases where it isn't a component-wise operation such as matrix multiply or whatnot.
