### ISSUE TITLE
HLSL: does not support SV_PrimitiveID builtin variable

### ISSUE THREAD

**Issue by xlpiao** [KhronosGroup/glslang#979]
The following HLSL code comes from <Tutorial 38: Hardware Tessellation> at http://www.rastertek.com/tutdx11.html
```hlsl
////////////////////////////////////////////////////////////////////////////////
// Filename: color.hs
// I save it as color.hlsl.hull.tesc
////////////////////////////////////////////////////////////////////////////////


/////////////
// GLOBALS //
/////////////
cbuffer TessellationBuffer : register(b0)
{
    float tessellationAmount;
    float3 padding;
};


//////////////
// TYPEDEFS //
//////////////
struct HullInputType
{
    float3 position : POSITION;
    float4 color : COLOR;
};

struct ConstantOutputType
{
    float edges[3] : SV_TessFactor;
    float inside : SV_InsideTessFactor;
};

struct HullOutputType
{
    float3 position : POSITION;
    float4 color : COLOR;
};


////////////////////////////////////////////////////////////////////////////////
// Patch Constant Function
////////////////////////////////////////////////////////////////////////////////
ConstantOutputType ColorPatchConstantFunction(InputPatch<HullInputType, 3> inputPatch, uint patchId : SV_PrimitiveID)
{
    ConstantOutputType output;


	// Set the tessellation factors for the three edges of the triangle.
    output.edges[0] = tessellationAmount;
    output.edges[1] = tessellationAmount;
    output.edges[2] = tessellationAmount;

	// Set the tessellation factor for tessallating inside the triangle.
    output.inside = tessellationAmount;

    return output;
}


////////////////////////////////////////////////////////////////////////////////
// Hull Shader
////////////////////////////////////////////////////////////////////////////////
[domain("tri")]
[partitioning("integer")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(3)]
[patchconstantfunc("ColorPatchConstantFunction")]

HullOutputType ColorHullShader(InputPatch<HullInputType, 3> patch, uint pointId : SV_OutputControlPointID, uint patchId : SV_PrimitiveID)
{
    HullOutputType output;


	// Set the position for this control point as the output position.
    output.position = patch[pointId].position;

	// Set the input color as the output color.
    output.color = patch[pointId].color;

    return output;
}
```

**Comment by johnkslang** [comment]
Glslang does have support for mapping `SV_PrimitiveId` to SPIR-V `BuiltIn PrimitiveId`, and there is a test that does so (hlsl.hull.3.tesc).

Can you narrow this down a bit more as to what the issue/problem/symptoms might be?

**Comment by xlpiao** [comment]
```bash
glslangValidator -V -D color.hlsl.hull.tesc -e ColorHullShader -o color.hlsl.hull.tesc.spv
ERROR: 0:0: '' : unable to find patch constant function builtin variable
ERROR: 1 compilation errors.  No code generated.
```

This error happens when both patchconstantfunc and entrypoint function use SV_PrimitiveId variable.

**Comment by johnkslang** [comment]
@LoopDawg does this trigger anything off the top of your head?

**Comment by LoopDawg** [comment]
There's a call to the patch constant function (or possibly, multiple calls to it) which is synthesized inside the entry point.  The parameters to the PCF can be in arbitrary order (there's no explicit call to the PCF), and connecting them to the right values from the entry point happens based on the declared builtin type.

If that symbol isn't found in the linkage while creating the argument list, this error results.  I don't see why that would be happening here though, so probably a defect.  The mechanism is working other cases, so it might be something specific to this workload.  I can have a look and try to see what's happening.

**Comment by LoopDawg** [comment]
A couple of things I've figured out so far:

1. This shader doesn't actually use the variable declared with SV_PrimitiveID.  As a local workaround, you could probably comment it out in both functions' param list and compile the code above with current glslang.

2. The problem is upstream of the patch constant function synthesis code, which I think will do the right thing here if given good data as input.  (That eliminates a fairly complex piece of code from the picture).  The PCF argument list members are matched via system semantics - i.e, by builtin type, because that's the only handle available (the names and param list order could be different).  The builtin type in this case is being lost because glslang does not believe it's a valid one for the hull stage.  That's why the PCF synthesizer fails to find it.

It isn't seen as a valid builtin because it's being used as a stage Input to a HS, whereas in Vulkan, it must be declared as a stage Output in HS/DS/GS, and stage Input in GS/PS, per [section 14.6](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#interfaces-builtin-variables).  There's explicit code in glslang matching the Vulkan docs, and rejecting it as an HS Input builtin.  If I locally hack the code to allow it, the shader compiles in glslang.

HLSL docs say that SV_PrimitiveID ["Can be written to by the geometry or pixel shaders, and read by the geometry, pixel, hull or domain shaders."](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647%28v=vs.85%29.aspx).  This would seem to allow the shader above's use as an HS stage input.

So (unless I'm missing some subtlety, such as SV_PrimitiveID mapping situationally to several different builtins?) there appears to be a mismatch between HLSL and Vulkan.  SPIR-V docs say "Primitive ID in a Geometry Execution Model." (a little confusing, since I think it's also valid for tessellation models), and then punt over to the Vulkan spec for details, per link above.

I've pretty well reached the end of what I know about PrimitiveIDs.  If it actually is OK to declare it as a HS input, then the problem is an easy fix.  I'm just not sure that is OK, per the Vulkan docs.  Maybe someone with more knowledge can add some clarity.

**Comment by johnkslang** [comment]
@LoopDawg wrote

> If it actually is OK to declare it as a HS input, then the problem is an easy fix. I'm just not sure that is OK, per the Vulkan docs.

The Vulkan spec says this:

> PrimitiveId
>
> Decorating a variable with the PrimitiveId built-in decoration will make that variable contain the index of the current primitive.
>
> In tessellation control and tessellation evaluation shaders, it will contain the index of the patch within the current set of rendering primitives that correspond to the shader invocation.

Does that answer the question? It seems the SPIR-V specification refers to it overly narrowly, if this is all the same subject.

**Comment by LoopDawg** [comment]
OK, provided that's just an overly narrow reference, then #1178 has a fix.

**Comment by johnkslang** [comment]
From the Vulkan spec:

> In a tessellation control or tessellation evaluation shader, any variable decorated with PrimitiveId must be declared using the Output storage class.

I think that's the problem. In GLSL, gl_PrimitiveID in is input to the tessellation stages, not an output.  It's only an output for geometry.

**Comment by johnkslang** [comment]
I opened a Khronos-internal issue for this.

**Comment by johnkslang** [comment]
I'll also try removing these as outputs.
