### ISSUE TITLE
SPIR-V missing memory qualifiers on function parameters

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/glslang#995]
For the attached glsl, there are memory qualifiers **readonly**, **writeonly**, **coherent** on the image parameters of the definitions of image_store and image_load.    
These are not represented in the SPIR-V produced by glslang, i.e. there are no decorations **NonWritable**, **NonReadable**, **Coherent** on the function parameters.
Should there be?  
If not, how should a SPIR-V consumer deduce e.g. that these calls to imageLoad and imageStore are coherent operations?
[imageReadWriteParam.frag.txt](https://github.com/KhronosGroup/glslang/files/1152478/imageReadWriteParam.frag.txt)

**Comment by johnkslang** [comment]
Yes, Khronos decided a while back to decorate function parameters, so that static analysis did not have to cross function boundaries. There are several decoration classes that need to be added.

So, this is a good trigger to catch glslang up to this decision. I'll added the infrastructure for this and then the memory decorations.
